### ISSUE TITLE
Development setup produces "Merging undefined is not supported" error

### ISSUE THREAD

**Issue by maxbrieiev** [quasarframework/quasar#10257]
**Describe the bug**
I get errors following instructions in [contribution guide](https://quasar.dev/contribution-guide/contribution-guide#contributing-to-the-quasar-ui-source-code) 

**To Reproduce**
1. Clone:
```
max@arch-max ~/code % git clone git@github.com:quasarframework/quasar.git
Cloning into 'quasar'...
remote: Enumerating objects: 121138, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 121138 (delta 43), reused 60 (delta 12), pack-reused 121022
Receiving objects: 100% (121138/121138), 91.72 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (92471/92471), done.
git clone git@github.com:quasarframework/quasar.git  11.43s user 4.34s system 27% cpu 58.005 total
```

2. Install deps:
```
max@arch-max ~/code % cd quasar/ui
max@arch-max ~/code/quasar/ui (git)-[dev] % yarn
yarn install v1.22.10
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @quasar/app > webpack-dev-server > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @quasar/app > webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning babel-preset-es2015-rollup > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning babel-preset-es2015-rollup > babel-plugin-external-helpers > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @babel/eslint-parser@7.14.7" has unmet peer dependency "@babel/core@>=7.11.0".
warning " > eslint-webpack-plugin@2.5.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > rollup-plugin-typescript2@0.29.0" has unmet peer dependency "typescript@>=2.4.0".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 29.28s.
yarn  17.28s user 4.64s system 74% cpu 29.479 total
```

3. Starting demo app gives the error:
```
max@arch-max ~/code/quasar/ui (git)-[dev] % yarn dev
yarn run v1.22.10
$ cd ./dev && node ./script.dev.js dev && cd ..

 Dev mode.......... spa
 Pkg quasar........ v2.0.3
 Pkg @quasar/app... v3.0.3
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 80.37% of global marketshare):
 · Chrome for Android >= 92
 · Firefox for Android >= 90
 · Android >= 92
 · Chrome >= 91
 · Edge >= 91
 · Firefox >= 89
 · iOS >= 14.0-14.4
 · Opera >= 76
 · Safari >= 14

/home/max/code/quasar/ui/node_modules/webpack-merge/dist/index.js:63
            throw new TypeError("Merging undefined is not supported");
                  ^

TypeError: Merging undefined is not supported
    at mergeWithOptions (/home/max/code/quasar/ui/node_modules/webpack-merge/dist/index.js:63:19)
    at merge (/home/max/code/quasar/ui/node_modules/webpack-merge/dist/index.js:52:35)
    at QuasarConfFile.compile (/home/max/code/quasar/ui/node_modules/@quasar/app/lib/quasar-conf-file.js:392:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async goLive (/home/max/code/quasar/ui/node_modules/@quasar/app/bin/quasar-dev:237:3)
error Command failed with exit code 1.
```

Node: v16.5.0
NPM: 7.17.0
Yarn: 1.22.10

**Comment by pdanpdan** [comment]
the correct sequence is:

```bash
yarn
yarn build
yarn dev
```

You must do a `yarn build` at least once between cloning the repo and starting the dev.
