### ISSUE TITLE
My application quasar compiled into ssr  not running on heroku. I get 500 error status from heroku server.

### ISSUE THREAD

**Issue by francelwebdev** [quasarframework/quasar#11075]
hi, since yesterday, i can't deploy my quasar application compiled in ssr on heroku. I send the ssr folder to github and it automatically deploys on heroku and then after the build on heroku when I go to the url i gets a 500 error.

**Comment by rstoenescu** [comment]
Hi,

This is most likely not a Quasar issue.
But regardless, more info is needed.

You first need to check out what the error is. Go to your render.js SSR middleware file and log the error (`console.error(err)` before the `res.status(500).send('500 | Internal Server Error')`).

**Comment by rstoenescu** [comment]
...and then check the log (assuming you have a logger in place).
Otherwise send the error too in the `.send(...)` as String so you'll see it on the browser page.

**Comment by francelwebdev** [comment]
Thank you for your quick reply.
This is the heroku log.

2021-10-22T14:55:13.097148+00:00 app[api]: Deploy e6e54a42 by user francel.webdev@gmail.com
2021-10-22T14:55:13.120570+00:00 app[api]: Scaled to web@1:Free by user francel.webdev@gmail.com
2021-10-22T14:55:16.000000+00:00 app[api]: Build succeeded
2021-10-22T14:55:16.976941+00:00 heroku[web.1]: Starting process with command `npm start`
2021-10-22T14:55:18.155379+00:00 app[web.1]: 
2021-10-22T14:55:18.155394+00:00 app[web.1]: > quasar_application@0.0.1 start
2021-10-22T14:55:18.155394+00:00 app[web.1]: > node index.js
2021-10-22T14:55:18.155395+00:00 app[web.1]: 
2021-10-22T14:55:18.358451+00:00 app[web.1]: Server listening at port 8408
2021-10-22T14:55:18.764780+00:00 heroku[web.1]: State changed from starting to up
2021-10-22T14:55:25.314637+00:00 app[web.1]: Error: Cannot find module '@vuelidate/validators'
2021-10-22T14:55:25.314652+00:00 app[web.1]: Require stack:
2021-10-22T14:55:25.314653+00:00 app[web.1]: - /app
2021-10-22T14:55:25.314654+00:00 app[web.1]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-10-22T14:55:25.314655+00:00 app[web.1]:     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
2021-10-22T14:55:25.314655+00:00 app[web.1]:     at _resolve (/app/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:47:50)
2021-10-22T14:55:25.314656+00:00 app[web.1]:     at _require (/app/node_modules/@quasar/ssr-helpers/lib/create-bundle.js:56:23)
2021-10-22T14:55:25.314657+00:00 app[web.1]:     at Object.3535 (render-app.js:830:18)
2021-10-22T14:55:25.314657+00:00 app[web.1]:     at __webpack_require__ (render-app.js:934:41)
2021-10-22T14:55:25.314658+00:00 app[web.1]:     at Object.6300 (render-app.js:203:79)
2021-10-22T14:55:25.314658+00:00 app[web.1]:     at __webpack_require__ (render-app.js:934:41)
2021-10-22T14:55:25.314659+00:00 app[web.1]:     at render-app.js:1066:131
2021-10-22T14:55:25.314659+00:00 app[web.1]:     at render-app.js:1189:3 {
2021-10-22T14:55:25.314659+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2021-10-22T14:55:25.314660+00:00 app[web.1]:   requireStack: [ '/app' ]
2021-10-22T14:55:25.314660+00:00 app[web.1]: }
2021-10-22T14:55:25.655453+00:00 heroku[router]: at=info method=GET path="/" host=app-immobiliere-quasar-ssr.herokuapp.com request_id=748ef962-fa46-4801-a1ce-53da504a0914 fwd="197.234.221.185" dyno=web.1 connect=0ms service=536ms status=500 bytes=337 protocol=https

**Comment by francelwebdev** [comment]
I have not any vuelidate package in my package.json file but vee-validate for form validation.

This is my package.json file.

{
  "name": "quasar_application",
  "version": "0.0.1",
  "description": "A Quasar Framework app",
  "productName": "Quasar App",
  "author": "Francel <francel.webdev@gmail.com>",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.10.11",
    "@urql/vue": "^0.5.0",
    "add": "^2.0.6",
    "axios": "^0.23.0",
    "core-js": "^3.18.3",
    "graphql": "^15.6.0",
    "graphql-hooks": "^5.4.1",
    "graphql-request": "^3.6.1",
    "pinia": "^2.0.0-rc.14",
    "quasar": "^2.1.9",
    "vee-validate": "^4.5.4",
    "vue-i18n": "^9.0.0-beta.0",
    "vue-tel-input": "^6.0.0-beta.0",
    "vuex": "^4.0.1",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.13.14",
    "@quasar/app": "^3.1.5",
    "dotenv": "^10.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^7.20.0",
    "eslint-webpack-plugin": "^3.0.1",
    "quasar-app-extension-vuelidate-rules": "^0.4.0",
    "workbox-webpack-plugin": "^6.0.0"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 14.x",
    "npm": ">= 8.x",
    "yarn": ">= 1.x"
  }
}

**Comment by francelwebdev** [comment]
OK it works, the page is displayed https://app-immobiliere-quasar-ssr.herokuapp.com. I installed the package
Vuelidate (which is recommended for form field validation in the quasar documentation).

Thank you very much, you are doing a really great job. I will fund this project when my project starts to work.

**Comment by rstoenescu** [comment]
Glad to help.

Although, I'd still comment: You or one of your installed dependencies is relying on `@vuelidate/validators`, cause Quasar itself has no deps and does not imports vuelidate.
