### ISSUE TITLE
 [/@quasar/vite-plugin]Cannot use import statement outside a module

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#11107]
follow the official guid , there is a bug:

```shell

failed to load config from /Users/Young/my-vue-app/vite.config.js
error when starting dev server:
/Users/Young/my-vue-app/node_modules/@quasar/vite-plugin/index.js:1
import quasar from './src/plugin'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/Users/Young/my-vue-app/node_modules/vite/dist/node/chunks/dep-be032392.js:68679:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/Young/my-vue-app/vite.config.js:31:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by RebeccaStevens** [comment]
I've just started getting this same issue (for the same file).
Is there a known fix?
