### ISSUE TITLE
prevent scroll issues an error in spa in jest test

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [quasarframework/quasar#11286]
**Describe the bug**
TypeError: Cannot read property 'ios' of undefined

      at apply (node_modules/quasar/dist/quasar.cjs.prod.js:6:155837)
      at preventScroll (node_modules/quasar/dist/quasar.cjs.prod.js:6:157237)
      at preventBodyScroll (node_modules/quasar/dist/quasar.cjs.prod.js:6:157340)
      at node_modules/quasar/dist/quasar.cjs.prod.js:6:161781
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6599:22)
      at callWithAsyncErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6608:21)
      at Array.job (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7007:17)
      at flushPreFlushCbs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6767:45)   
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6807:5)
      at flushJobs (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6846:13)

**To Reproduce**
1. Mount a Component that uses a dialog and is not set to seemless
2. Try to run the test and take a screenshot

**Expected behavior**
Should not throw an error

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.1.3

Quasar mode:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [X] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10 10.0.19042
Node: 14.17.3
NPM:  7.20.6

**Additional context**
The error disappears when seemless is set which leads me to the conclusion that the trigger for this issue is here https://github.com/quasarframework/quasar/blob/82ba9059401c4324fe390d527a8faaa86a76d53f/ui/src/components/dialog/QDialog.js#L167 because https://github.com/quasarframework/quasar/blob/82ba9059401c4324fe390d527a8faaa86a76d53f/ui/src/components/dialog/QDialog.js#L143 will be false.
But the source of the issue seems to be here https://github.com/quasarframework/quasar/blob/82ba9059401c4324fe390d527a8faaa86a76d53f/ui/src/utils/prevent-scroll.js#L111
Since during the test `client` doesn't seem to have `.is`

**Comment by IlCallo** [comment]
Closing in favor of https://github.com/quasarframework/quasar-testing/issues/190
The underlying issue is probably the same

**Comment by IlCallo** [comment]
Another related, probably the same issue: https://github.com/quasarframework/quasar-testing/issues/186

**Comment by sschneider-ihre-pvs** [comment]
@IlCallo quasarframework/quasar-testing#190 seem to be something different to me, no teleport, no dialog no backdrop ?

**Comment by IlCallo** [comment]
Yeah, issue 186 looks more like it
The underlying issue appears related to me anyway

**Comment by sschneider-ihre-pvs** [comment]
ok, at least you have some line numbers that might help and a reproducible scenario
