### ISSUE TITLE
Recent changes to Screen plugin fail in a testing environment

### ISSUE THREAD

**Issue by maparent** [quasarframework/quasar#12318]
### What happened?

Updating quasar from 1.17.8 to 1.18.2.
Running a test using `@quasar/quasar-app-extension-testing-unit-jest`.
I get new errors upon calling mountQuasar. (See log section)

Upon analyzing the backtrace, this corresponds to the change in at line 53 of ui/src/plugins/Screen.js introduced in  3c22bb35be4e5059127532d1c8b84f94a5846c46 

The new calculation assumes the scrollingElement is present, which is not true in a testing environment.

### What did you expect to happen?

No errors.

### Reproduction URL

https://github.com/topicquests/qs-demo/runs/5046344036?check_suite_focus=true

### How to reproduce?

Create a jest test using the components above.

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

### Platforms/Browsers

Other

### Quasar info output

```shell
Operating System - Darwin(21.3.0) - darwin/arm64
NodeJs - 17.4.0

Global packages
  NPM - 8.4.0
  yarn - 1.22.17
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 1.18.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.2.11 -- Quasar Framework local CLI
  @quasar/extras - 1.12.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.14 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.5.1 -- Official router for Vue.js 2
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.17.0 -- Babel compiler core.
  webpack - 4.44.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 1.0.5 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-jest - 2.2.3 -- A Quasar App Extension for running Jest tests

Networking
  Host - elbereth
  en0 - 192.168.1.251
```

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'clientWidth')

      68 |     propsData: {},
      69 |   };
    > 70 |   return mountQuasar(MainLayout, merge(defaultMountOptions));
         |                     ^
      71 | }
      72 |
      73 | describe("MainLayout.vue not logged in button", () => {

      at o (node_modules/quasar/dist/quasar.common.js:6:7738)
      at a (node_modules/quasar/dist/quasar.common.js:6:8049)
      at c (node_modules/quasar/dist/quasar.common.js:6:9271)
      at Object.install (node_modules/quasar/dist/quasar.common.js:6:9376)
      at Object.install (node_modules/quasar/dist/quasar.common.js:6:24773)
      at Function.Vue.use (node_modules/vue/dist/vue.runtime.common.dev.js:5101:22)
      at Function.instance.use (node_modules/@vue/test-utils/dist/vue-test-utils.js:13931:14)
      at Object.createLocalVueForQuasar (node_modules/@quasar/quasar-app-extension-testing-unit-jest/src/helpers/create-local-quasar.ts:15:12)
      at mountQuasar (node_modules/@quasar/quasar-app-extension-testing-unit-jest/src/helpers/mount-quasar.ts:24:20)
      at createWrapper (src/layouts/__tests__/MainLayout.spec.js:70:21)
      at Suite.<anonymous> (src/layouts/__tests__/MainLayout.spec.js:218:19)
      at Object.<anonymous> (src/layouts/__tests__/MainLayout.spec.js:202:1)
```

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available shortly in Quasar v2.5.3 and v1.18.3
