### ISSUE TITLE
Cannot start project without ESLint selected

### ISSUE THREAD

**Issue by customautosys** [quasarframework/quasar#12796]
### What happened?

I just tried to create a new project without ESLint and it didn't work due to undefined lintConfig.

### What did you expect to happen?

Project is created

### Reproduction URL

https://github.com/quasarframework/quasar/issues/12796

### How to reproduce?

npm init quasar, do not select ESLint

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Operating System        Windows_NT(10.0.22000) - win32/x64
NodeJs                  16.14.0

Global packages
  NPM                   8.3.1
  yarn                  Not installed
  @quasar/cli           1.3.0
  @quasar/icongenie     2.5.0
  cordova               11.0.0

Networking
  Host                  DESKTOP-UVPL1F6
  Wi-Fi                 192.168.1.189
```

### Relevant log output

```Shell
$ npm init quasar


 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... caswebsite
√ Target directory "caswebsite" is not empty. Remove existing files and continue? ... yes
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Typescript
√ Pick Quasar App CLI variant: » Quasar App CLI with Vite (BETA stage)
√ Package name: ... caswebsite
√ Project product name: (must start with letter if building mobile apps) ... Custom Automated Systems ® Pte Ltd
√ Project description: ... Custom Automated Systems ® Pte Ltd website
√ Author: ... Custom Automated Systems ® Pte Ltd
√ Pick a Vue component style: » Composition API
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: » State Management (Pinia), Axios

 Quasar • Generating files...

 - index.html
 - package.json
undefined:21
 if (lintConfig === 'prettier') { ;
 ^

ReferenceError: lintConfig is not defined
    at eval (eval at <anonymous> (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\lodash.template\index.js:1550:12), <anonymous>:21:2)
    at Object.module.exports.renderTemplate (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\create-quasar\utils\index.js:80:37)
    at module.exports (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\create-quasar\templates\app\quasar-v2\ts-vite\index.js:64:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\create-quasar\templates\app\quasar-v2\index.js:29:3)
    at async module.exports (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\create-quasar\templates\app\index.js:9:3)
    at async run (C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_npx\bffef4e514f2f7e3\node_modules\create-quasar\index.js:70:3)
npm ERR! code 1
npm ERR! path C:\Users\WilsonFooYuKang\Documents\Gitlab\quasar_upgrade
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-quasar

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WilsonFooYuKang\AppData\Local\npm-cache\_logs\2022-03-15T04_15_47_319Z-debug-0.log
```

**Comment by diadal** [comment]
try `npm create quasar`

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fixed it.
