### ISSUE TITLE
SASS variables are not prepended on vue files in SSR mode

### ISSUE THREAD

**Issue by Dodobibi** [quasarframework/quasar#12838]
### What happened?

SASS variables (or quasar variables : $primary...) cannot be used in vue files in SSR mode. No issue in SPA mode.

```html
<style lang="scss">
.blue {
  background-color: $blue-6;
}
</style>
```

### What did you expect to happen?

Correctly prepend quasar variables

### Reproduction URL

https://github.com/Dodobibi/TestSsrSass

### How to reproduce?

Create a clean Quasar project, with 

- Typescript
- @quasar/app-vite

Add SSR mode

```html
// in IndexPage.vue

<template>
  <q-page class="row items-center justify-evenly">
    <div class="blue">Must be blue blacground</div>
  </q-page>
</template>

<style lang="scss">
.blue {
  background-color: $blue-6;
}
</style>
```

Run : `quasar dev -m ssr`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

SSR Mode

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19044) - win32/x64
NodeJs - 16.13.0

Global packages
  NPM - 8.1.0
  yarn - 1.22.15
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - Not installed
  vuex - Not installed
  vite - 2.8.6 -- Native-ESM powered web dev build tool
  eslint - 8.11.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
11:41:42 [vite] Error when evaluating SSR module /src/pages/IndexPage.vue:
Error: Undefined variable.
  ╷
3 │   background-color: $primary;
  │                     ^^^^^^^^
  ╵
  src\pages\IndexPage.vue 3:21  root stylesheet
    at Object._newRenderError (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:13172:19)
    at Object._wrapException (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:12998:16)
    at _render_closure1.call$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:81115:21)
    at _RootZone.runBinary$3$3 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:27260:18)
    at _FutureListener.handleError$1 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25816:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:26114:49)
    at Object._Future__propagateToListeners (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:4536:77)
    at _Future._completeError$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25946:9)
    at _AsyncAwaitCompleter.completeError$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25600:12)
    at Object._asyncRethrow (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:4335:17)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Undefined variable.
  ╷
3 │   background-color: $primary;
  │                     ^^^^^^^^
  ╵
  src\pages\IndexPage.vue 3:21  root stylesheet
    at Object._newRenderError (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:13172:19)
    at Object._wrapException (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:12998:16)
    at _render_closure1.call$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:81115:21)
    at _RootZone.runBinary$3$3 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:27260:18)
    at _FutureListener.handleError$1 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25816:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:26114:49)
    at Object._Future__propagateToListeners (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:4536:77)
    at _Future._completeError$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25946:9)
    at _AsyncAwaitCompleter.completeError$2 (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:25600:12)
    at Object._asyncRethrow (C:\PROJETS\TestSass\node_modules\sass\sass.dart.js:4335:17) {
  formatted: 'Error: Undefined variable.\n' +
    '  ╷\n' +
    '3 │   background-color: $primary;\n' +
    '  │                     ^^^^^^^^\n' +
    '  ╵\n' +
    '  src\\pages\\IndexPage.vue 3:21  root stylesheet',
  line: 3,
  column: 21,
  file: 'C:\\PROJETS\\TestSass\\src\\pages\\IndexPage.vue',
  status: 1,
  id: 'C:\\PROJETS\\TestSass\\src\\pages\\IndexPage.vue',
  frame: 'Error: Undefined variable.\n' +
    '  ╷\n' +
    '3 │   background-color: $primary;\n' +
    '  │                     ^^^^^^^^\n' +
    '  ╵\n' +
    '  src\\pages\\IndexPage.vue 3:21  root stylesheet',
  plugin: 'vite:css',
  pluginCode: '\n.blue {\n  background-color: $primary;\n}\n',
  loc: {
    file: 'C:/PROJETS/TestSass/src/pages/IndexPage.vue',
    line: 11,
    column: 21
  }
}
```

**Comment by rstoenescu** [comment]
Hi,

Thanks for reporting.
Will submit a fix later this evening or tomorrow morning next thing.

**Comment by rstoenescu** [comment]
Was a problem in our vite plugin.
Just yarn install again. It should pick the latest `@quasar/vite-plugin` through `@quasar/app-vite`. If it doesn't and you still have the issue, just delete node_modules and yarn.lock and install again.
