### ISSUE TITLE
All of my custom directives doesnt working for ssr builds after quasar and vue upgrade

### ISSUE THREAD

**Issue by LefterisMavrakis** [quasarframework/quasar#13171]
I upgraded my quasar v2 app today and also vue3 and vue router 4. All of my directives doesnt working for ssr builds.

src/boot/click-outside-directive.js

```
import { boot } from 'quasar/wrappers'

export default boot(async ({ app, router, store, ssrContext }) => {
  app.directive('click-outside', {
    updated(el, binding) {
     ...
    },
    unmounted(el) {
     ...
    },
    getSSRProps (binding) {
      // server-side implementation:
      // return the props to be rendered.
      // getSSRProps only receives the directive binding.
      return {
        class: 'click-outside'
      }
    }
  })
})
```

src-ssr/directives/click-outside.js

`export default (clickOutside) => {
  return {
    props:[],
    getSSRProps(){
      return {}
    }
  }
}`

I still get
 [Vue warn]: Failed to resolve directive: click-outside
ssr error TypeError: Cannot read properties of undefined (reading 'getSSRProps')

I added getSSRProps in directive definitions after upgrade
Any ideas if there is something wrong to my implementation?

Do we need to create an App extension in order to provide a custom directive for ssr builds?

_Originally posted by @LefterisMavrakis in https://github.com/quasarframework/quasar/discussions/10832#discussioncomment-2560719_

**Comment by rstoenescu** [comment]
The Vue team finally fixed an issue in Vue so that the approach with separate directive declaration in src-ssr/directives is no longer needed. Just specify your directive in /src (so in the UI code) and make sure that it contains getSSRProps(). Also, after you've done so for all the directives, delete src/directives as it serves no purpose anymore. This info is also in the release notes.

**Comment by rstoenescu** [comment]
The Vue team finally fixed an issue in Vue so that the approach with separate directive declaration in src-ssr/directives is no longer needed. Just specify your directive in /src (so in the UI code) and make sure that it contains getSSRProps(). Also, after you've done so for all the directives, delete src/directives as it serves no purpose anymore. This info is also in the release notes.

**Comment by LefterisMavrakis** [comment]
Thank you Razvan. I appreciate your fast response!

I deleted src-ssr/directives folder but i am still getting the error

[Vue warn]: Failed to resolve directive: click-outside
ssr error TypeError: Cannot read properties of undefined (reading 'getSSRProps')
    at ssrGetDirectiveProps (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:967:42)
    at ssrRender (chunk-src_layouts_MainLayout_vue.js:6965:87)
    at renderComponentSubTree (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
    at renderVNodeChildren (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:325:9)
    at renderElementVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:376:17)
    at renderVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:307:17)
    at renderVNodeChildren (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:325:9)
    at renderElementVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:376:17)
[Quasar Dev Webserver] / -> error during render
TypeError: Cannot read properties of undefined (reading 'getSSRProps')
    at ssrGetDirectiveProps (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:967:42)
    at ssrRender (chunk-src_layouts_MainLayout_vue.js:6965:87)
    at renderComponentSubTree (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
    at renderVNodeChildren (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:325:9)
    at renderElementVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:376:17)
    at renderVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:307:17)
    at renderVNodeChildren (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:325:9)
    at renderElementVNode (/home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:376:17)

Below is my directive and it is placed inside a boot file. The boot file is registered in quasar.conf.js with server: false parameter

```
 app.directive('click-outside', {
    updated(el, binding) {
     ...
    },
    unmounted(el) {
     ...
    },
    getSSRProps (binding) {
      // server-side implementation:
      // return the props to be rendered.
      // getSSRProps only receives the directive binding.
      return {
        id: 'click-outside'
      }
    }
  })
```
The way i add to an element is like this

`v-click-outside="()=> toggleOptionsShow(false)"`


The errror seems  it comes from the vue package (vue: "^3.2.32")

 Open: /home/lefte/Projects/pockee-website-quasar/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js

```
    function ssrGetDirectiveProps(instance, dir, value, arg, modifiers = {}) {
        if (typeof dir !== 'function' && dir.getSSRProps) {
            return (dir.getSSRProps({
                dir,
```

So in the file above i tried to log the typeof dir like this

```
function ssrGetDirectiveProps(instance, dir, value, arg, modifiers = {}) {
  console.log(typeof dir)
    if (typeof dir !== 'function' && dir.getSSRProps) {
```
Then in my console where the dev server is running (quasar dev -m ssr) i can see that the typeof dir is undefined 

finally i modified server-renderer.cjs.js ssrGetDirectiveProps() and added an extra check for the dir

```
function ssrGetDirectiveProps(instance, dir, value, arg, modifiers = {}) {
    if (typeof dir !== 'function' && typeof dir !== 'undefined') {
      if(dir.getSSRProps) {
        return (dir.getSSRProps({
          dir,
          instance,
          value,
          oldValue: undefined,
          arg,
          modifiers
        }, null) || {});
      }
    }
    return {};
}
```

Everything works fine now but this is not an actual solution

**Comment by LefterisMavrakis** [comment]
Ok i found the solution!

I had my directives registered in quasar.conf.js like this:

```
 { path: 'click-outside-directive', server: false },
  { path: 'cleave-directive', server: false }
```
 
 That's why they were undefined for vue ssrGetDirectiveProps method during ssr.
 The reason i had set them not to run in server side was that both directives accessing window and document object models which are not available during ssr.
 
 Now i have changed directive registrations as below in order to register in both server and client sides
 
 ```
  'click-outside-directive',
  'cleave-directive'
```

Everything works fine now!

Hope it helps!
