### ISSUE TITLE
SPA build with axios and vue-i18n results in TypeError: s is not a function

### ISSUE THREAD

**Issue by jeancaffou** [quasarframework/quasar#13483]
With new scaffolding and the IndexPage.vue:
```javascript
export default boot(({ app }) => {
  const i18n = createI18n({
    globalInjection: true,
    locale: 'en',
    messages
  })

  // Set i18n instance on app
  app.use(i18n)
})
```

```javascript
      vitePlugins: [
        ['@intlify/vite-plugin-vue-i18n', {
          // if you want to use Vue I18n Legacy API, you need to set `compositionOnly: false`
          compositionOnly: false,

          // you need to set i18n resource including paths !
          include: path.resolve(__dirname, './src/i18n/**')
        }]
      ]
```
the error message is:
```
index.0d7c96e5.js:1 TypeError: s is not a function
    at Ke (i18n.69efe207.js:25:3625)
    at $e (i18n.69efe207.js:25:3003)
    at i18n.69efe207.js:29:2690
    at U (i18n.69efe207.js:29:2565)
    at Object.ve [as t] (i18n.69efe207.js:29:2685)
    at Object.t (i18n.69efe207.js:29:8572)
    at Proxy.$t (i18n.69efe207.js:29:12980)
    at IndexPage.2785adea.js:10:1612
    at r (index.0d7c96e5.js:1:15622)
    at Pe (QBtn.d2433f53.js:1:838)
```

_Originally posted by @znbang in https://github.com/quasarframework/quasar/issues/12814#issuecomment-1069825139_

**Comment by jeancaffou** [comment]
Solved by adding `runtimeOnly: false,` in `vitePlugins` options, as referenced in https://github.com/intlify/vite-plugin-vue-i18n/issues/91
This bug happens when using `$t` in template files

The unminified error is:
```
TypeError: messageCompiler is not a function
```
