### ISSUE TITLE
Cannot read properties of undefined (reading 'config') if use v-ripple and <script setup>

### ISSUE THREAD

**Issue by igor-popryadukhin** [quasarframework/quasar#13488]
### What happened?

Cannot read properties of undefined (reading 'config') 

If

```
<template>
  <q-list separator>
    <q-item  clickable v-ripple>
      <q-item-section>Single line item</q-item-section>
    </q-item>
  </q-list>
</template>

<script setup>
...
</script>
```

### What did you expect to happen?

I expected ripple to work properly

### Reproduction URL

https://google.com

### How to reproduce?

```
<template>
  <q-list separator>
    <q-item  clickable v-ripple>
      <q-item-section>Single line item</q-item-section>
    </q-item>
  </q-list>
</template>


<script setup>

function onAddClick() {
  console.log('Click')
}
</script>
```

![image](https://user-images.githubusercontent.com/48174353/169652823-4024bce4-5a6a-4b68-9104-4324858af467.png)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Directives (quasar), Composables (quasar), TypeScript Support, SPA Mode

### Platforms/Browsers

Chrome

### Relevant log output

```Shell
vue-router.esm-bundler.js:3308 TypeError: Cannot read properties of undefined (reading 'config')
    at updateModifiers (Ripple.js?v=543049e0:65:45)
    at beforeMount (Ripple.js?v=543049e0:112:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:2791:13)
    at mountElement (runtime-core.esm-bundler.js:5180:13)
    at processElement (runtime-core.esm-bundler.js:5110:13)
    at patch (runtime-core.esm-bundler.js:5030:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5582:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
triggerError @ vue-router.esm-bundler.js:3308
(анонимная) @ vue-router.esm-bundler.js:3344
Объект Promise.catch (асинхронный)
handleScroll @ vue-router.esm-bundler.js:3344
finalizeNavigation @ vue-router.esm-bundler.js:3198
(анонимная) @ vue-router.esm-bundler.js:3070
Объект Promise.then (асинхронный)
pushWithRedirect @ vue-router.esm-bundler.js:3041
push @ vue-router.esm-bundler.js:2969
install @ vue-router.esm-bundler.js:3386
use @ runtime-core.esm-bundler.js:4327
start @ client-entry.js:118
Объект await in start (асинхронный)
(анонимная) @ client-entry.js:149
Объект Promise.then (асинхронный)
(анонимная) @ client-entry.js:144
Объект Promise.then (асинхронный)
(анонимная) @ client-entry.js:137
Ripple.js?v=543049e0:65 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')
    at updateModifiers (Ripple.js?v=543049e0:65:45)
    at beforeMount (Ripple.js?v=543049e0:112:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:2791:13)
    at mountElement (runtime-core.esm-bundler.js:5180:13)
    at processElement (runtime-core.esm-bundler.js:5110:13)
    at patch (runtime-core.esm-bundler.js:5030:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5582:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
updateModifiers @ Ripple.js?v=543049e0:65
beforeMount @ Ripple.js?v=543049e0:112
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invokeDirectiveHook @ runtime-core.esm-bundler.js:2791
mountElement @ runtime-core.esm-bundler.js:5180
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
mountElement @ runtime-core.esm-bundler.js:5138
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
mountElement @ runtime-core.esm-bundler.js:5138
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
mountElement @ runtime-core.esm-bundler.js:5138
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
mountElement @ runtime-core.esm-bundler.js:5138
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
componentUpdateFn @ runtime-core.esm-bundler.js:5655
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:396
Объект Promise.then (асинхронный)
nextTick @ runtime-core.esm-bundler.js:246
(анонимная) @ QResizeObserver.js?v=543049e0:65
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2687
flushPostFlushCbs @ runtime-core.esm-bundler.js:358
flushJobs @ runtime-core.esm-bundler.js:403
Объект Promise.then (асинхронный)
queueFlush @ runtime-core.esm-bundler.js:285
queueCb @ runtime-core.esm-bundler.js:307
queuePostFlushCb @ runtime-core.esm-bundler.js:313
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1582
scheduler @ runtime-core.esm-bundler.js:1804
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:384
triggerRefValue @ reactivity.esm-bundler.js:1000
(анонимная) @ reactivity.esm-bundler.js:1131
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:379
triggerRefValue @ reactivity.esm-bundler.js:1000
(анонимная) @ reactivity.esm-bundler.js:1131
triggerEffect @ reactivity.esm-bundler.js:394
triggerEffects @ reactivity.esm-bundler.js:379
triggerRefValue @ reactivity.esm-bundler.js:1000
set value @ reactivity.esm-bundler.js:1044
finalizeNavigation @ vue-router.esm-bundler.js:3197
(анонимная) @ vue-router.esm-bundler.js:3070
Объект Promise.then (асинхронный)
pushWithRedirect @ vue-router.esm-bundler.js:3041
push @ vue-router.esm-bundler.js:2969
install @ vue-router.esm-bundler.js:3386
use @ runtime-core.esm-bundler.js:4327
start @ client-entry.js:118
Объект await in start (асинхронный)
(анонимная) @ client-entry.js:149
Объект Promise.then (асинхронный)
(анонимная) @ client-entry.js:144
Объект Promise.then (асинхронный)
(анонимная) @ client-entry.js:137
Показать ещё 55 фреймов
Ripple.js?v=543049e0:65 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')
    at updateModifiers (Ripple.js?v=543049e0:65:45)
    at beforeMount (Ripple.js?v=543049e0:112:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:2791:13)
    at mountElement (runtime-core.esm-bundler.js:5180:13)
    at processElement (runtime-core.esm-bundler.js:5110:13)
    at patch (runtime-core.esm-bundler.js:5030:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5582:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
```

**Comment by MilosPaunovic** [comment]
Sounds related to https://github.com/quasarframework/quasar/issues/13154

**Comment by yusufkandemir** [comment]
Closing in favor of #13154.
