### ISSUE TITLE
Quasar App Extension UI Kit V1 ~ Get Error : App · ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.

### ISSUE THREAD

**Issue by NekoSukuriputo** [quasarframework/quasar#13771]
### What happened?

After Installing Quasar App Extention using Quasar v1, install modules and run project ini folder ui, get error: This command must be executed inside a Quasar v1+ project folder.

Following Instruction in : https://v1.quasar.dev/app-extensions/development-guide/introduction
use command : `npm init quasar` 
**Quasar UI kit**
select option using **Quasar V1**

then to _ui_ run `npm i` and go to _ui/dev_ then run `npm i`

After that in **ui** folder run `npm run dev` get error:
```

> quasar-ui-approval-component-v1@0.0.1 dev C:\Users\Lawencon\Documents\00test_project\approval-component-v1\ui      
> cd dev && npm run dev && cd ..


> dev@1.0.0 dev C:\Users\Lawencon\Documents\00test_project\approval-component-v1\ui\dev
> quasar dev

 App · ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dev@1.0.0 dev: `quasar dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dev@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lawencon\AppData\Roaming\npm-cache\_logs\2022-06-24T08_39_05_792Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quasar-ui-approval-component-v1@0.0.1 dev: `cd dev && npm run dev && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quasar-ui-approval-component-v1@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lawencon\AppData\Roaming\npm-cache\_logs\2022-06-24T08_39_05_835Z-debug.log
```

### What did you expect to happen?

Not Compile Error

### Reproduction URL

https://v1.quasar.dev/app-extensions/development-guide/introduction

### How to reproduce?

 run `npm init quasar`

`# ..then select App Extension and Quasar v1 options`

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app), Plugins (quasar), App Extension API

### Platforms/Browsers

Other

### Quasar info output

```Shell
Can not get `quasar info` in `ui/dev folder,` and get output:

```
quasar info
 App · ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.
```
```

### Relevant log output

```Shell
.d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

√ What would you like to build? » Quasar UI kit
√ Project folder: ... approval-v1
√ Pick Quasar version: » Quasar v1 (Vue 2)
√ Project name (npm name, kebab-case, without "quasar-ui" prefix) ... approval
√ Author: ... Abdul Rahmat <abdulrahmat97dev@gmail.com>
√ License type ... MIT
√ Pick what you will be interested in: » Vue component, Vue directive, Quasar App Extension
√ Package description ... approval
√ UMD export name (global variable, camelCased) ... approval
√ Component name (PascalCase) ... Approval
√ Directive name (kebab-case, without "v-" prefix) ... approval
√ App Extension description ... A Quasar App Extension
√ Pick the needed App Extension scripts: » Prompts script, Install script
√ Repository type: ... git
√ Repository URL: (eg https://github.com/quasarframework/quasar) ...
√ Homepage URL: ...
√ Issue reporting URL: (eg https://github.com/quasarframework/quasar/issues) ...

 Quasar • Generating files...

 - LICENSE
 - README.md
 - .gitignore
 - jsconfig.json
 - ui/README.md
 - ui/umd-test.html
 - ui/.npmignore
 - ui/package.json
 - ui/build/config.js
 - ui/build/index.js
 - ui/build/script.app-ext.js
 - ui/build/script.clean.js
 - ui/build/script.css.js
 - ui/build/script.javascript.js
 - ui/build/script.open-umd.js
 - ui/build/utils.js
 - ui/dev/babel.config.js
 - ui/dev/quasar.config.js
 - ui/dev/README.md
 - ui/dev/.editorconfig
 - ui/dev/.gitignore
 - ui/dev/.postcssrc.js
 - ui/dev/package.json
 - ui/src/index.js
 - ui/src/index.sass
 - ui/build/entry/index.common.js
 - ui/build/entry/index.esm.js
 - ui/build/entry/index.umd.js
 - ui/dev/src/App.vue
 - ui/dev/src/index.template.html
 - ui/src/mixins/.gitkeep
 - ui/dev/src/assets/.gitkeep
 - ui/dev/src/boot/register.js
 - ui/dev/src/components/.gitkeep
 - ui/dev/src/css/app.sass
 - ui/dev/src/css/quasar.variables.sass
 - ui/dev/src/layouts/MyLayout.vue
 - ui/dev/src/pages/Index.vue
 - ui/dev/src/pages/Test1.vue
 - ui/dev/src/router/index.js
 - ui/dev/src/router/pages.js
 - ui/dev/src/router/routes.js
 - app-extension/README.md
 - app-extension/.npmignore
 - app-extension/package.json
 - app-extension/src/index.js
 - app-extension/src/boot/register.js
 - app-extension/src/templates/.gitkeep
 - app-extension/src/install.js
 - app-extension/src/prompts.js
 - ui/src/components/Component.js
 - ui/src/components/Component.sass
 - ui/src/directives/Directive.js
 - ui/src/directives/Directive.sass
 - ui/build/script.app-ext.js

 Quasar •  SUCCESS  • The project has been scaffolded


To get started:

  cd approval-v1

Documentation can be found at: https://v1.quasar.dev

Quasar is relying on donations to evolve. We'd be very grateful if you can
read our manifest on "Why donations are important": https://v1.quasar.dev/why-donate
Donation campaign: https://donate.quasar.dev
Any amount is very welcomed.
If invoices are required, please first contact Razvan Stoenescu.

Please give us a star on Github if you appreciate our work:
  https://github.com/quasarframework/quasar

Enjoy! - Quasar Team
```

### Additional context

File log npm from comman `npm run dev`

```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle quasar-ui-approval-component-v1@0.0.1~predev: quasar-ui-approval-component-v1@0.0.1
6 info lifecycle quasar-ui-approval-component-v1@0.0.1~dev: quasar-ui-approval-component-v1@0.0.1
7 verbose lifecycle quasar-ui-approval-component-v1@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle quasar-ui-approval-component-v1@0.0.1~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Lawencon\Documents\00test_project\approval-component-v1\ui\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\protoc\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Go\bin;C:\ProgramData\chocolatey\bin;%ERLANG_HOME%\bin;C:\protoc\go-proto-validators-master;C:\oc;C:\Users\Lawencon\AppData\Local\Microsoft\WindowsApps;C:\Users\Lawencon\AppData\Local\Yarn\bin;C:\Users\Lawencon\AppData\Roaming\npm;C:\Users\Lawencon\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Lawencon\go\bin;C:\oc;
9 verbose lifecycle quasar-ui-approval-component-v1@0.0.1~dev: CWD: C:\Users\Lawencon\Documents\00test_project\approval-component-v1\ui
10 silly lifecycle quasar-ui-approval-component-v1@0.0.1~dev: Args: [ '/d /s /c', 'cd dev && npm run dev && cd ..' ]
11 silly lifecycle quasar-ui-approval-component-v1@0.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle quasar-ui-approval-component-v1@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: quasar-ui-approval-component-v1@0.0.1 dev: `cd dev && npm run dev && cd ..`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid quasar-ui-approval-component-v1@0.0.1
15 verbose cwd C:\Users\Lawencon\Documents\00test_project\approval-component-v1\ui
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error quasar-ui-approval-component-v1@0.0.1 dev: `cd dev && npm run dev && cd ..`
22 error Exit status 1
23 error Failed at the quasar-ui-approval-component-v1@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by yusufkandemir** [comment]
https://v1.quasar.dev/app-extensions/development-guide/introduction#getting-started
> When using the UI kit, you will have two npm packages; one for the App Extension and one for the UI module. **For testing with the dev app, from the ui folder type `yarn dev`**. Create pages in the dev folder for testing and they will automatically be injected into the test app. Also, check out the scripts section in the package.json to see what you have available. When you yarn build, a dist folder will be created and populated with various types of packages (common, esm, and umd).

You shouldn't cd into `ui/dev` folder and run `quasar dev`, you should run `yarn dev`/`npm run dev` in the `ui` folder instead.

**Comment by NekoSukuriputo** [comment]
> https://v1.quasar.dev/app-extensions/development-guide/introduction#getting-started
> 
> > When using the UI kit, you will have two npm packages; one for the App Extension and one for the UI module. **For testing with the dev app, from the ui folder type `yarn dev`**. Create pages in the dev folder for testing and they will automatically be injected into the test app. Also, check out the scripts section in the package.json to see what you have available. When you yarn build, a dist folder will be created and populated with various types of packages (common, esm, and umd).
> 
> You shouldn't cd into `ui/dev` folder and run `quasar dev`, you should run `yarn dev`/`npm run dev` in the `ui` folder instead.

That still not working,  I think is same  if you check in package.json in ui folder ` yarn dev` or `npm run dev`  is `cd dev && yarn dev && cd ..`  command

This picture if I'm run in ui folder : 
![gambar](https://user-images.githubusercontent.com/51826615/175807002-66c813a5-1641-4ffc-aca7-ec9894465388.png)

Of course node_modules is alrady installed: 
![gambar](https://user-images.githubusercontent.com/51826615/175807083-3ab5b425-a6b9-40c0-b92e-1870841d35dd.png)

**Comment by yusufkandemir** [comment]
Use `yarn`, or replace `yarn` references in `scripts` sections with `npm run`. Also, please share the output of `npm config get global`.

**Comment by NekoSukuriputo** [comment]
> Use `yarn`, or replace `yarn` references in `scripts` sections with `npm run`. Also, please share the output of `npm config get global`.


This I'm replace `yarn`  to `npm run` and I'm run the command:
![gambar](https://user-images.githubusercontent.com/51826615/175807252-93f16052-a76a-47ce-8b90-12cbddb3430b.png)

![gambar](https://user-images.githubusercontent.com/51826615/175807292-6c271205-ead9-43e7-8ffa-5f43744e082d.png)

`npm config get global` : 
![gambar](https://user-images.githubusercontent.com/51826615/175807329-751bc7ef-e477-46ea-84b4-4f6c17f2c475.png)

**Comment by yusufkandemir** [comment]
Please rename `dev/quasar.config.js` to `dev/quasar.conf.js` then try again.

**Comment by NekoSukuriputo** [comment]
> Please rename `dev/quasar.config.js` to `dev/quasar.conf.js` then try again.

This working, thank you for helping me.

![gambar](https://user-images.githubusercontent.com/51826615/175807678-b36977d0-c28a-43dc-963b-d4320ad7798a.png)

**Comment by yusufkandemir** [comment]
Thanks for your collaboration. I made a fix into the UI-kit template for Quasar v1, so new projects won't have this problem after it gets released.
