### ISSUE TITLE
Getting `zlib: incorrect data check` when trying to run `npm i --save-dev @quasar/extras@1.14.1 `

### ISSUE THREAD

**Issue by jrgleason** [quasarframework/quasar#13852]
### What happened?

I am running node `v16.15.1` when I run `npm i --save-dev @quasar/extras` to try to install the lib I get...

```
npm WARN tar zlib: incorrect data check
npm WARN tarball cached data for @quasar/extras@https://registry.npmjs.org/@quasar/extras/-/extras-1.14.2.tgz (sha512-F9T1aIhRIiuJeuxPCu2CBlPj5js6mBZWQOAHHyVlreNa5qhVEHhr/9GfljG6RTnjvTNOjJraTl0hi8g0IuUfLw==) seems to be corrupted. Refreshing cache.
npm WARN tarball tarball data for @quasar/extras@https://registry.npmjs.org/@quasar/extras/-/extras-1.14.2.tgz (sha512-F9T1aIhRIiuJeuxPCu2CBlPj5js6mBZWQOAHHyVlreNa5qhVEHhr/9GfljG6RTnjvTNOjJraTl0hi8g0IuUfLw==) seems to be corrupted. Trying again.
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for @quasar/extras@https://registry.npmjs.org/@quasar/extras/-/extras-1.14.2.tgz (sha512-F9T1aIhRIiuJeuxPCu2CBlPj5js6mBZWQOAHHyVlreNa5qhVEHhr/9GfljG6RTnjvTNOjJraTl0hi8g0IuUfLw==) seems to be corrupted. Trying again.
npm ERR! code Z_DATA_ERROR
npm ERR! errno -3
npm ERR! zlib: incorrect data check

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2022-07-03T02_34_03_490Z-debug-0.log
```

All of the other dependencies install fine.

### What did you expect to happen?

I would expect to be able to install the extras

### Reproduction URL

https://github.com/quasarframework/quasar

### How to reproduce?

1. install node v16.15.1
2. run `npm i --save-dev @quasar/extras`

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Firefox

### Relevant log output

```
126 timing reify:rollback:createSparse Completed in 50ms
127 timing reify:rollback:retireShallow Completed in 0ms
128 timing command:i Completed in 11236ms
129 verbose stack ZlibError: zlib: incorrect data check
129 verbose stack     at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:154:22)
129 verbose stack     at Unpack.write (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:19)
129 verbose stack     at Yallist.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:389:18)
129 verbose stack     at Yallist.forEach (/usr/local/lib/node_modules/npm/node_modules/yallist/yallist.js:156:8)
129 verbose stack     at IntegrityStream.emit (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:388:20)
129 verbose stack     at IntegrityStream.emit (/usr/local/lib/node_modules/npm/node_modules/ssri/lib/index.js:90:18)
129 verbose stack     at IntegrityStream.write (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:172:16)
129 verbose stack     at IntegrityStream.write (/usr/local/lib/node_modules/npm/node_modules/ssri/lib/index.js:96:18)
129 verbose stack     at Yallist.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:389:18)
129 verbose stack     at Yallist.forEach (/usr/local/lib/node_modules/npm/node_modules/yallist/yallist.js:156:8)
130 verbose cwd /Users/.../Code/personal/ecommerce-mono/ui
131 verbose Darwin 21.5.0
132 verbose node v16.15.1
133 verbose npm  v8.11.0
134 error code Z_DATA_ERROR
135 error errno -3
136 error zlib: incorrect data check
137 verbose exit -3
138 timing npm Completed in 11364ms
139 verbose unfinished npm timer reify 1656815643617
140 verbose unfinished npm timer reify:unpack 1656815643793
141 verbose unfinished npm timer reifyNode:node_modules/@quasar/extras 1656815643793
142 verbose code -3
143 error A complete log of this run can be found in:
143 error     /Users/.../.npm/_logs/2022-07-03T02_34_03_490Z-debug-0.log
```

**Comment by pdanpdan** [comment]
you should clear npm cache / remove node_modules / remove lock file
and try again

**Comment by rstoenescu** [comment]
This is an npm server error. Should be fixed by now.
