### ISSUE TITLE
Version >2.9.0 <q-route-tab> breaks jest-unit testing

### ISSUE THREAD

**Issue by mobsean** [quasarframework/quasar#14549]
### What happened?

I updated from Quasar 2.7.5 to 2.9.1 so see my jest unit tests failing after the update.

### What did you expect to happen?

unit tests should work as before. 

### Reproduction URL

https://github.com/mobsean/quasar-2.9.1-test-jest-fails

### How to reproduce?

1. npm init quasar
2. quasar ext add @quasar/testing-unit-jest@alpha
3. npm run test:unit - see that its working
4. from __tests__ examples: add this to MyButton.vue 
```
    <q-tabs>
      <q-route-tab name="Test" to="/test" />
    </q-tabs>
```
5. npm run test:unit
6. watch tests fail
7. npm install quasar@2.8.4
8. npm run test:unit
9. watch tests pass

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19044) - win32/x64
NodeJs - 16.10.0

Global packages
  NPM - 7.24.0
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.9.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.40 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.22 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool  eslint - 8.24.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 2.0.4 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-unit-jest - 3.0.0-alpha.10 -- A Quasar App Extension for running Jest tests

Networking
  Host - nope
  LAN-Verbindung - *.*.*.*
  Ethernet - *.*.*.*
```

### Relevant log output

```Shell
FAIL  test/jest/__tests__/MyButton.spec.ts (6.443 s)   
  ● Console

    console.warn
      [Vue warn]: Unhandled error during execution of watcher getter 
        at <QRouteTab name="Test" to="/test" > 
        at <QTabs> 
        at <MyButton ref="VTU_COMPONENT" > 
        at <VTUROOT>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
      at logError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:214:9)
      at handleError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:206:5)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:160:9)
      at ReactiveEffect.getter [as fn] (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1706:28)        
      at ReactiveEffect.run (node_modules/@vue/reactivity/dist/reactivity.cjs.js:189:25)
      at doWatch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1812:31)
      at watch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1656:12)
```

### Additional context

Downgrade to Quasar 2.8.4 makes the tests pass again.

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.9.2
