### ISSUE TITLE
Qtree update Error , Quasar Framework v1.15.2

### ISSUE THREAD

**Issue by AdorableGhost** [quasarframework/quasar#14823]
### What happened?

When I used Quasar Framework v1.15.2 ,I will self define the filter action ,so ,I  binded a q-input to the self-defined function , every time when user input charactors to  the input ,I will fetch data from the server and re-render the q-tree.
but when I reset the q-tree nodes model to new data , caught error  
```
TypeError: (intermediate value)(intermediate value)(intermediate value).map is not a function
    at a.__getChildren (quasar.umd.min.js:6:480269)
    at a.render (quasar.umd.min.js:6:483685)
    at e._render (vue.min.js:6:35481)
    at a.r (vue.min.js:6:68170)
    at fn.get (vue.min.js:6:26768)
    at fn.run (vue.min.js:6:27652)
    at un (vue.min.js:6:25760)
    at Array.<anonymous> (vue.min.js:6:12466)
    at qe (vue.min.js:6:11867)
```

the functoion fetch data like
```
            filterUnit() {
                //filter 是 筛选关键词  Filter is the keys word to search 
                if (this.filter == undefined || !this.filter || this.filter.length < 1 || this.filter.trim().length < 1) {
                    return;
                }
                axios({
                    method: 'post',
                    url: 'quasar_search',
                    data: {
                        "name": this.filter,
                    },
                    {{--headers: {--}}
                    {{--    "X-CSRF-TOKEN": "{{csrf_token()}}",--}}
                    {{--    "Content-Type": 'application/json;charset=utf-8',--}}
                    {{--},--}}
                }).then((response) => {

                    if (response.data.code == 200) {
                        let resp_data = JSON.parse(JSON.stringify(response.data.data));
                        console.log("resp_data");
                        console.log(resp_data);
                        if (this.opened) {
                            console.log("children before");
                            resp_data.handler = (resp_data) => {
                                window.ell.unit_click(resp_data);
                            };
                            resp_data.children.forEach((el) => {
                                el.handler = (el) => {
                                    window.ell.unit_click(el);
                                };
                            });
                            console.log("children after");

                            this.unit_tree = [];
                            this.unit_tree = JSON.parse(JSON.stringify(resp_data));
                            console.log("after unit_tree")
                        }

                        if (this.officer_opened) {
                            resp_data.handler = (el) => {
                                window.ell.select_officer(el);
                            };
                            resp_data.children.forEach((el) => {
                                el.handler = (el) => {
                                    window.ell.select_officer(el);
                                };
                            });


                            this.officer_unit_tree = resp_data;
                        }
                        console.log("final")
                  
                    } else {
//  response have invalid code 
                        this.message = response.data.message;
                        this.notify();

                    }
                    console.log("final")
                }).catch((error) => {
                    if (error.response) {

                        this.message = "服务器发生了错误！" + error.response.data; // Server ERR
                        this.notify();

                    } else if (error.request) {
                        this.message = "服务器发生了错误！" + error.request; // Server ERR
                        this.notify();
                    } else {
                        // Something happened in setting up the request that triggered an Error
                        console.log('Error', error.message);
                        this.message = "服务器发生了错误！" + error.message; // Server ERR
                        this.notify();
                    }
                    console.log(error.config);
                });

            }
```
I know it's error while quasar rendering the tree ,but I thought there's no  error in my code .why it get a wired error.

### What did you expect to happen?

rendering the tree right with my data 

### Reproduction URL

private object .cant put on internet

### How to reproduce?

1. define a tree
2. make a  input button  use as a filter 
3. everytime user input things , reset the tree nodes model to the data fetched from the server
4. Error occured

### Flavour

UMD

### Areas

PWA Mode

### Platforms/Browsers

Chrome

### Relevant log output

```Shell
TypeError: (intermediate value)(intermediate value)(intermediate value).map is not a function
    at a.__getChildren (quasar.umd.min.js:6:480269)
    at a.render (quasar.umd.min.js:6:483685)
    at e._render (vue.min.js:6:35481)
    at a.r (vue.min.js:6:68170)
    at fn.get (vue.min.js:6:26768)
    at fn.run (vue.min.js:6:27652)
    at un (vue.min.js:6:25760)
    at Array.<anonymous> (vue.min.js:6:12466)
    at qe (vue.min.js:6:11867)
```

**Comment by pdanpdan** [comment]
Please make a codepen with reproduction
Update your quasar version
https://v1.quasar.dev/vue-components/tree#custom-filter-method
