### ISSUE TITLE
"update-electron-app" can't find packages.json with Quasar

### ISSUE THREAD

**Issue by rehoehle** [quasarframework/quasar#15407]
### What happened?

When the application start in Dev-Mode the application folder starts an ".quasar/electron". Here the package.json cannot be found. It give me the following error:

```
Error: ENOENT: no such file or directory, open '/Users/xxx/Sites/projects/xxx/xxx-fogos-updater/.quasar/electron/package.json'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at validateInput (/Users/xxx/Sites/projects/xxx/xxx-fogos-updater/node_modules/update-electron-app/index.js:110:23)
    at updater (/Users/xxx/Sites/projects/xxx/xxx-fogos-updater/node_modules/update-electron-app/index.js:22:10)
    at Object.<anonymous> (/Users/xxx/Sites/projects/xxx/xxx-fogos-updater/.quasar/electron/electron-main.js:27:40)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
```

The line can't find the file because it starts from the subdirectory. 

`const pkgBuf = fs.readFileSync(path.join(electron.app.getAppPath(), 'package.json'))`

### What did you expect to happen?

The dev-mode should find the file and update check if there are some updates. Is there a fix to get the packages file in that location automatically? Or is there another tool to use for updates?

### Reproduction URL

https://test.de/

### How to reproduce?

1.) install "update-electron-app". 

https://www.electronjs.org/de/docs/latest/tutorial/updates

2.) Start the dev mode with `quasar dev -m electron`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Electron Mode

### Platforms/Browsers

Electron

### Quasar info output

```Shell
Operating System - Darwin(22.3.0) - darwin/arm64
NodeJs - 18.12.1

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.0 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.10 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.33.0 -- An AST-based pattern checker for JavaScript.
  electron - 22.1.0 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.5.2 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 23.6.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - xxx.local
  en0 - 10.0.1.150
```

**Comment by pdanpdan** [comment]
https://github.com/electron/update.electronjs.org#manual-setup

Check the important part :)

**Comment by rehoehle** [comment]
@pdanpdan thanks for your reply. I have seen this but i couldn't start the app. But i have changed it to another solution with electron-builder.
