### ISSUE TITLE
Could not resolve "@quasar/extras/mdi-v7"

### ISSUE THREAD

**Issue by herodotus-ecosystem** [quasarframework/quasar#15627]
### What happened?

after update @quasar/extras 1.16.0 will got 'Could not resolve "@quasar/extras/mdi-v7"' error.

my environment:

- Vue 3.2.47
- Vite 4.2.1
- Quasar 2.11.9

### What did you expect to happen?

when start project , will got error

```
VITE v4.2.1  ready in 3118 ms

  ➜  Local:   http://localhost:3000/                                                                                                                                                                  09:39:43  
  ➜  Network: http://192.168.101.10:3000/                                                                                                                                                             09:39:43  
  ➜  Network: http://172.21.112.1:3000/                                                                                                                                                               09:39:43  
  ➜  press h to show help                                                                                                                                                                             09:39:43  
X [ERROR] Could not resolve "@quasar/extras/mdi-v7"

    ../../node_modules/.pnpm/registry.npmmirror.com+quasar@2.11.9/node_modules/quasar/icon-set/svg-mdi-v7.mjs:82:7:
      82 │ } from '@quasar/extras/mdi-v7'
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./mdi-v7" is forbidden by this package:

    ../../node_modules/@quasar/extras/package.json:116:11:
      116 │     "./*": "./*"
          ╵            ~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    ../../node_modules/@quasar/extras/package.json:9:2:
      9 │   "exports": {
        ╵   ~~~~~~~~~

  Import from "@quasar/extras/mdi-v7/index.js" to get the file
  "../../node_modules/@quasar/extras/mdi-v7/index.js":

    ../../node_modules/.pnpm/registry.npmmirror.com+quasar@2.11.9/node_modules/quasar/icon-set/svg-mdi-v7.mjs:82:29:
      82 │ } from '@quasar/extras/mdi-v7'
         │                              ^
         ╵                              /index.js

  You can mark the path "@quasar/extras/mdi-v7" as external to exclude it from the bundle, which
  will remove this error.

D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../node_modules/.pnpm/registry.npmmirror.com+quasar@2.11.9/node_modules/quasar/icon-set/svg-mdi-v7.mjs:82:7: ERROR: Could not resolve "@quasar/extras/mdi-v7"
    at failureErrorWithLog (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1636:15)
    at D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1046:7)
    at D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:1057:54)
    at handleRequest (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:723:19)
    at handleIncomingPacket (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:745:7)
    at Socket.readFromStdout (D:\Workspaces\Next\herodotus-cloud-ui\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.17.14\node_modules\esbuild\lib\main.js:673:7) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: '../../node_modules/.pnpm/registry.npmmirror.com+quasar@2.11.9/node_modules/quasar/icon-set/svg-mdi-v7.mjs',
        length: 23,
        line: 82,
        lineText: "} from '@quasar/extras/mdi-v7'",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 11,
            file: '../../node_modules/@quasar/extras/package.json',
            length: 5,
            line: 116,
            lineText: '    "./*": "./*"',
            namespace: '',
            suggestion: ''
          },
          text: 'Importing the directory "./mdi-v7" is forbidden by this package:'
        },
        {
          location: {
            column: 2,
            file: '../../node_modules/@quasar/extras/package.json',
            length: 9,
            line: 9,
            lineText: '  "exports": {',
            namespace: '',
            suggestion: ''
          },
          text: 'The presence of "exports" here makes importing a directory forbidden:'
        },
        {
          location: {
            column: 29,
            file: '../../node_modules/.pnpm/registry.npmmirror.com+quasar@2.11.9/node_modules/quasar/icon-set/svg-mdi-v7.mjs',
            length: 0,
            line: 82,
            lineText: "} from '@quasar/extras/mdi-v7'",
            namespace: '',
            suggestion: '/index.js'
          },
          text: 'Import from "@quasar/extras/mdi-v7/index.js" to get the file "../../node_modules/@quasar/extras/mdi-v7/index.js":'
        },
        {
          location: null,
          text: 'You can mark the path "@quasar/extras/mdi-v7" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@quasar/extras/mdi-v7"'
    }
  ],
  warnings: []
}
```

### Reproduction URL

https://quasar.dev

### How to reproduce?

use mdi-v7 with quasar 

quasar config:

```
import type { App } from 'vue';
import { Quasar, Loading, AppFullscreen } from 'quasar';
import quasarLang from 'quasar/lang/zh-CN';
import quasarIconSet from 'quasar/icon-set/svg-mdi-v7';

// Import icon libraries
import '@quasar/extras/material-icons/material-icons.css';
import '@quasar/extras/mdi-v7/mdi-v7.css';
// Import Quasar css
import 'quasar/dist/quasar.css';
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar Extras (@quasar/extras)

### Platforms/Browsers

Chrome

### Additional context

I found @quasar/extras package.json not export mdi-v7 module

```
    },
    "./mdi-v3": {
      "types": "./mdi-v3/index.d.ts",
      "import": "./mdi-v3/index.mjs",
      "require": "./mdi-v3/index.js"
    },
    "./mdi-v4": {
      "types": "./mdi-v4/index.d.ts",
      "import": "./mdi-v4/index.mjs",
      "require": "./mdi-v4/index.js"
    },
    "./mdi-v5": {
      "types": "./mdi-v5/index.d.ts",
      "import": "./mdi-v5/index.mjs",
      "require": "./mdi-v5/index.js"
    },
    "./mdi-v6": {
      "types": "./mdi-v6/index.d.ts",
      "import": "./mdi-v6/index.mjs",
      "require": "./mdi-v6/index.js"
    },
    "./themify": {
      "types": "./themify/index.d.ts",
      "import": "./themify/index.mjs",
      "require": "./themify/index.js"
    },
    "./*": "./*"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/quasarframework/quasar.git"
  },
```

**Comment by rstoenescu** [comment]
Thanks for reporting. Fix will be available in next q/extras release
