### ISSUE TITLE
TypeError: Cannot destructure property 'generalAnimations' of 'getPackage(...)' as it is undefined.

### ISSUE THREAD

**Issue by stillnurs** [quasarframework/quasar#15623]
### What happened?

After updating to v2.11.9 running command 'quasar dev' with quasar.config.js settings property 'animations: "all" ' (while working with prior to latest update), cannot run a project or build. 

Getting this error. 

`TypeError: Cannot destructure property 'generalAnimations' of 'getPackage(...)' as it is undefined.
    at Object.<anonymous> 
    
    Without animations: 'all' or setting the value to one of animations e.g., 'bounceInLeft' does not reproduce this error.

### What did you expect to happen?

To run or build with settings property set to 'animations: "all"' 

### Reproduction URL

https://stackblitz.com/edit/quasarframework-jjrcl3

### How to reproduce?

update to v2.11.9

run command 'npm run dev' (quasar dev)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
TypeError: Cannot destructure property 'generalAnimations' of 'getPackage(...)' as it is undefined.
    at Object.eval (file:///home/projects/quasarframework-fujgj2/node_modules/@quasar/app-vite/lib/helpers/animations.js:4:3)
    at Object.function (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:144744)
    at Module._compile (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244076)
    at Module._extensions..js (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:244741)
    at Module.load (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:242766)
    at Module._load (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:240331)
    at Module.require (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:243084)
    at i (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:6:480348)
    at _0x2f264e (https://quasarframeworkfujgj2-vzjz.w-corp.staticblitz.com/blitz.88d3a49b591611919d7d64c44b90ff5f8e939906.js:15:144020)
    at QuasarConfFile.read (file:///home/projects/quasarframework-fujgj2/node_modules/@quasar/app-vite/lib/quasar-config-file.js:281:34)
```

**Comment by d4ism3l** [comment]
I have the same problem...!

**Comment by mathiasayivor** [comment]
I also have the same problem!

**Comment by yjzzjy4** [comment]
Same here! I just upgrade my quasar-cli to the latest version in order to get over with the issue using v-ripple deirective inside the q-dialog, problem fixed but then I got this...

**Comment by jeimz143** [comment]
i have the same issue. whenever you set the ```{animations: "all"} ``` in ```quasar.conf.js```,  it triggers the issue... so for now i set it as ```{animations: []}```..  i triggered also for fresh install.

**Comment by rstoenescu** [comment]
Thanks for reporting.
Fix will be available on next q/extras release.
