### ISSUE TITLE
Failed to create new Quasar project with ESLint

### ISSUE THREAD

**Issue by DerZade** [quasarframework/quasar#15792]
### What happened?

Creating a new quasar project with ESLint doesn't work. 
The follwoing error occurs:
```
> eslint --ext .js,.vue ./ --fix


Oops! Something went wrong! :(

ESLint: 8.39.0

/home/jonas/projects/and/quasar-project/.eslintrc.cjs:30
    <% if (lintConfig === 'standard') { %>'standard'
    ^

SyntaxError: Unexpected token '<'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at module.exports [as default] (/home/jonas/projects/and/quasar-project/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/home/jonas/projects/and/quasar-project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2562:47)
    at loadConfigFile (/home/jonas/projects/and/quasar-project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2646:20)

 npm FAILED...

 Quasar • ⚠️  Could not auto lint fix the project folder.
```

Also the eslint config seems borked:
<details>
<summary>Expand to see eslintrc.cjs</summary>

```cjs
// .eslintrc.cjs
module.exports = {
  // https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
  // This option interrupts the configuration hierarchy at this file
  // Remove this if you have an higher level ESLint config file (it usually happens into a monorepos)
  root: true,

  parserOptions: {
    parser: '@babel/eslint-parser',
    ecmaVersion: 2018, // Allows for the parsing of modern ECMAScript features
    sourceType: 'module' // Allows for the use of imports
  },

  env: {
    browser: true,
    'vue/setup-compiler-macros': true
  },

  // Rules order is important, please avoid shuffling them
  extends: [
    // Base ESLint recommended rules
    // 'eslint:recommended',

    // Uncomment any of the lines below to choose desired strictness,
    // but leave only one uncommented!
    // See https://eslint.vuejs.org/rules/#available-rules
    'plugin:vue/vue3-essential', // Priority A: Essential (Error Prevention)
    // 'plugin:vue/vue3-strongly-recommended', // Priority B: Strongly Recommended (Improving Readability)
    // 'plugin:vue/vue3-recommended', // Priority C: Recommended (Minimizing Arbitrary Choices and Cognitive Overhead)

    <% if (lintConfig === 'standard') { %>'standard'
    <% } else if (lintConfig === 'airbnb') { %>'airbnb-base'
    <% } else if (lintConfig === 'prettier') { %>// https://github.com/prettier/eslint-config-prettier#installation
    // usage with Prettier, provided by 'eslint-config-prettier'.
    'prettier'<% } %>
  ],

  plugins: [
    // https://eslint.vuejs.org/user-guide/#why-doesn-t-it-work-on-vue-files
    // required to lint *.vue files
    'vue',
    <% if (lintConfig === 'prettier') { %>
    // https://github.com/typescript-eslint/typescript-eslint/issues/389#issuecomment-509292674
    // Prettier has not been included as plugin to avoid performance impact
    // add it as an extension for your IDE
    <% } %>
  ],

  globals: {
    ga: 'readonly', // Google Analytics
    cordova: 'readonly',
    __statics: 'readonly',
    __QUASAR_SSR__: 'readonly',
    __QUASAR_SSR_SERVER__: 'readonly',
    __QUASAR_SSR_CLIENT__: 'readonly',
    __QUASAR_SSR_PWA__: 'readonly',
    process: 'readonly',
    Capacitor: 'readonly',
    chrome: 'readonly'
  },

  // add your custom rules here
  rules: {
    <% if (lintConfig === 'standard') { %>
    // allow async-await
    'generator-star-spacing': 'off',
    // allow paren-less arrow functions
    'arrow-parens': 'off',
    'one-var': 'off',
    'no-void': 'off',
    'multiline-ternary': 'off',

    'import/first': 'off',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    <% } else if (lintConfig === 'airbnb') { %>
    'no-param-reassign': 'off',
    'no-void': 'off',
    'no-nested-ternary': 'off',
    'max-classes-per-file': 'off',

    'import/first': 'off',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/prefer-default-export': 'off',
    <% } %>
    'prefer-promise-reject-errors': 'off',

    // allow debugger during development only
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}
```

</details>

### What did you expect to happen?

It not to error 

### Reproduction URL
Tell me how to provide a reproduction URL for creating a quasar project, and I will :D

### How to reproduce?

1. Run `npm init quasar` or `yarn create quasar` 
2. Select the following options
    ```
    ✔ What would you like to build? › App with Quasar CLI, let's go!
    ✔ Project folder: … quasar-project
    ✔ Target directory "quasar-project" is not empty. Remove existing files and continue? … yes
    ✔ Pick Quasar version: › Quasar v2 (Vue 3 | latest and greatest)
    ✔ Pick script type: › Javascript
    ✔ Pick Quasar App CLI variant: › Quasar App CLI with Webpack
    ✔ Package name: … quasar-project
    ✔ Project product name: (must start with letter if building mobile apps) … Quasar App
    ✔ Project description: … A Quasar Project
    ✔ Author: …
    ✔ Pick your CSS preprocessor: › Sass with SCSS syntax
    ✔ Check the features needed for your project: › ESLint
    ✔ Pick an ESLint preset: › Prettier
    ```

Script Type, CLI variant, css preprocessor and ESLint preset do not matter.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Project Creation (create-quasar)

### Additional context
`npm init quasar@1.1.2` works fine.

**Comment by rstoenescu** [comment]
Fixed. Thanks for reporting!
