### ISSUE TITLE
Error in composables/private/use-field.js during server-side-render

### ISSUE THREAD

**Issue by jcalfee** [quasarframework/quasar#15934]
### What happened?

Tried to the example here on my localhost using server-side rendering:
https://vee-validate.logaretm.com/v4/examples/ui-libraries#quasar

And I'm getting this warning `[Vue warn]: inject() can only be used inside setup() or functional components.` and error on the server (below).  It appears that composables/private/use-field.js may not be running during the setup phase (on the client) and instead is trying to run during the render phase..  If I turn off SSR, all works fine..
```
Cannot read properties of undefined (reading 'dark')

at ReactiveEffect.run (./node_modules/.pnpm/@vue+reactivity@3.3.4/node_modules/@vue/reactivity/dist/reactivity.cjs.js:162:19)
at ComputedRefImpl.get value [as value] (./node_modules/.pnpm/@vue+reactivity@3.3.4/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1143:33)
at ReactiveEffect.fn (/home/james/dev/inpower/inpower/node_modules/.pnpm/quasar@2.12.0/node_modules/quasar/src/composables/private/use-field.js:219:21)
at ReactiveEffect.run (./node_modules/.pnpm/@vue+reactivity@3.3.4/node_modules/@vue/reactivity/dist/reactivity.cjs.js:162:19)
at ComputedRefImpl.get value [as value] (./node_modules/.pnpm/@vue+reactivity@3.3.4/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1143:33)
at Proxy.renderField (/home/james/dev/inpower/inpower/node_modules/.pnpm/quasar@2.12.0/node_modules/quasar/src/composables/private/use-field.js:589:17)
at renderComponentRoot (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:812:16)
at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:700:28)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)
```

### What did you expect to happen?

To work while SSR is enabled.

### Reproduction URL

https://vee-validate.logaretm.com/v4/examples/ui-libraries#quasar

### How to reproduce?

I doubt the code tools above provide SSR..

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
I do not see a CLI in this version of quasar..

$ ls ./node_modules/.bin/quasar
ls: cannot access './node_modules/.bin/quasar': No such file or directory

$ egrep quasar package.json 
    "@quasar/extras": "^1.16.4",
    "quasar": "^2.12.0",
    "nuxt-quasar-ui": "^1.7.4",
```

### Relevant log output

```Shell
With SSR enabled, making a request to route / which imports in `<script setup>...</script>` a component with all of the app.vue code from this example:

https://vee-validate.logaretm.com/v4/examples/ui-libraries#quasar

[web] New request: http://code.local:3000/
[web] ✔ Vite server hmr 36 files in 1846.938ms
[web] [Vue warn]: inject() can only be used inside setup() or functional components.
[web] [Vue warn]: resolveComponent can only be used in render() or setup().
[web] [Vue warn]: resolveComponent can only be used in render() or setup().
[web] [Vue warn]: Component QSelect is missing template or render function.
[web] [Vue warn]: Component QSelect is missing template or render function.
[web] [Vue warn]: resolveComponent can only be used in render() or setup().
[web] New request: http://code.local:3000/__nuxt_error?url=/&statusCode=500&statusMessage&message=Cannot+read+properties+of+undefined+ .... (stack trace from above)
```

**Comment by rstoenescu** [comment]
Closing for lack of a reproduction after 2+ years. Comment with one and we'll reopen.
