### ISSUE TITLE
[capacitor/yarn] Duplicate workspace

### ISSUE THREAD

**Issue by razorness** [quasarframework/quasar#16110]
### What happened?

Syncronization of `./package.json` and `./src-capacitor/package.json` conflicts with workspace feature in Yarn `v3`.

- Created new project with quasar cli (vite/typescript)
- switched to yarn `v3.6.1`: `yarn set version stable`
- added capacitor mode: `yarn quasar mode add capacitor` and 
  - ran into workspace error by running `yarn install` in `./src-capacitor`
    - however, this can be fixed by defining workspace in `package.json` of root project

```json
  // ./package.json
  "workspaces": [
    ".",
    "src-capacitor"
  ],
```

  - rerun `yarn quasar mode add capacitor`
- and now, we have a vanilla project via quasar cli with SPA and capacitor modes
- try to exec any yarn command. all you get is:
```bash
Internal Error: Duplicate workspace name quasar-project: /opt/test/quasar-project/src-capacitor conflicts with /opt/test/quasar-project
    at je.addWorkspace (/home/user/.cache/node/corepack/yarn/3.6.1/yarn.js:439:1949)
    at /home/user/.cache/node/corepack/yarn/3.6.1/yarn.js:439:1658
```
  - change package name in `./src-capacitor/package.json`
  - run dev server `yarn quasar dev -m capacitor -T android`
    -  this command will sync package name of `./package.json` with `./src-capacitor/package.json` and you get the yarn error back again.

### What did you expect to happen?

`yarn quasar dev -m capacitor -T android` to not overwrite my given project name in `./src-capacitor/package.json`

### Reproduction URL

https://github.com/razorness/quasar-yarn-capacitor-workspaces-issue

### How to reproduce?

- Exec `yarn` from project root. Error.
- Change package name in `./src-capacitor/package.json`
- Exec `yarn` from project root. Works!
- Exec `yarn quasar dev -m capacitor -T android`
- Exec `yarn` from project root. Error.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Capacitor Mode

### Quasar info output

```Shell
Operating System - Linux(5.15.90.1-microsoft-standard-WSL2) - linux/x64
NodeJs - 18.17.0

Global packages
  NPM - 9.8.1
  yarn - 3.6.1
  @quasar/cli - undefined
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.12.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.4 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - 5.2.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 5.2.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 5.2.2 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 5.2.2 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  *None installed*

Networking
  Host - rzcx
  eth0 - 172.18.58.255
```

### Relevant log output

```Shell
Internal Error: Duplicate workspace name quasar-project: /opt/test/quasar-project/src-capacitor conflicts with /opt/test/quasar-project
    at je.addWorkspace (/home/razorness/.cache/node/corepack/yarn/3.6.1/yarn.js:439:1949)
    at /home/razorness/.cache/node/corepack/yarn/3.6.1/yarn.js:439:1658
```

**Comment by customautosys** [comment]
Hi, also experienced bug today and because I couldn't find a way to add capacitor I decided to stick with cordova.
