### ISSUE TITLE
Build errors when using defineProps<QTableProps>()

### ISSUE THREAD

**Issue by danielbender1989** [quasarframework/quasar#16363]
### What happened?

I am writing a wrapper component DTable for the q-table which should pass all props to q-table directly like this:

```
<template>
  <q-table v-bind="$props" />
</template>

<script setup lang="ts">
import { QTableProps } from 'quasar';

defineProps<QTableProps>();
</script>
```

During build of the project 'Unexpected token, expected "," (76:21)' is thrown.

Same thing was tested with QCardProps and the q-card component and it worked as expected.

### What did you expect to happen?

Component compiles without error and whenever someone hands over a q-table prop (e.g. `<d-table :rows="rows"/>`), it is handed over to the q-table component.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-lgobhe?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Got to the reproduction link
2. Error comes during build

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar), TypeScript Support

### Platforms/Browsers

Firefox

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 18.17.1

Global packages
  NPM - 9.3.1
  yarn - Not installed
  @quasar/cli - 2.0.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.49.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
App •  LINT OK  • C:/Users/CVMZN/IdeaProjects/sandbox/test-table-interface/src/components/ExampleComponent.vue

Error in error handler:
Error: offset is longer than source length! offset 4205 > length 165
    at numberToPos (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:18524:15)
    at formatError (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39102:35)
    at TransformContext.error (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19)
    at Object.transform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39320:25)
    at async doTransform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)

Unexpected token, expected "," (76:21)
Error in error handler:
Error: offset is longer than source length! offset 4205 > length 165
    at numberToPos (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:18524:15)
    at formatError (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39102:35)
    at TransformContext.error (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19)
    at Object.transform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39320:25)
    at async doTransform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)

12:55:30 [vite] Internal server error: Unexpected token, expected "," (76:21)
  Plugin: vite:vue
  File: C:/Users/CVMZN/IdeaProjects/sandbox/test-table-interface/src/components/DTable.vue
      at constructor (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:348:19)
      at TypeScriptParserMixin.raise (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3202:19)
      at TypeScriptParserMixin.unexpected (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3232:16)
      at TypeScriptParserMixin.expect (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3569:28)
      at TypeScriptParserMixin.parseObjectLike (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:11611:14)
      at TypeScriptParserMixin.parseExprAtom (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:11131:23)
      at TypeScriptParserMixin.parseExprSubscripts (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10839:23)
      at TypeScriptParserMixin.parseUpdate (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10822:21)
      at TypeScriptParserMixin.parseMaybeUnary (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10798:23)
      at TypeScriptParserMixin.parseMaybeUnary (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:9682:18)
Error in error handler:
Error: offset is longer than source length! offset 4205 > length 165
    at numberToPos (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:18524:15)
    at formatError (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39102:35)
    at TransformContext.error (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39076:19)
    at Object.transform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:39320:25)
    at async doTransform (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:50043:29)

12:55:30 [vite] Internal server error: Unexpected token, expected "," (76:21)
  Plugin: vite:vue
  File: C:/Users/CVMZN/IdeaProjects/sandbox/test-table-interface/src/components/DTable.vue
      at constructor (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:348:19)
      at TypeScriptParserMixin.raise (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3202:19)
      at TypeScriptParserMixin.unexpected (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3232:16)
      at TypeScriptParserMixin.expect (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:3569:28)
      at TypeScriptParserMixin.parseObjectLike (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:11611:14)
      at TypeScriptParserMixin.parseExprAtom (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:11131:23)
      at TypeScriptParserMixin.parseExprSubscripts (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10839:23)
      at TypeScriptParserMixin.parseUpdate (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10822:21)
      at TypeScriptParserMixin.parseMaybeUnary (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:10798:23)
      at TypeScriptParserMixin.parseMaybeUnary (C:\Users\CVMZN\IdeaProjects\sandbox\test-table-interface\node_modules\@babel\parser\lib\index.js:9682:18)
```

**Comment by yusufkandemir** [comment]
It's not a Quasar problem, it's a Vue problem:
https://github.com/quasarframework/quasar/discussions/16343#discussioncomment-7013837

**Comment by danielbender1989** [comment]
Thanks @yusufkandemir  this helped me to find the cause of the problem. My workaround for now is to omit the problematic attributes:

```
<template>
  <q-table v-bind="$props" />
</template>

<script setup lang="ts">
import { QTableProps } from 'quasar';

defineProps<
  Omit<
    QTableProps,
    'onUpdate:pagination' | 'onUpdate:selected' | 'onUpdate:expanded'
  >
>();
</script>
```
