### ISSUE TITLE
quasar.sass error map-get($value, "y")

### ISSUE THREAD

**Issue by thinkido** [quasarframework/quasar#16388]
### What happened?

9:31:58 PM [vite] Internal server error: $map: 0 is not a map.
     ╷
7197 │     padding: map-get($value, "y") map-get($value, "x")
     │              ^^^^^^^^^^^^^^^^^^^^
     ╵
  node_modules/quasar/dist/quasar.sass 7197:14  root stylesheet
  Plugin: vite:css
  File: /home/thinkido/workspace/todo-cool-quasar/node_modules/quasar/dist/quasar.sass
  Error: $map: 0 is not a map.
       ╷
  7197 │     padding: map-get($value, "y") map-get($value, "x")
       │              ^^^^^^^^^^^^^^^^^^^^
       ╵
    node_modules/quasar/dist/quasar.sass 7197:14  root stylesheet
      at Object._newRenderError (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:13172:19)
      at Object._wrapException (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:12998:16)
      at _render_closure1.call$2 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:81115:21)
      at _RootZone.runBinary$3$3 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:27260:18)
      at _FutureListener.handleError$1 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:25816:19)
      at _Future__propagateToListeners_handleError.call$0 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:26114:49)
      at Object._Future__propagateToListeners (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:4536:77)
      at _Future._completeError$2 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:25946:9)
      at _AsyncAwaitCompleter.completeError$2 (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:25600:12)
      at Object._asyncRethrow (/home/thinkido/workspace/todo-cool-quasar/node_modules/sass/sass.dart.js:4335:17)

- Convert project to Quasar CLI with Vite

### What did you expect to happen?

- Convert project to Quasar CLI with Vite
- quasar.sass error

### Reproduction URL

- none

### How to reproduce?

- none

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by thinkido** [comment]
my mistake

Variables list
$space-base   : 16px !default
$space-x-base : $space-base !default
$space-y-base : $space-base !default

$space-none : (x: 0, y: 0) !default
$space-xs   : (x: ($space-x-base * .25), y: ($space-y-base * .25)) !default
$space-sm   : (x: ($space-x-base * .5), y: ($space-y-base * .5)) !default
$space-md   : (x: $space-x-base, y: $space-y-base) !default
$space-lg   : (x: ($space-x-base * 1.5), y: ($space-y-base * 1.5)) !default
$space-xl   : (x: ($space-x-base * 3), y: ($space-y-base * 3)) !default

mine scss file is

$space-base : 16px;
$space-x-base : $space-base ;
$space-y-base : $space-base ;

$space-none : 0;
$space-xs : ($space-x-base * .25);
$space-sm : ($space-x-base * .5);
$space-md : ($space-x-base );
$space-lg : ($space-x-base * 1.5);
$space-xl : ($space-x-base * 3);
