### ISSUE TITLE
quasar.config.js.devServer.host does not work with vite.server.host allowed values

### ISSUE THREAD

**Issue by mmouterde** [quasarframework/quasar#16601]
### What happened?

According to [vite doc](https://vitejs.dev/config/server-options.html#server-host) pointed by [quasar config doc](https://quasar.dev/quasar-cli-vite/quasar-config-file#devserver)  : two value are allowed : `true` and `"0.0.0.0"`
```
{
...
 devServer:{
  host:true
 }
}
```

- The `true` value makes server crash due to `host.toLowercase()`
- `"0.0.0.0"` is ignored

### What did you expect to happen?

According to [vite doc](https://vitejs.dev/config/server-options.html#server-host) :
> Specify which IP addresses the server should listen on. Set this to 0.0.0.0 or true to listen on all addresses, including LAN and public addresses.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-kjkcma?file=quasar.config.js

### How to reproduce?

Just use `true` or `"0.0.0.0"` as devServer.host value.
Reproduction URL does not work, probably due to stackbiltz wrapping.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
Operating System - Linux(5.15.0-88-generic) - linux/x64
NodeJs - 16.14.2

Global packages
  NPM - 8.5.0
  yarn - 1.22.5
  @quasar/cli - undefined
  @quasar/icongenie - 3.1.0
  cordova - You have been opted out of telemetry. To change this, run: cordova telemetry on.
12.0.0 (cordova-lib@12.0.1)

Important local packages
  quasar - 2.13.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.6.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.7 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.7 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - Not installed
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.52.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/android - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 5.5.1 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  *None installed*

Networking
  Host - mmo-XPS-13-9360
  wlp58s0 - 192.168.1.26
  wg0 - 10.0.0.5
  br-5b095e80e9d2 - 172.18.0.1
```

### Relevant log output

```Shell
$ quasar dev -m capacitor -T android

.../mobile/node_modules/@quasar/app-vite/lib/quasar-config-file.js:100
    && (!host || localHostList.includes(host.toLowerCase()))
                                            ^

TypeError: host.toLowerCase is not a function
    at onAddress (.../mobile/node_modules/@quasar/app-vite/lib/quasar-config-file.js:100:46)
    at QuasarConfFile.read (.../mobile/node_modules/@quasar/app-vite/lib/quasar-config-file.js:349:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async goLive (.../mobile/node_modules/@quasar/app-vite/lib/cmd/dev.js:152:22)
error Command failed with exit code 1.
```

**Comment by glorat** [comment]
Bump - I just ran into this too
