### ISSUE TITLE
PWA Error: Expected /custom-service-worker.ts to have javascript content-type, but received video/mp2t

### ISSUE THREAD

**Issue by maksimdrosdov** [quasarframework/quasar#16642]
### What happened?

I'm trying to configure a service worker, but errors are popping up.

I use quasar dev - pwa

I use this configuration

```
pwa: {
    workboxMode: 'injectManifest', // or 'injectManifest' //generateSW
    swFilename: 'custom-service-worker.ts',
    injectPwaMetaTags: true,
    manifestFilename: 'manifest.json'
    // useCredentialsForManifestTag: false
    // useFilenameHashes: true,
    // extendGenerateSWOptions (cfg) {}
    // extendInjectManifestOptions (cfg) {},
    // extendManifestJson (json) {}
    // extendPWACustomSWConf (esbuildConf) {}
  }
```

The file structure is like this src-pwa directory
<img width="266" alt="Снимок экрана 2023-11-29 в 01 02 15" src="https://github.com/quasarframework/quasar/assets/114719453/9c9724de-09f2-4fa5-b9c6-ce0ad748797c">

but it gives an error

```
Error during service worker registration: Error: Expected /custom-service-worker.ts to have javascript content-type, but received video/mp2t
    at index.js:116:23
```

register-service-worker file

```
import { register } from 'register-service-worker';

register(process.env.SERVICE_WORKER_FILE, {
  // registrationOptions: { scope: './' },

  ready(/* registration */) {
    console.log('Service worker is active.');
  },

  registered(/* registration */) {
    console.log('Service worker has been registered.');
  },

  cached(/* registration */) {
    // console.log('Content has been cached for offline use.')
  },

  updatefound(/* registration */) {
    // console.log('New content is downloading.')
  },

  updated(/* registration */) {
    // console.log('New content is available; please refresh.')
  },

  offline() {
    // console.log('No internet connection found. App is running in offline mode.')
  },

  error(err) {
    console.error('Error during service worker registration:', err);
  }
});
```

custom-service-worker.ts file

```
declare const self: ServiceWorkerGlobalScope &
  typeof globalThis & { skipWaiting: () => void };

import { clientsClaim } from 'workbox-core';
import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  createHandlerBoundToURL
} from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

self.skipWaiting();
clientsClaim();

// Use with precache injection
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Non-SSR fallback to index.html
// Production SSR fallback to offline.html (except for dev)
if (process.env.MODE !== 'ssr' || process.env.PROD) {
  registerRoute(
    new NavigationRoute(
      createHandlerBoundToURL(process.env.PWA_FALLBACK_HTML),
      { denylist: [/sw\.js$/, /workbox-(.)*\.js$/] }
    )
  );
}
```

I don’t even know where to dig anymore. If I delete it swFilename: 'custom-service-worker.ts', then it’s an error

```
Uncaught non-precached-url: createHandlerBoundToURL('index.html') was called, but that URL is not precached. Please pass in a URL that is precached instead.
    at PrecacheController.createHandlerBoundToURL (http://localhost:9200/sw.js:1175:15)
    at createHandlerBoundToURL (http://localhost:9200/sw.js:1655:32)
    at http://localhost:9200/sw.js:1725:9
    at http://localhost:9200/sw.js:1730:3
```

### What did you expect to happen?

-

### Reproduction URL

-

### How to reproduce?

quasar dev -m pwa

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), Components (quasar), Composables (quasar), TypeScript Support, SPA Mode, PWA Mode

**Comment by rstoenescu** [comment]
The `swFilename` prop should be ending with `.js` as it is the distribution file, NOT the input file.
