### ISSUE TITLE
Extensions deploy failed with netlify

### ISSUE THREAD

**Issue by Junvary** [quasarframework/quasar#16652]
### What happened?

Extensions deploy failed with netlify

### What did you expect to happen?

deploy success

### Reproduction URL

Netlify

### How to reproduce?

Extensions deploy failed with netlify

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar Extras (@quasar/extras)

### Quasar info output

```Shell
3:40:28 PM:  Build mode................ spa
3:40:28 PM:  Pkg quasar................ v2.14.1
3:40:28 PM:  Pkg @quasar/app-webpack... v3.12.0
3:40:28 PM:  Pkg webpack............... v5
3:40:28 PM:  Debugging................. no
3:40:28 PM:  Publishing................ no
```

### Relevant log output

```Shell
3:40:35 PM:  App •  ERROR  •  UI  in ../node_modules/@quasar/extras/material-icons/material-icons.css
3:40:35 PM: Syntax Error: ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
3:40:35 PM:  - options.url should be one of these:
3:40:35 PM:    boolean | function
3:40:35 PM:    -> Enables/Disables "url"/"image-set" functions handling (https://github.com/webpack-contrib/css-loader#url).
3:40:35 PM:    Details:
3:40:35 PM:     * options.url should be a boolean.
3:40:35 PM:     * options.url should be an instance of function.
3:40:35 PM:     at validate (/opt/build/repo/ui/node_modules/schema-utils/dist/validate.js:191:11)
3:40:35 PM:     at Object.loader (/opt/build/repo/ui/node_modules/css-loader/dist/index.js:36:29)
3:40:35 PM:  App •  COMPILATION FAILED  • Please check the log above for details.
3:40:35 PM: 
3:40:35 PM: error Command failed with exit code 1.
3:40:35 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
3:40:35 PM: ​
3:40:35 PM: "build.command" failed                                        
3:40:35 PM: ────────────────────────────────────────────────────────────────
3:40:35 PM: ​
3:40:35 PM:   Error message
3:40:35 PM:   Command failed with exit code 1: yarn && cd dev && yarn && yarn build
3:40:35 PM: ​
3:40:35 PM:   Error location
3:40:35 PM:   In Build command from Netlify app:
3:40:35 PM:   yarn && cd dev && yarn && yarn build
3:40:35 PM: ​
3:40:35 PM:   Resolved config
3:40:35 PM:   build:
3:40:35 PM:     base: /opt/build/repo/ui
3:40:35 PM:     command: yarn && cd dev && yarn && yarn build
3:40:35 PM:     commandOrigin: ui
3:40:35 PM:     publish: /opt/build/repo/ui/dev/dist/spa
3:40:35 PM:     publishOrigin: ui
3:40:35 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
3:40:35 PM: Failing build: Failed to build site
3:40:35 PM: Finished processing build request in 1m58.741s
```

**Comment by rstoenescu** [comment]
Hi,

Please provide a reproduction repo (see the above message). We cannot tell what your quasar.config file looks like nor what you are compiling, so there is nothing actionable from our part.
