### ISSUE TITLE
getActivePinia() error on new workstation

### ISSUE THREAD

**Issue by dost-mmg** [quasarframework/quasar#16688]
### What happened?

1. App worked fine on Windows and  from repo.
2. Synced local copy to new Mac and when running "quasar dev" a getActivePinia() error was thrown.
3. The error was thrown even on a completely stripped down app test. 
4. Error is not thrown on new quasar App ran on new Mac machine.
5. NOTE: There are two additional warnings that I haven't figured out. "This selector doesn't have any properties and won't be rendered.

null

### What did you expect to happen?

Running quasar dev would launch app as it was running on other machine.

### Reproduction URL

https://github.com/dost-mmg/testjh

### How to reproduce?

1. Go to reproduction link.
2. Run NPM ci
3. Run quasar dev

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Darwin(23.1.0) - darwin/arm64
NodeJs - 20.10.0

Global packages
  NPM - 10.2.3
  yarn - Not installed
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.12.1 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.11 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.23.6 -- Babel compiler core.
  webpack - 5.89.0 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - mes-Laptop.local
  en0 - xxx

me@mes-Laptop jobhubber %
```

### Relevant log output

```Shell
caught (in promise) Error: [🍍]: "getActivePinia()" was called but there was no active Pinia. Are you trying to use a store before calling "app.use(pinia)"?
See https://pinia.vuejs.org/core-concepts/outside-component-usage.html for help.
This will fail in production.
    at useStore (pinia.mjs:1727:19)
    at setup (index.js??clonedRuleSet-2.use[0]!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/layouts/SplashLayout.vue?vue&type=script&lang=js:23:79)
    at callWithErrorHandling (runtime-core.esm-bundler.js:296:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7442:25)
    at setupComponent (runtime-core.esm-bundler.js:7403:36)
    at mountComponent (runtime-core.esm-bundler.js:5800:7)
    at processComponent (runtime-core.esm-bundler.js:5766:9)
    at patch (runtime-core.esm-bundler.js:5254:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5974:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:217:19)
```

### Additional context

For some reason, when I change the store folder to stores, and then change history from hash to history, the problem goes away. I don't know what the combination or what aspect of that is actually doing.

**Comment by dost-mmg** [comment]
Zero idea why this worked, but my folder was titled 'store' and I changed it to 'stores' and it worked. It was working for months on the windows machine titled as 'store'
