### ISSUE TITLE
How to re-enable "global" in SSR mode? 

### ISSUE THREAD

**Issue by itinance** [quasarframework/quasar#16720]
### What happened?

Basic libraries like "graceful-fs" or "file-system-cache" are requiring `global`. It is not available in the SSR-Mode.

So we can not use these libs server side and instead get errors like:

`ReferenceError: global is not defined`

### What did you expect to happen?

`global` variable still exists.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-eygtuk?file=quasar.config.js

### How to reproduce?

Either start the demo project from here in SSR mode: `https://stackblitz.com/edit/quasarframework-eygtuk?file=quasar.config.js`

or setup easily from scratch:

1. setup a new quasar applciation

2.
```
yarn add file-system-cache
```

3. server side, like in a boot file enabled for server and disabled for client:
`const cache = Cache({})`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support, SSR Mode

### Quasar info output

```Shell
Operating System - Darwin(22.6.0) - darwin/arm64
NodeJs - 18.17.1

Global packages
  NPM - 9.6.7
  yarn - 1.22.19
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.12.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.4 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.45.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
Uncaught (in promise) ReferenceError: global is not defined
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:45:7)
    at __require (chunk-J43GMYXM.js?v=157be694:11:50)
    at node_modules/fs-extra/lib/fs/index.js (index.js:5:12)
    at __require (chunk-J43GMYXM.js?v=157be694:11:50)
    at node_modules/fs-extra/lib/index.js (index.js:5:6)
    at __require (chunk-J43GMYXM.js?v=157be694:11:50)
    at node_modules/file-system-cache/lib/common/libs.js (libs.js:32:36)
    at __require (chunk-J43GMYXM.js?v=157be694:11:50)
    at node_modules/file-system-cache/lib/common/util.js (util.js:13:16)
    at __require (chunk-J43GMYXM.js?v=157be694:11:50)
```

**Comment by stefanvanherwijnen** [comment]
As far as I know, there is no default `globals` variable as there is for `window`. So this shouldn't be related to SSR, but probably a dependency of either one of those packages uses [globals](https://www.npmjs.com/package/globals) which looks like a CJS only package.
I'd advise to find a ESM alternative to those packages,

**Comment by rstoenescu** [comment]
Closing as not reproducible. There is nothing to re-enable here: `global` is a Node.js built-in and SSR never removes it. Your boot file was not running in Node when it threw.

**What the stack trace says**

```
at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:45:7)
at __require (chunk-J43GMYXM.js?v=157be694:11:50)
```

`chunk-*.js?v=<hash>` together with the esbuild `__require` shim is the output of Vite's client dependency optimizer. That code only ever runs in the browser, and the browser has no `global`. So `file-system-cache` (and its `graceful-fs` dependency, which reads `global[...]` at module top) got bundled for and executed by the browser.

**Why a `client: false` boot file can still reach the browser**

`boot: [{ client: false, path: 'cache' }]` only keeps the boot file out of the generated client entry. Your boot file also does `export { cache }`, and any client code that imports that module (for example `import { cache } from 'boot/cache'` inside a component or a store) pulls the whole thing, Node-only dependencies included, into the client bundle. The boot flag cannot prevent that; it is a plain ES import.

The StackBlitz you linked does not contain such an import and its `dev` script runs plain `quasar dev` (SPA mode), so the project as published does not show the error either.

**Verified on current versions**

Fresh app with quasar 2.30.1, @quasar/app-vite 3.8.2, vite 8.2.2 and file-system-cache 2.4.4, the boot file registered exactly as above:

- `quasar dev -m ssr`: the page renders, the boot file runs on the server with `typeof global === 'object'` and writes its cache files; the generated client entry never references the boot file.
- `quasar build -m ssr` and the production server: the package stays external in the server bundle and the boot file runs the same way.

**What to do instead**

- Never import a server-only boot module from code that also ships to the client. Read the instance through `app.config.globalProperties.$cache` (or provide/inject) and guard the usage with `process.env.SERVER` / `import.meta.env.SSR` where needed.
- Node-only work that does not need the Vue app can live in `src-ssr/middlewares` instead of a boot file.
- Unrelated interop note: the package is `__esModule` CommonJS with `exports.default`, so under Node's interop `import Cache from 'file-system-cache'` gives you the exports object. Use `import { Cache } from 'file-system-cache'` and `new Cache(options)`.
