### ISSUE TITLE
Bug  $rad: math.div($angle, 180) * $PI

### ISSUE THREAD

**Issue by boahost** [quasarframework/quasar#16944]
### What happened?

Good morning!

How i run the command quasar dev 

[plugin:vite:css] Undefined function.
   ╷
45 │   $rad: math.div($angle, 180) * $PI
   │         ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\quasar\dist\quasar.sass 45:9     sin()
  node_modules\quasar\dist\quasar.sass 4597:16  root stylesheet

### What did you expect to happen?

run the command

### Reproduction URL

https://donthave.com

### How to reproduce?

how i can run the command 

quasar dev

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Plugins (quasar)

**Comment by rstoenescu** [comment]
Hi,

Please upgrade your `sass` dependency to its latest version.

**Comment by boahost** [comment]
My package is 


{
  "name": "quasar",
  "version": "0.0.1",
  "description": "A Quasar Project",
  "productName": "Seguranca Institucional",
  "author": "Jose",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@quasar/extras": "^1.15.5",
    "axios": "^0.21.1",
    "node-sass": "^9.0.0",
    "pinia": "^2.0.14",
    "quasar": "^2.14.5",
    "quasar-app": "^0.0.1",
    "quasar-dotenv": "^1.0.5",
    "vue": "^3.0.0",
    "vue-moment": "^4.1.0",
    "vue-router": "^4.0.0",
    "yarn": "^1.22.21"
  },
  "devDependencies": {
    "@quasar/app-vite": "^1.1.3",
    "@quasar/quasar-app-extension-dotenv": "^1.1.0",
    "autoprefixer": "^10.4.2",
    "dotenv": "^16.0.1",
    "eslint": "^8.10.0",
    "eslint-config-standard": "^17.0.0-1",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-vue": "^8.5.0"
  },
  "engines": {
    "node": "^18 || ^16 || ^14.19",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}

**Comment by rstoenescu** [comment]
Your `/package.json` only tells about the minimum version (due to the caret characters), NOT the actually installed versions. Upgrade them all (both q/app-vite and quasar) to the latest.

**Comment by caner-cetin** [comment]
@rstoenescu 
```bash
❯ cd frontend
❯ quasar upgrade

 Global Quasar CLI • Gathering information from the NPM registry (https://registry.npmjs.org/)...

 Global Quasar CLI • Congrats! All Quasar packages are up to date (according to https://registry.npmjs.org/).
```

yet i still see

```bash
2024-04-06 18:11:06   File: /frontend/node_modules/quasar/dist/quasar.sass
2024-04-06 18:11:06   Error: Undefined function.
2024-04-06 18:11:06      ╷
2024-04-06 18:11:06   45 │   $rad: math.div($angle, 180) * $PI
2024-04-06 18:11:06      │         ^^^^^^^^^^^^^^^^^^^^^
2024-04-06 18:11:06      ╵
2024-04-06 18:11:06     node_modules/quasar/dist/quasar.sass 45:9     sin()
2024-04-06 18:11:06     node_modules/quasar/dist/quasar.sass 4562:16  root stylesheet
2024-04-06 18:11:06       at Object._newRenderError (/frontend/node_modules/sass/sass.dart.js:13172:19)
2024-04-06 18:11:06       at Object._wrapException (/frontend/node_modules/sass/sass.dart.js:12998:16)
2024-04-06 18:11:06       at _render_closure1.call$2 (/frontend/node_modules/sass/sass.dart.js:81115:21)
2024-04-06 18:11:06       at _RootZone.runBinary$3$3 (/frontend/node_modules/sass/sass.dart.js:27260:18)
2024-04-06 18:11:06       at _FutureListener.handleError$1 (/frontend/node_modules/sass/sass.dart.js:25816:19)
2024-04-06 18:11:06       at _Future__propagateToListeners_handleError.call$0 (/frontend/node_modules/sass/sass.dart.js:26114:49)
2024-04-06 18:11:06       at Object._Future__propagateToListeners (/frontend/node_modules/sass/sass.dart.js:4536:77)
2024-04-06 18:11:06       at _Future._completeError$2 (/frontend/node_modules/sass/sass.dart.js:25946:9)
2024-04-06 18:11:06       at _AsyncAwaitCompleter.completeError$2 (/frontend/node_modules/sass/sass.dart.js:25600:12)
2024-04-06 18:11:06       at Object._asyncRethrow (/frontend/node_modules/sass/sass.dart.js:4335:17)
```

 when I load in my website that is run by docker 

```bash
FROM node:latest as develop-stage
WORKDIR /frontend
RUN yarn config set ignore-engines true
COPY ./frontend/package.json ./
COPY ./frontend/quasar.config.js ./
RUN yarn install --production=false
COPY ./frontend/ ./
RUN yarn global add @quasar/cli --production=false
EXPOSE 8080
ENTRYPOINT ["quasar", "dev", "--p", "8080"]
```
