### ISSUE TITLE
Syntax Error: TypeError: importTransformation is not a function

### ISSUE THREAD

**Issue by felek000** [quasarframework/quasar#17276]
### What happened?

Standard project non upgrade done in few days.

After remove node-modules i get error

```
Syntax Error: TypeError: importTransformation is not a function
    at /node_modules/@quasar/app-webpack/lib/webpack/loader.js.transform-quasar-imports.js:23:85
```

This refers to 
```quasar/dist/transforms/import-transformation.js``` file was not exist in path. 

dependency list
```
  "dependencies": {
    "@capacitor/camera": "^4.1.4",
    "@capacitor/cli": "^4.7.0",
    "@capacitor/core": "^4.7.0",
    "@capacitor/geolocation": "^4.1.0",
    "@ionic/pwa-elements": "^3.1.1",
    "@quasar/cli": "^1.4.0",
    "@quasar/extras": "^1.16.9",
    "@quasar/quasar-app-extension-qenv": "^1.1.0",
    "@twilio/video-processors": "^2.1.0",
    "@vue/compiler-sfc": "^3.4.19",
    "@vueuse/components": "^10.6.1",
    "@vueuse/core": "^10.6.1",
    "axios": "^0.18.1",
    "babel-loader": "^9.1.3",
    "core-js": "^3.6.5",
    "dayjs": "^1.10.2",
    "dexie": "^3.2.3",
    "downloadjs": "^1.4.7",
    "eslint-webpack-plugin": "^4.0.0",
    "file-saver": "^2.0.5",
    "hammerjs": "^2.0.8",
    "idb": "^6.0.0",
    "install": "^0.13.0",
    "jszip": "^3.5.0",
    "lodash-es": "^4.17.15",
    "mic-check": "^1.1.0",
    "quasar": "^2.14.4",
    "rxjs": "^6.6.3",
    "rxjs-for-await": "^0.0.2",
    "sass": "1.33.0",
    "simple-crypto-js": "^3.0.0",
    "twilio-video": "^2.28.1",
    "vue": "^3.4.19",
    "vue-i18n": "^9.2.2",
    "vue-offline": "^2.0.8",
    "vue-router": "4",
    "vue-router-multiguard": "^1.0.3",
    "vuex": "4",
    "workerize-loader": "^1.3.0",
    "xstate": "^4.38.1"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.12.7",
    "@intlify/vue-i18n-loader": "^4.2.0",
    "@quasar/app-webpack": "3.12.3",
    "@quasar/quasar-app-extension-dotenv": "^1.1.0",
    "@quasar/quasar-app-extension-testing": "^1.0.3",
    "@vue/devtools": "^6.5.0",
    "cross-env": "^7.0.2",
    "dotenv": "^16.4.5",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-plugin-import": "^2.19.1",
    "eslint-plugin-jest": "^24.1.0",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-quasar": "^1.0.0",
    "eslint-plugin-vue": "^7.0.0",
    "sass-loader": "12.0.0",
    "workbox-webpack-plugin": "^7.0.0"
  },
```

### What did you expect to happen?

Will build proper. After i Found file on server build works fine.

### Reproduction URL

''

### How to reproduce?

yarn install
quasar build -m pwa

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

### Quasar info output

```Shell
Syntax Error: TypeError: importTransformation is not a function
    at /home/prfi/projekty/idoc-pwa/front/node_modules/@quasar/app-webpack/lib/webpack/loader.js.transform-quasar-imports.js:23:85
```

**Comment by yusufkandemir** [comment]
Make sure both `@quasar/app-webpack` and `quasar` are the latest versions.

**Comment by felek000** [comment]
@yusufkandemir 


I updated
Project is building.
```
"@quasar/app-webpack": "3.13.2",
"quasar": "^2.16.4",
```

However now in old component I have error.

```Cannot convert object to primitive value```

I check lines and i have simple assignments:  ` this.textLabel = 'aaa'`
This happens only in few place also assignments object/arrays.

**Comment by yusufkandemir** [comment]
What's the **FULL** error message with stack trace? What is the **FULL** code in the file with errors?

**Comment by felek000** [comment]
@yusufkandemir 

Found it.

If any one will look. i Had dynamic ref to component `:red="$refs.name"` It was behind v-if. Before it was no problem. Now its create `Cannot convert object to primitive value` error. When i remove it error gone. The problem was that it points me to assign error from diffrent line.
