### ISSUE TITLE
can't run quasar build successfully after upgrade to latest version

### ISSUE THREAD

**Issue by Zhangshunyao** [quasarframework/quasar#17419]
### What happened?

please see below screenshot
<img width="1117" alt="截屏2024-08-07 16 46 27" src="https://github.com/user-attachments/assets/d88db217-7e12-46ee-a8ee-3b758e534d41">

### What did you expect to happen?

just build my project correctly

### Reproduction URL

https://jsfiddle.net/rstoenescdfsafdsau/a2cuzodsfdsafdafda

### How to reproduce?

upgrade to latest version and run 

quasar b

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), SPA Mode

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Darwin(23.5.0) - darwin/arm64
NodeJs - 18.17.0

Global packages
  NPM - 10.6.0
  yarn - 1.22.22
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.9.4 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.3.4 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.4
  pinia - 2.1.6 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.46.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - MBP.local
  en0 - 10.0.0.6
  utun8 - 198.18.0.1
```

### Relevant log output

```Shell
.d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b


 Build mode............. spa
 Pkg quasar............. v2.16.7
 Pkg @quasar/app-vite... v1.9.4
 Pkg vite............... v2.9.16
 Debugging.............. no
 Publishing............. no

node:fs:603
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/v/zSpace/0.Dev/va2023/node_modules/quasar/dist/transforms/import-map.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Object.<anonymous> (/Users/v/zSpace/0.Dev/va2023/node_modules/@quasar/vite-plugin/dist/index.cjs:67:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/v/zSpace/0.Dev/va2023/node_modules/@quasar/app-vite/lib/quasar-config-file.js:6:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/v/zSpace/0.Dev/va2023/node_modules/quasar/dist/transforms/import-map.json'
}

Node.js v18.17.0
```

### Additional context

just after upgrade

**Comment by yusufkandemir** [comment]
You have the correct versions which should play nicely. But, there might have been a problem with the package manager messing stuff up.
Please delete `node_modules`, re-install dependencies, and try again. If it doesn't work, delete `node_modules` and the lock file, re-install dependencies, and try again.

**Comment by rstoenescu** [comment]
Please reopen if you followed our recommendations and are still having the issue.
