### ISSUE TITLE
viteConf.server.watch.ignored not respected

### ISSUE THREAD

**Issue by Marvosg** [quasarframework/quasar#17551]
### What happened?

My project is configured with a subfolder (`docker`) that contains folders that are not owned by the current user, and cannot be read. I want to ignore this folder when building and when running the dev server.

My `quasar.config.ts` file:
```ts
import { configure } from 'quasar/wrappers';
// ...

export default configure((ctx) => {
    return {
        //...
        build: {
            // ...
            extendViteConf(viteConf) {
                viteConf.server = viteConf.server || {};
                viteConf.server.watch = viteConf.server.watch || {};
                viteConf.server.watch.ignored = ['**/docker/**'];
            }
        }
    }
```

But the `docker` folder is still being watched. `quasar dev` crashes with
```
Error: EACCES: permission denied, watch '/home/myuser/myrepo/docker/volumes/db/data'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2491:36)
    at createFsWatchInstance (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:617:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  errno: -13,
  syscall: 'watch',
  code: 'EACCES',
  path: '/home/myuser/myrepo/docker/volumes/db/data',
  filename: '/home/myuser/myrepo/docker/volumes/db/data'
}

Node.js v20.17.0
```

### What did you expect to happen?

The folder `docker` should be ignored - not watched.

### Reproduction URL

sorry, can't make folders that are not owned by the current user on these services

### How to reproduce?

1. Create a folder in your project directory that is owned by root, not the current user.
2. `quasar dev`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Operating System - Linux(5.15.0-122-generic) - linux/x64
NodeJs - 20.17.0

Global packages
  NPM - 10.8.2
  yarn - Not installed
  pnpm - 9.11.0
  bun - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.0.0-beta.21 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.6 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.5
  pinia - 2.2.2 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 5.4.6 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 8.57.1 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.23.1 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.5.4 -- TypeScript is a language for application scale JavaScript development
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
Error: EACCES: permission denied, watch '/home/myuser/myrepo/docker/volumes/db/data'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2491:36)
    at createFsWatchInstance (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (/home/myuser/myrepo/node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/lib/nodefs-handler.js:617:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  errno: -13,
  syscall: 'watch',
  code: 'EACCES',
  path: '/home/myuser/myrepo/docker/volumes/db/data',
  filename: '/home/myuser/myrepo/docker/volumes/db/data'
}
```

**Comment by yusufkandemir** [comment]
This is not related to Quasar or Vite. This is about configuring Chokidar correctly, which Vite uses.
As per [Chokidar docs](https://github.com/paulmillr/chokidar/tree/main?tab=readme-ov-file#path-filtering), it's supposed to be a `function, regex, or path`. You've provided a glob pattern. You can convert it to a function instead:
```js
// import { mergeConfig } from 'vite'

// safer way of extending config:
viteConf.server = mergeConfig(viteConf.server, {
  watch: {
    ignored: [
      (path) => path.includes('/docker/') // update logic if needed
    ]
  }
})
```
