### ISSUE TITLE
Regression 2.17.0 in QSelect when `map-options` are `true` and `options` are `null`.

### ISSUE THREAD

**Issue by hazzik** [quasarframework/quasar#17613]
### What happened?

Updated to 2.17.0, many `QSelect` components stopped working. Likely a regression in this commit: https://github.com/quasarframework/quasar/commit/d044fddba1fe0e250934244d186b98314987b416

### What did you expect to happen?

Not throwing TypeError

### Reproduction URL

https://codepen.io/hazzik/pen/OJKZjyM

### How to reproduce?

`<q-select map-options :options="null" />`

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome, Microsoft Edge

### Quasar info output

```Shell
Global packages
  NPM - 10.8.2
  yarn - 1.22.22
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.17.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.14.0 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.11 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.3
  pinia - Not installed
  vuex - 4.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.24.8 -- Babel compiler core.
  webpack - 5.94.0 -- Packs ECMAScript/CommonJs/AMD modules for the browser. Allows you to split your codebase into multiple bundles, which can be loaded on demand. Supports loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  @quasar/quasar-app-extension-qpdfviewer - 2.0.0-alpha.6 -- QPdfviewer is an app extension for viewing PDF files
```

### Relevant log output

```Shell
QSelect.js:612  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'find')
    at getOption (QSelect.js:612:28)
    at QSelect.js:207:37
    at Array.map (<anonymous>)
    at ComputedRefImpl.fn (QSelect.js:207:28)
    at refreshComputed (reactivity.esm-bundler.js:377:1)
    at get value [as value] (reactivity.esm-bundler.js:1693:1)
    at ReactiveEffect.getter [as fn] (reactivity.esm-bundler.js:1791:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:222:1)
    at job (reactivity.esm-bundler.js:1861:1)
    at watch (reactivity.esm-bundler.js:1911:1)
```

### Additional context

Working fine in 2.16.x: https://codepen.io/hazzik/pen/YzmLxym

**Comment by rstoenescu** [comment]
Fix will be available in Quasar v2.17.2
