### ISSUE TITLE
Add Vue SFC support to AEs

### ISSUE THREAD

**Issue by whoacowboy** [quasarframework/quasar#17718]
### What happened?

I created a new ui app-extension and only modified the Component.js. When executing `yarn build` I receive an error if I use the short hand `@` instead of `v-on:` and I also get an error when I use a computed attribute inside a template `:label="item"` or `:data-item="item"`.

```vue
<template>
  <q-btn
    class="component"
    @click="action"
    :label="item"
  ></q-btn>
</template>
<script setup>
import { ref } from 'vue'

const item = ref('hello')
const action = () => (item.value = Math.random().toString(36).substring(2, 12))
</script>
```
and 

```vue
<template>
  <q-btn
    class="component"
    :label="item"
    @click="action"
  ></q-btn>
</template>
<script setup>
import { ref } from 'vue'

const item = ref('hello')
const action = () => (item.value = Math.random().toString(36).substring(2, 12))
</script>
```
error for slightly different reasons but it appears to be buble causing the issue.

I have tried this with div tag as well and I receive the same error.

### What did you expect to happen?

I expected the app-extension ui framework to support the @ shorthand and the hyphenated dynamic attributes.

### Reproduction URL

https://github.com/whoacowboy/app-extension-bug

### How to reproduce?

Create a new UI App extension.

```
yarn create quasar
```

During the CLI process, enter default info wherever possible and appropriate info where user input is required.

```
cd quasar-project/ui
```

Install dependencies

```
yarn
```

Rename `src/components/Component.js` to `src/components/Component.vue`

```
mv src/components/Component.js src/components/Component.vue
```

Replace the code in `src/Components.vue` with the follow code and save

```vue
<template>
  <q-btn
    class="component"
    :data-item="item"
    :label="item"
    @click="action"
  ></q-btn>
</template>
<script setup>
import { ref } from 'vue'

const item = ref('hello')
const action = () => (item.value = Math.random().toString(36).substring(2, 12))
</script>
```

Run the build script

```
yarn build
```

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

App Extension API

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
`quasar info`

Operating System   	Darwin(23.6.0) - darwin/arm64
NodeJs             	20.11.0

Global packages
  NPM              	10.2.4
  yarn             	1.22.22
  pnpm             	Not installed
  bun              	Not installed
  @quasar/cli      	2.4.1
  @quasar/icongenie	Not installed
  cordova          	Not installed

Networking
  Host             	James.localdomain
  en1              	192.168.4.4
  bridge1          	192.168.1.70
```

### Relevant log output

```Shell
ui % yarn build
yarn run v1.22.22
$ node build/index.js

 ⭐️ App Extension version quasar-app-extension-delete-1 synced with UI version.

 💥 Cleaned build artifacts.

 📦 Building v0.0.1... [multi-threaded]

SyntaxError: Unexpected character '@' (2:27)
    at pp$4.raise (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2825:15)
    at pp$9.getTokenFromCode (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:4560:10)
    at pp$9.readToken (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:4288:17)
    at _class.readToken (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:469:20)
    at pp$9.nextToken (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:4279:17)
    at pp$9.next (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:4236:10)
    at pp$3.parseLiteral (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2288:10)
    at pp$3.parseExprAtom (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2220:19)
    at _class.parseExprAtom (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-dynamic-import/lib/index.js:75:117)
    at _class.parseExprAtom (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:445:22) {
  pos: 38,
  loc: Position {
    line: 2,
    column: 27,
    file: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  },
  raisedAt: 38,
  snippet: '1 : <template>\n' +
    '2 :   <q-btn class="component" @click="action" :label="item"></q-btn>\n' +
    '                               ^',
  toString: [Function (anonymous)],
  plugin: 'buble',
  frame: '1 : <template>\n' +
    '2 :   <q-btn class="component" @click="action" :label="item"></q-btn>\n' +
    '                               ^',
  code: 'PLUGIN_ERROR',
  hook: 'transform',
  id: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue',
  watchFiles: [
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/index.umd.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/vue-plugin.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  ]
}
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import 'quasar/src/css/variables.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    src/index.sass 1:9  root stylesheet

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
3 │ @import './components/Component.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    src/index.sass 3:9  root stylesheet

[css]  dist/index.css                              0.15kb (gzipped:   0.15kb)
[css]  dist/index.rtl.css                          0.15kb (gzipped:   0.15kb)
[css]  dist/index.min.css                          0.14kb (gzipped:   0.15kb)
[css]  dist/index.rtl.min.css                      0.14kb (gzipped:   0.15kb)
✨  Done in 0.67s.


##################################################################
Syntax error when putting :label first
##################################################################

SyntaxError: Unexpected token (2:27)
    at pp$4.raise (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2825:15)
    at pp.unexpected (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:689:10)
    at _class.jsx_parseIdentifier (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:257:14)
    at _class.jsx_parseNamespacedName (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:266:23)
    at _class.jsx_parseAttribute (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:343:24)
    at _class.jsx_parseOpeningElementAt (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:356:35)
    at _class.jsx_parseElementAt (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:378:33)
    at _class.jsx_parseElementAt (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:391:32)
    at _class.jsx_parseElement (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:436:19)
    at _class.parseExprAtom (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:443:21) {
  pos: 38,
  loc: Position {
    line: 2,
    column: 27,
    file: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  },
  raisedAt: 39,
  snippet: '1 : <template>\n' +
    '2 :   <q-btn class="component" :label="item" @click="action"></q-btn>\n' +
    '                               ^',
  toString: [Function (anonymous)],
  plugin: 'buble',
  frame: '1 : <template>\n' +
    '2 :   <q-btn class="component" :label="item" @click="action"></q-btn>\n' +
    '                               ^',
  code: 'PLUGIN_ERROR',
  hook: 'transform',
  id: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue',
  watchFiles: [
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/index.esm.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/vue-plugin.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  ]
}
```

**Comment by whoacowboy** [comment]
FWIW I switch :item with v-bind:item and then I got an error about <script setup>

```
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (4:0)
    at pp$4.raise (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2825:15)
    at _class.jsx_parseElementAt (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:418:14)
    at _class.jsx_parseElement (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:436:19)
    at _class.parseExprAtom (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn-jsx/index.js:443:21)
    at pp$3.parseExprSubscripts (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2089:21)
    at pp$3.parseMaybeUnary (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2066:19)
    at pp$3.parseExprOps (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:2010:21)
    at pp$3.parseMaybeConditional (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:1993:21)
    at pp$3.parseMaybeAssign (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:1968:21)
    at pp$3.parseExpression (/Users/james/Code/example/consumer/fe/delete-1/ui/node_modules/buble/node_modules/acorn/dist/acorn.js:1933:21) {
  pos: 99,
  loc: Position {
    line: 4,
    column: 0,
    file: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  },
  raisedAt: 100,
  snippet: '1 : <template>\n' +
    '2 :   <q-btn class="component" v-bind:label="item" v-on:click="action"></q-btn>\n' +
    '3 : </template>\n' +
    '4 : <script setup>\n' +
    '    ^',
  toString: [Function (anonymous)],
  plugin: 'buble',
  frame: '1 : <template>\n' +
    '2 :   <q-btn class="component" v-bind:label="item" v-on:click="action"></q-btn>\n' +
    '3 : </template>\n' +
    '4 : <script setup>\n' +
    '    ^',
  code: 'PLUGIN_ERROR',
  hook: 'transform',
  id: '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue',
  watchFiles: [
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/index.esm.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/vue-plugin.js',
    '/Users/james/Code/example/consumer/fe/delete-1/ui/src/components/Component.vue'
  ]
}
```

**Comment by yusufkandemir** [comment]
The UI kit build process doesn't support Vue SFCs(i.e., `.vue` files). In #17168, we introduced support for SFCs in AEs(not UI kit), TS-only. It has not yet been enabled for use. We are planning to support it in both JS and TS AE templates.

**Comment by whoacowboy** [comment]
Hi @yusufkandemir, do you have a timeline on when you be implementing it.

**Comment by yusufkandemir** [comment]
Hi, unfortunately, no.

/cc @rstoenescu

**Comment by jclaveau** [comment]
@whoacowboy If you want I have updated my build scripts to support SFC, esm and typescript but my app extension is not open sourced yet
[build.zip](https://github.com/user-attachments/files/18354087/build.zip)

You will also need to update some dev deps like
<details><summary>Details</summary>
<p>

```javascript
{
  "name": "quasar-ui-milkdown",
  "version": "0.0.1",
  "author": "Jean Claveau <1556489+jclaveau@users.noreply.github.com>",
  "description": "Milkdown smooth integration with Quasar framework",
  "license": "MIT",
  "type": "module",
  "//module": "dist/index.esm.js",
  "//main": "dist/index.common.js",
  "module": "dist/esm/apps/quasar-ui-milkdown/ui/src/index.esm.js",
  "main": "dist/esm/apps/quasar-ui-milkdown/ui/src/index.esm.js",
  "scripts": {
    "dev:clean": "cd dev && quasar clean && rm -rf node_modules/.q-cache",
    "deveuh": "cd dev && pnpm dev --debug && cd ..",
    "dev:umd": "pnpm build && node build/script.open-umd.js",
    "dev:ssr": "cd dev && pnpm 'dev:ssr' && cd ..",
    "dev:ios": "cd dev && pnpm 'dev:ios' && cd ..",
    "dev:android": "cd dev && pnpm 'dev:android' && cd ..",
    "dev:electron": "cd dev && pnpm 'dev:electron' && cd ..",
    "build": "node build/index.js",
    "build:js": "node build/script.javascript.js",
    "build:css": "node build/script.css.js",
    "test": "playwright test",
    "test:watch": "PWTEST_WATCH=1 playwright test",
    "test:ui": "playwright test --ui",
    "test:headed": "playwright test --headed",
    "test:update-snapshots": "playwright test --update-snapshots",
    "test:gen": "playwright codegen",
    "link:local-clone": "node ./scripts/link.js",
    "": ""
  },
  "devDependencies": {
    "@playwright/test": "^1.49.1",
    "@prosemirror-adapter/vue": "^0.2.6",
    "@quasar/app-vite": "2.0.4",
    "@quasar/extras": "^1.16.4",
    "@rollup/plugin-buble": "^1.0.3",
    "@rollup/plugin-commonjs": "^28.0.2",
    "@rollup/plugin-json": "^6.1.0",
    "@rollup/plugin-node-resolve": "^16.0.0",
    "@rollup/plugin-replace": "^6.0.2",
    "autoprefixer": "^10.0.2",
    "chalk": "^5.4.1",
    "core-js": "^3.39.0",
    "cssnano": "^7.0.6",
    "fs-extra": "^8.1.0",
    "glob": "^11.0.0",
    "open": "^7.3.0",
    "playwright": "^1.49.1",
    "postcss": "^8.1.9",
    "prosemirror-dev-toolkit": "^1.1.8",
    "quasar": "^2.17.5",
    "rimraf": "^6.0.1",
    "rollup": "^4.29.2",
    "rollup-plugin-esbuild": "^6.1.1",
    "rollup-plugin-polyfill-node": "^0.13.0",
    "rollup-plugin-postcss": "^4.0.2",
    "rollup-plugin-styles": "^4.0.0",
    "rtlcss": "^2.6.1",
    "sass": "^1.33.0",
    "uglify-js": "^3.13.3",
    "unplugin-vue": "^5.2.1",
    "vue": "^3.5.13",
    "vue-router": "^4.0.0",
    "webfontloader": "^1.6.28",
    "zlib": "^1.0.5"
  },
  "browserslist": [
    "last 4 Chrome versions",
    "last 4 Firefox versions",
    "last 2 Edge versions",
    "last 4 Safari versions",
    "last 4 Android versions",
    "last 4 ChromeAndroid versions",
    "last 4 FirefoxAndroid versions",
    "last 4 iOS versions"
  ],
  "dependencies": {
    "@milkdown/kit": "^7.5.9",
    "@milkdown/theme-nord": "^7.5.9",
    "@milkdown/vue": "^7.5.9",
    "fuse.js": "^7.0.0"
  }
}
``` 

</p>
</details> 

Just take in consideration it's a work in progress plz

@yusufkandemir If what I shared seems to be the right direction to you, I may patch the app extension template submit a PR 

### Edit: I updated the zip and package after a little clean up

**Comment by whoacowboy** [comment]
@jclaveau This is great, thank you. I am working on integrating it now. Do you have a rollup.config.js or are you not using one?

**Comment by jclaveau** [comment]
> @jclaveau This is great, thank you. 

You're welcome. It's always a pleasure when value is created from my work 🙏

> I am working on integrating it now. Do you have a rollup.config.js or are you not using one?

Nope, I stuck to the previous philosophy. 
- The main difference is that I added a build configuration for developing mode: it preserves modules for an easier targeting in the devtools. 
- The rest is mainly ESM / deps updates and switching to more modern rollup plugins (inspired by the [Directus extension sdk build command](https://github.com/directus/directus/blob/main/packages/extensions-sdk/src/cli/commands/build.ts) )
- Also, I still not have made the extraction of css work again

One thing more: if you want to use Quasar components in the SFC without imports and in kebab-case you will need something like this in your `vue-plugin.ts`

```ts
import MilkdownEditorWrappable from './components/MilkdownEditorWrappable.vue'
import MilkdownEditor from './components/MilkdownEditor.vue'

const version = __UI_VERSION__
import { 
  QPopupProxy,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QAvatar,
  QIcon,
  QTooltip,
} from 'quasar';

import * as directives from 'quasar/src/directives.js'


function install (app) {
  [
    QPopupProxy,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QAvatar,
    QIcon,
    QTooltip,
  ].forEach((component) => {
    app.component(component.name, component)
  })


  Object.entries(directives).forEach(([_key, directive]) => {
    app.directive(directive.name, directive)
  })

  app.component(MilkdownEditor.__name, MilkdownEditor)
  app.component(MilkdownEditorWrappable.__name, MilkdownEditorWrappable)
}

export {
  version,
  MilkdownEditor,
  MilkdownEditorWrappable,

  install
}
```

**Comment by whoacowboy** [comment]
@jclaveau Thank you that is very helpful. I am having similar issues with scss inside the SFCs.

```
  Vue({ 
    style: {
      preprocessLang: 'scss',
      preprocessOptions: {
        additionalData: `
            @use '${path.resolve(__dirname, '../node_modules/quasar/src/css/variables.sass')}' as *;
        `,
      },
    },
  }),
```

I had to change the `rollupPlugins Vue` section to get it to read the quasar css.

What errors are you getting?
