### ISSUE TITLE
q-tooltip in a q-button with loading attribute produces a console error message

### ISSUE THREAD

**Issue by jimmityglick** [quasarframework/quasar#2210]
q-tooltip in a q-button with loading attribute produces a console error message.

### Software version
Operating System    Linux(4.9.0-6-amd64) - linux/x64
NodeJs                    10.5.0

Global packages
  NPM                      6.1.0
  yarn                       1.7.0
  quasar-cli              0.16.4
  vue-cli                   2.9.6
  cordova                Not installed

Important local packages
  quasar-cli                 0.16.4 
  quasar-framework    0.16.0
  quasar-extras          2.0.2
  vue                          2.5.16 
  vue-router               3.0.1 
  vuex                        3.0.1  
  electron                   Not installed
  electron-packager   Not installed
  electron-builder       Not installed
  @babel/core           7.0.0-beta.49   (Babel compiler core.)
  webpack                 4.9.1  
  webpack-dev-server 3.1.4   
  workbox-webpack-plugin 3.2.0  

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/bm7d9e4w/

### What did you get as the error?

vue.min.js:6 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at o.__hide (https://unpkg.com/quasar-framework@0.16.0/dist/umd/quasar.mat.umd.min.js:6:194725)
    at o.beforeDestroy (https://unpkg.com/quasar-framework@0.16.0/dist/umd/quasar.mat.umd.min.js:6:13973)
    at _t (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:14786)
    at o.un.$destroy (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:32070)
    at destroy (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:23629)
    at w (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:53862)
    at C (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:54046)
    at https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:55540
    at k (https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:55551)
    at https://unpkg.com/vue@2.5.16/dist/vue.min.js:6:55101
### What steps did you take, to get the error?

Click on the "notify" button in the fiddle.

**Comment by jimmityglick** [comment]
Here is a workaround - https://jsfiddle.net/81ajedns/

**Comment by rstoenescu** [comment]
Hi,

Yes, the workaround is needed, due to how QTooltip and Vue works under the covers.
