### ISSUE TITLE
Uncaught TypeError: _this.model.includes is not a function

### ISSUE THREAD

**Issue by j-shade** [quasarframework/quasar#351]
Seems that parsing an Array of Objects to q-table creates an error.

```
quasar.common.js?e3df:6537 Uncaught TypeError: _this.model.includes is not a function
    at eval (eval at <anonymous> (http://localhost:8080/js/app.js:1590:1), <anonymous>:6537:28)
    at Array.map (native)
    at VueComponent.optModel (eval at <anonymous> (http://localhost:8080/js/app.js:1590:1), <anonymous>:6536:27)
    at Watcher.get (eval at <anonymous> (http://localhost:8080/js/app.js:723:1), <anonymous>:2934:27)
    at Watcher.evaluate (eval at <anonymous> (http://localhost:8080/js/app.js:723:1), <anonymous>:3042:21)
    at Proxy.computedGetter (eval at <anonymous> (http://localhost:8080/js/app.js:723:1), <anonymous>:3240:15)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8721)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:8751)
```

I did some digging and 'It seems that Array.includes is not JavaScript specs, and it should be Array.prototype.includes instead, and it is not supported in IE'

https://github.com/aldeed/node-simple-schema/issues/34

Perhaps we require babel-polyfill? anything else i can submit to help?

**Comment by rstoenescu** [comment]
Hi,

It is parts of JS specs: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

Polyfill already included in Quasar. `Array.prototype.includes` it's just how it is injected into Array.
**And optModel is not part of DataTable.**

1. What version of Quasar are you using?
2. Do you have a repo I can take a look with instructions on how to reproduce?

Thanks!

**Comment by j-shade** [comment]
Hi, seems clearing out node cache and reinstalling all packages fixed the issue!

Thankyou for the prompt reply though :)
