### ISSUE TITLE
Can't run build

### ISSUE THREAD

**Issue by boriscy** [quasarframework/quasar#385]
When I run `quasar build` I get this error
```
Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/home/boris/dev/js/acasito-trans/node_modules/webpack/lib/Chunk.js:59:9)
    at /home/boris/dev/js/acasito-trans/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/home/boris/dev/js/acasito-trans/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/home/boris/dev/js/acasito-trans/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/home/boris/dev/js/acasito-trans/node_modules/webpack/lib/Compilation.js:558:8)
    at /home/boris/dev/js/acasito-trans/node_modules/webpack/lib/Compiler.js:474:16
    at /home/boris/dev/js/acasito-trans/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/home/boris/dev/js/acasito-trans/node_modules/webpack/lib/Compilation.js:472:11)
    at processModuleDependencies.err (/home/boris/dev/js/acasito-trans/node_modules/webpack/lib/Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! quasar-app@0.0.1 build: `node build/script.build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quasar-app@0.0.1 build script 'node build/script.build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quasar-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/script.build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quasar-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quasar-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/boris/dev/js/acasito-trans/npm-debug.log
```
This is npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle quasar-app@0.0.1~prebuild: quasar-app@0.0.1
6 silly lifecycle quasar-app@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle quasar-app@0.0.1~build: quasar-app@0.0.1
8 verbose lifecycle quasar-app@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle quasar-app@0.0.1~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/boris/dev/js/acasito-trans/node_modules/.bin:/home/boris/.npm-global/bin:/home/boris/.rvm/gems/ruby-2.3.1/bin:/home/boris/.rvm/gems/ruby-2.3.1@global/bin:/home/boris/.rvm/rubies/ruby-2.3.1/bin:/usr/local/heroku/bin:/home/boris/.kiex/elixirs/elixir-1.4.1/bin:/home/boris/.kiex/bin:~/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/boris/.rvm/bin:/home/boris/.rvm/bin:/home/boris/.npm-packages/bin:/opt/java/jdk1.8.0_121/bin:/home/boris/.rvm/bin
10 verbose lifecycle quasar-app@0.0.1~build: CWD: /home/boris/dev/js/acasito-trans
11 silly lifecycle quasar-app@0.0.1~build: Args: [ '-c', 'node build/script.build.js' ]
12 silly lifecycle quasar-app@0.0.1~build: Returned: code: 1  signal: null
13 info lifecycle quasar-app@0.0.1~build: Failed to exec build script
14 verbose stack Error: quasar-app@0.0.1 build: `node build/script.build.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid quasar-app@0.0.1
16 verbose cwd /home/boris/dev/js/acasito-trans
17 error Linux 4.4.0-21-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error quasar-app@0.0.1 build: `node build/script.build.js`
22 error Exit status 1
23 error Failed at the quasar-app@0.0.1 build script 'node build/script.build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the quasar-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/script.build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs quasar-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls quasar-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

this is my package.json
```js
{
  "name": "quasar-app",
  "version": "0.0.1",
  "description": "A Quasar App",
  "author": "Your Name",
  "scripts": {
    "clean": "node build/script.clean.js",
    "dev": "node build/script.dev.js",
    "build": "node build/script.build.js",
    "lint": "eslint --ext .js,.vue src"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "babel-runtime": "^6.0.0",
    "fastclick": "^1.0.6",
    "material-design-icons": "^3.0.1",
    "moment": "^2.15.0",
    "phoenix": "^1.2.1",
    "quasar-framework": "^0.13.1",
    "roboto-fontface": "^0.6.0",
    "velocity-animate": "^1.2.3",
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.1",
    "vuex-i18n": "^1.3.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.0",
    "babel-core": "^6.0.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "colors": "^1.1.2",
    "connect-history-api-fallback": "^1.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.0",
    "eslint": "^3.0.1",
    "eslint-config-standard": "^6.2.0",
    "eslint-friendly-formatter": "^2.0.5",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-promise": "^3.3.0",
    "eslint-plugin-standard": "^2.0.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.0",
    "json-loader": "^0.5.4",
    "opn": "^4.0.2",
    "postcss-loader": "^1.0.0",
    "progress-bar-webpack-plugin": "^1.9.3",
    "shelljs": "^0.7.0",
    "sinon": "^1.17.7",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.1.1",
    "url-loader": "^0.5.7",
    "vue-loader": "^10.1.2",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.13.2",
    "webpack-merge": "^2.0.0"
  }
}
```

**Comment by rstoenescu** [comment]
`extract-text-webpack-plugin` should at least be `^2.0.0-beta.4`

**Comment by rstoenescu** [comment]
Referencing https://github.com/webpack/webpack/issues/2764
