### ISSUE TITLE
[v1] Quasar initialization problem with test components

### ISSUE THREAD

**Issue by Abuntxa** [quasarframework/quasar#3894]
### Software version
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.15.3

#### Global packages
  NPM - 6.4.1
  yarn - 1.12.3
  @quasar/cli - 1.0.0-beta.4
  cordova - Not installed

#### Important local packages
  quasar - 1.0.0-beta.17 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, PWA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-beta.17 -- Quasar Framework App CLI
  @quasar/extras - 1.1.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.4 -- Official router for Vue.js 2
  vuex - 3.1.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4 -- Babel compiler core.
  webpack - 4.30.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.3.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.2.0 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

#### Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0-beta.22 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing - 1.0.0-rc.5 -- A Quasar App Extension for managing Test Harnesses
### Repository reproducing the problem
[https://github.com/Abuntxa/quasar-testing](https://github.com/Abuntxa/quasar-testing)
It's a repository with the minimal case.
* It's a basic bootstrapped project with the unit testing extension (jest)
* It has been modified src/pages/Index.vue to make use of the plugin localStorage
* There have been added two exactly indentical tests of the component
* Before each test the component to be tested is recreated and destroyed

**Only the first of the 2 tests passes**

### What did you get as the error?

One of the identical tests fails after several vue warnings indicating that the Quasar components are unknown, Below the console output.
```
npm run test:unit

> quasar-testing@0.0.1 test:unit C:\Users\Jon\Desarrollo\quasar-testing
> jest --updateSnapshot

 PASS  test/jest/__tests__/App.spec.js
  ● Console

    console.log test/jest/__tests__/App.spec.js:59
      formattedString 2019 April Apr 16

 FAIL  src/pages/__tests__/Index.spec.js
  ● Console

    console.error node_modules/vue/dist/vue.common.dev.js:630
      [Vue warn]: Unknown custom element: <q-page> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <PageIndex>
             <Root>
    console.error node_modules/vue/dist/vue.common.dev.js:630
      [Vue warn]: Unknown custom element: <q-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <PageIndex>
             <Root>
    console.error node_modules/vue/dist/vue.common.dev.js:630
      [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'localStorage' of undefined"
      
      found in
      
      ---> <PageIndex>
             <Root>
    console.error node_modules/vue/dist/vue.common.dev.js:1893
      TypeError: Cannot read property 'localStorage' of undefined
          at VueComponent.mounted (C:\Users\Jon\Desarrollo\quasar-testing\src\pages\index.vue:579:38)
          at invokeWithErrorHandling (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:1859:57)
          at callHook (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:4210:7)
          at Object.insert (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:3142:7)
          at invokeInsertHook (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:6331:28)
          at VueComponent.patch [as __patch__] (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:6548:5)
          at VueComponent.Vue._update (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:3936:19)
          at VueComponent.updateComponent (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:4057:10)
          at Watcher.get (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:4468:25)
          at new Watcher (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:4457:12)
          at mountComponent (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:4064:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:9034:10)
          at VueComponent.Object.<anonymous>.Vue.$mount (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\vue\dist\vue.common.dev.js:11919:16)
          at mount (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\@vue\test-utils\dist\vue-test-utils.js:8649:21)
          at mountComponent (C:\Users\Jon\Desarrollo\quasar-testing\test\jest\utils\testCommon.js:66:12)
          at mountComponent (C:\Users\Jon\Desarrollo\quasar-testing\test\jest\utils\testCommon.js:40:10)
          at Object.<anonymous> (C:\Users\Jon\Desarrollo\quasar-testing\src\pages\__tests__\Index.spec.js:35:17)
          at Object.asyncJestLifecycle (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:53:37)
          at resolve (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
          at promise.then (C:\Users\Jon\Desarrollo\quasar-testing\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
          at process._tickCallback (internal/process/next_tick.js:68:7)

  ● Dashboard designer page tests › passes the sanity check to see if at least is a Vue instance2 

    TypeError: Cannot read property 'localStorage' of undefined



      at VueComponent.mounted (src/pages/index.vue:579:38)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.common.dev.js:1859:57)
      at callHook (node_modules/vue/dist/vue.common.dev.js:4210:7)
      at Object.insert (node_modules/vue/dist/vue.common.dev.js:3142:7)
      at invokeInsertHook (node_modules/vue/dist/vue.common.dev.js:6331:28)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.common.dev.js:6548:5)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.common.dev.js:3936:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.common.dev.js:4057:10)
      at Watcher.get (node_modules/vue/dist/vue.common.dev.js:4468:25)
      at new Watcher (node_modules/vue/dist/vue.common.dev.js:4457:12)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4064:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.common.dev.js:9034:10)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.common.dev.js:11919:16)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:21)
      at mountComponent (test/jest/utils/testCommon.js:66:12)
      at mountComponent (test/jest/utils/testCommon.js:40:10)
      at Object.<anonymous> (src/pages/__tests__/Index.spec.js:35:17)
```

### What were you expecting?
Both tests passing. The result should be the same wether I decide to share the component across the tests or not.

### What steps did you take, to get the error?
Explained in the repository

**Comment by nothingismagick** [comment]
Hi, please see my comment at your other issue. I would prefer to avoid any changes to core - everything should be instrumentable.

**Comment by Abuntxa** [comment]
I updated the comment in the linked issue

**Comment by rstoenescu** [comment]
Please use quasar-testing ticket only to track this issue.
