### ISSUE TITLE
[Bug] binding.symlink error when wrap cordova

### ISSUE THREAD

**Issue by lyquocnam** [quasarframework/quasar#572]
i tried:
`quasar wrap cordova`
and this bug
```
PS F:\dev\myapp> quasar wrap cordova

? Install Crosswalk WebView plugin for Android Apps (HIGHLY recommended) Yes
Creating a new cordova project.
fs.js:1034
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink '..\dist' -> 'F:\dev\myapp\cordova\www'
    at Object.fs.symlinkSync (fs.js:1034:18)
    at Object.symlink (C:\Users\lyquo\AppData\Roaming\npm\node_modules\quasar-cli\lib\qfs.js:58:13)
    at install (C:\Users\lyquo\AppData\Roaming\npm\node_modules\quasar-cli\bin\wrappers\cordova\install.js:32:11)
    at ChildProcess.callback (C:\Users\lyquo\AppData\Roaming\npm\node_modules\quasar-cli\bin\wrappers\cordova\install.js:82:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

PS F:\dev\myapp>
```

**Comment by rstoenescu** [comment]
Hi,

1. Please use appropriate repo for reporting issues, in this case the Quasar CLI repo.
2. Read `Note for Windows Developers`: http://quasar-framework.org/guide/cordova-wrapper.html#Wrap-your-App
