### ISSUE TITLE
Adding webpack cfg.externals gives strange errors

### ISSUE THREAD

**Issue by vdraceil** [quasarframework/quasar#6460]
I've recently been playing around with amcharts4 and I had it included in my project.
To get rid of the unwanted (for me) dependencies, I added the webpack externals function to **quasar.conf.js**

The aim was to exclude 3 dependencies from being bundled in **vendor.js** - xlsx, canvg, pdfmake

```
build: {
  extendWebpack (cfg) {
    ... 
    cfg.externals = function (context, request, callback) {
      if (/canvg|pdfmake/.test(request)) {
        return callback(null, "commonjs " + request)
      }
      callback()
    }
  }
}
```
With this config, the SSR build (`quasar build -m ssr`) succeeds, but when I serve the ssr code (`DEBUG=true quasar serve dist/ssr`), it results in this strange error

```
Server listening at port 3000

500 on /
TypeError: Cannot read property 'install' of undefined
    at Function.Ai.t.use (server-bundle.js:16:215110)
    at Module.4edf (server-bundle.js:16:747158)
    at i (server-bundle.js:1:194)
    at Object.0 (server-bundle.js:1:1330)
    at i (server-bundle.js:1:194)
    at module.exports.0 (server-bundle.js:1:1291)
    at Object.<anonymous> (server-bundle.js:1:1300)
    at evaluateModule (/home/vdraceil/Workplace/Personal/test/node_modules/vue-server-renderer/build.dev.js:9318:21)
    at /home/vdraceil/Workplace/Personal/test/node_modules/vue-server-renderer/build.dev.js:9376:18
    at new Promise (<anonymous>)
```

Now, if I include xlsx in the regex as in `/xlsx|canvg|pdfmake/`, the build just fails with another strange error (I mean, not giving away much).

![Screenshot_23-Feb-2020_T20-15-05_+07](https://user-images.githubusercontent.com/10086849/75120320-70d47180-56bd-11ea-92dd-cc3d08d709cd.jpg)

Am I doing anything wrong?
Any pointers on how to go about this might help greatly.

**Comment by vdraceil** [comment]
It seems I was trying to forcefully remove/skip the dependencies (which were dynamically imported) by **amcharts**

I'm using the below to forcefully move those packages out of vendor.js
```
build: {
  vendor: {
    remove: [ 'pdfmake', 'canvg', 'xlsx' ]
  }
}
```
For now this works, but those unwanted bundles are now getting prefetched no matter what
