### ISSUE TITLE
ChunkLoadError: Loading chunk xxx failed [docs]

### ISSUE THREAD

**Issue by turigeza** [quasarframework/quasar#6564]
The documentation on the public website dies on me all the time I have to reload the page to get it working again. 

https://quasar.dev/vue-components/tab-panels#Installation

This always happen after I leave the computer and come back after lets say 20 minutes. So when the site goes idle. Or when I don't visit the tab for a while ... It has something to do with not having it active for a while.

MacOS 10.15 
Chrome 80.0.3987.122 (Official Build) (64-bit)

Full console log 
```
color-palette:1 Refused to execute script from 'https://quasar.dev/not-found' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
vendor.47a34429.js:32 ChunkLoadError: Loading chunk 203 failed.
(error: https://quasar.dev/js/203.cd099275.js)
    at n.e (https://quasar.dev/js/runtime.8221b91f.js:1:9989)
    at Array.map (<anonymous>)
    at o (https://quasar.dev/js/app.ecf077ee.js:1:14805)
    at component (https://quasar.dev/js/app.ecf077ee.js:1:66967)
    at https://quasar.dev/js/vendor.47a34429.js:32:16500
    at https://quasar.dev/js/vendor.47a34429.js:32:16750
    at Array.map (<anonymous>)
    at https://quasar.dev/js/vendor.47a34429.js:32:16726
    at Array.map (<anonymous>)
    at ze (https://quasar.dev/js/vendor.47a34429.js:32:16676)
l @ vendor.47a34429.js:32
runtime.8221b91f.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 203 failed.
(error: https://quasar.dev/js/203.cd099275.js)
    at n.e (https://quasar.dev/js/runtime.8221b91f.js:1:9989)
    at Array.map (<anonymous>)
    at o (https://quasar.dev/js/app.ecf077ee.js:1:14805)
    at component (https://quasar.dev/js/app.ecf077ee.js:1:66967)
    at https://quasar.dev/js/vendor.47a34429.js:32:16500
    at https://quasar.dev/js/vendor.47a34429.js:32:16750
    at Array.map (<anonymous>)
    at https://quasar.dev/js/vendor.47a34429.js:32:16726
    at Array.map (<anonymous>)
    at ze (https://quasar.dev/js/vendor.47a34429.js:32:16676)
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.postload.js.map
color-palette:1 Refused to apply style from 'https://quasar.dev/not-found' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
color-palette:1 Refused to apply style from 'https://quasar.dev/not-found' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by turigeza** [comment]
Don't bother looking at it just yet. I suspect it might be a combination of recent chrome updates and / or AdlockPlus extension.  I am going to see if I get the same problems when I disable this extension and let you know.

**Comment by turigeza** [comment]
This seems to happen if one has AdBlockPlus (https://adblockplus.org/) installed on the Chrome. Ever since I disable the plugin this issue didn't happen. 

It happens regardless you have the plugin enable on the site or not. It is enough to have it installed which is what confused me.

**Comment by rstoenescu** [comment]
Thanks for discovering the root cause and sharing it here. Might be useful for others too.
Was sure it's because of an external reason.
