### ISSUE TITLE
quasar not working out of the box, electron-is-dev referencing electron.remote which is undefined

### ISSUE THREAD

**Issue by masteroleary** [quasarframework/quasar#6742]
I get this error
webpack:///./node_modules/electron-is-dev/index.js?:4
const app = electron.app || electron.remote.app;
                                            ^

TypeError: Cannot read property 'app' of undefined
    at eval (webpack:///./node_modules/electron-is-dev/index.js?:4:45)
    at Object../node_modules/electron-is-dev/index.js (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:640:1)
    at __webpack_require__ (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///./node_modules/electron-debug/index.js?:4:15)
    at Object../node_modules/electron-debug/index.js (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:580:1)
    at __webpack_require__ (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///./src-electron/main-process/electron-main.dev.js?:8:1)
    at Object../src-electron/main-process/electron-main.dev.js (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:898:1)
    at __webpack_require__ (/Users/dev/Projects/MeanBot/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///multi_./src-electron/main-process/electron-main.dev.js?:1:18)

 app:spawn Command "/Users/dev/Projects/MeanBot/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron" failed with exit code: 1 +0ms

According to this link the last commenter says:
"I believe electron.remote has been deprecated but it is referenced by the node_modules\electron-is-dev\index.js Please see the following reference.. I recently had to remove electron-is-dev from my project when attempting to test out the latest Electron 10 nightly build. I'm not sure if there is an alternative, but it seems to be a major dependency for this project that has broke."

https://github.com/sindresorhus/electron-is-dev/issues/20#issuecomment-589383829

Steps

1. new project created
2. quasar mode add electron
3. Followed these steps: https://quasar.dev/quasar-cli/cli-documentation/supporting-ts
4. quasar dev -m electron

   
OS: macOS Catalina 10.15.4
Node: 12.16.1
NPM: 6.14.4 
Electron: 8.2.0

**Comment by rstoenescu** [comment]
Hi,

1. Point 3 is not relevant to this issue.
2. I haven't managed to reproduce your issue, even if running the same environment.
3. Even if I could reproduce, this should be reported and fixed upstream as it is out of our control. So please do that and follow the ticket that you highlighted.

**Comment by masteroleary** [comment]
I found that I needed to change "quasar dev -m electron" to "sudo quasar dev -m electron" and run as administrator. Now it works.
