### ISSUE TITLE
yarn global add @quasar/icongenie error

### ISSUE THREAD

**Issue by zhangyongjiang86** [quasarframework/quasar#7081]
yarn global add @quasar/icongenie
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⡀ pngquant-bin                                                                                                                                                                                               [-/3] ⢀ waiting...                                                                                                                                                                                                 error C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\pngquant-bin
Output:
‼ certificate has expired
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by pdanpdan** [comment]
Hello. It looks like you are behind a MitM machine - please make the bug report  to the guis taking care of your computer and network.
