### ISSUE TITLE
js/app.js from Terser. Unexpected line terminator

### ISSUE THREAD

**Issue by trixden** [quasarframework/quasar#7487]
When I run the command:
```
quasar build -m android
```
I get an error:

```
 Converting to long form: -m cordova -T android

 Build mode........ cordova
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v1.9.6
 Debugging......... no
 Publishing........ no
 Packaging mode.... cordova

 App · Reading quasar.conf.js
 App · Generating legacy js code (ES5); use "--modern" param for ES6+
 App · Cleaned build artifact: "/home/trix/Projects/admin/dist/cordova/android"
 App · Generating Webpack entry point
 App · Compiling with Webpack...

 • Compiling:
 └── Cordova ████████████████████ 100% done in 51353 ms


 App · ⚠️  1 error encountered:

js/app.js from Terser
Unexpected line terminator [js/app.js:46415,174]
    at ee (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:19541)
    at m (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:20854)
    at /home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:25148
    at /home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:25627
    at I (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:25568)
    at Object.H [as input] (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:26083)
    at a (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:28003)
    at s (/home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:28057)
    at /home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:43427
    at /home/trix/Projects/admin/node_modules/terser/dist/bundle.min.js:1:28976

 App · ⚠️  [FAIL] Build failed with 1 error. Check log above.
```

The error doesn't explain anything. Is there a solution to this problem? Or maybe it is possible to display the error in more detail?

________________

P.S.

When I run the command:

```
quasar build -m android --debug
```

Everything is ok.

```
Converting to long form: -m cordova -T android

 Build mode........ cordova
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v1.9.6
 Debugging......... enabled
 Publishing........ no
 Packaging mode.... cordova

 App · Reading quasar.conf.js
 App · Generating legacy js code (ES5); use "--modern" param for ES6+
 App · Cleaned build artifact: "/home/trix/Projects/admin/dist/cordova/android"
 App · Generating Webpack entry point
 App · Compiling with Webpack...

 • Compiling:
 └── Cordova ████████████████████ 100% done in 21451 ms


 Build summary for css/js/json (the rest are omitted):
 ╔══════════════════╤════════════╤════════════╗
 ║            Asset │       Size │    Gzipped ║
 ╟──────────────────┼────────────┼────────────╢
 ║ app.81afb7a7.css │  237.60 KB │   36.33 KB ║
 ╟──────────────────┼────────────┼────────────╢
 ║             1.js │   32.61 KB │   11.42 KB ║
 ║           app.js │ 7895.46 KB │ 1946.39 KB ║
 ╚══════════════════╧════════════╧════════════╝
 
 App · Updated Cordova config.xml
 App · Running "cordova build --debug android"

Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/home/trix/Android/Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)

...

BUILD SUCCESSFUL in 33s
42 actionable tasks: 3 executed, 39 up-to-date
Built the following apk(s): 
        /home/trix/Projects/admin/src-cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk

 Build succeeded

 Build mode........ cordova
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v1.9.6
 Debugging......... enabled
 Publishing........ no
 Packaging mode.... cordova
 Modern build...... no (legacy ES5); use "--modern" param for ES6+
 ==================
 Output folder..... /home/trix/Projects/admin/dist/cordova
```

**Comment by pdanpdan** [comment]
please fill the issue template

**Comment by trixden** [comment]
@pdanpdan, i'm sorry. Something strange has happened. I would never delete the issue template.

I find a solution. Terser crashes with an error, when i import a 'jsonwebtoken' package. It was pointless to use it on the frontend.

**Comment by pdanpdan** [comment]
maybe it uses some features that are not supported by terser. I'm glad it got fixed

**Comment by trixden** [comment]
@pdanpdan, can I disable Terser, or replace it with something?

**Comment by pdanpdan** [comment]
I don't think so - try on the discord channel.
But it's strange you use packages written using so low stage proposals.
