### ISSUE TITLE
`quasar test` fails to collect coverage on out-of-the-box setup

### ISSUE THREAD

**Issue by papiro** [quasarframework/quasar#7584]
**Describe the bug**
Running `quasar test` on an out-of-the-box setup fails to collect coverage.

**Codepen/jsFiddle/Codesandbox (required)**
N/A

**To Reproduce**
1. Create a fresh Quasar project via `quasar create`
3. Add testing extension via `quasar ext add @quasar/testing`, and select Jest as unit-testing harness.
4. Run default tests via `quasar test --unit jest`

**Expected behavior**
Runs tests and collects coverage.

**Actual behavior**
Runs tests but fails to collect coverage. Displays following errors:
```
Running coverage on untested files...Failed to collect coverage from /Users/pierrepirault/spysmiles/src/boot/axios.ts
ERROR: /Users/pierrepirault/spysmiles/src/boot/axios.ts: Unexpected token, expected ";" (4:8)

  2 | import { boot } from 'quasar/wrappers'
  3 | 
> 4 | declare module 'vue/types/vue' {
    |         ^
  5 |   interface Vue {
  6 |     $axios: AxiosInstance;
  7 |   }
STACK: SyntaxError: /Users/pierrepirault/spysmiles/src/boot/axios.ts: Unexpected token, expected ";" (4:8)

  2 | import { boot } from 'quasar/wrappers'
  3 | 
> 4 | declare module 'vue/types/vue' {
    |         ^
  5 |   interface Vue {
  6 |     $axios: AxiosInstance;
  7 |   }
    at Parser._raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:756:17)
    at Parser.raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:750:17)
    at Parser.unexpected (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8930:16)
    at Parser.semicolon (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8912:40)
    at Parser.parseExpressionStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11888:10)
    at Parser.parseStatementContent (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11484:19)
    at Parser.parseStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11930:25)
    at Parser.parseBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11916:10)
Failed to collect coverage from /Users/pierrepirault/spysmiles/src/env.d.ts
ERROR: /Users/pierrepirault/spysmiles/src/env.d.ts: Unexpected token, expected ";" (1:8)

> 1 | declare namespace NodeJS {
    |         ^
  2 |   interface ProcessEnv {
  3 |     NODE_ENV: string;
  4 |     VUE_ROUTER_MODE: 'hash' | 'history' | 'abstract' | undefined;
STACK: SyntaxError: /Users/pierrepirault/spysmiles/src/env.d.ts: Unexpected token, expected ";" (1:8)

> 1 | declare namespace NodeJS {
    |         ^
  2 |   interface ProcessEnv {
  3 |     NODE_ENV: string;
  4 |     VUE_ROUTER_MODE: 'hash' | 'history' | 'abstract' | undefined;
    at Parser._raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:756:17)
    at Parser.raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:750:17)
    at Parser.unexpected (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8930:16)
    at Parser.semicolon (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8912:40)
    at Parser.parseExpressionStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11888:10)
    at Parser.parseStatementContent (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11484:19)
    at Parser.parseStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11930:25)
    at Parser.parseBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11916:10)
Failed to collect coverage from /Users/pierrepirault/spysmiles/src/components/models.ts
ERROR: /Users/pierrepirault/spysmiles/src/components/models.ts: Support for the experimental syntax 'flow' isn't currently enabled (1:8):

> 1 | export interface Todo {
    |        ^
  2 |   id: number;
  3 |   content: string;
  4 | }

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
STACK: SyntaxError: /Users/pierrepirault/spysmiles/src/components/models.ts: Support for the experimental syntax 'flow' isn't currently enabled (1:8):

> 1 | export interface Todo {
    |        ^
  2 |   id: number;
  3 |   content: string;
  4 | }

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:756:17)
    at Parser.expectOnePlugin (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8945:18)
    at Parser.isExportDefaultSpecifier (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:12575:16)
    at Parser.maybeParseExportDefaultSpecifier (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:12468:14)
    at Parser.parseExport (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:12421:29)
    at Parser.parseStatementContent (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11454:27)
    at Parser.parseStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11930:25)
    at Parser.parseBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11916:10)
Failed to collect coverage from /Users/pierrepirault/spysmiles/src/shims-vue.d.ts
ERROR: /Users/pierrepirault/spysmiles/src/shims-vue.d.ts: Unexpected token, expected ";" (2:8)

  1 | // Mocks all files ending in `.vue` showing them as plain Vue instances
> 2 | declare module '*.vue' {
    |         ^
  3 |   import Vue from 'vue'
  4 |   export default Vue
  5 | }
STACK: SyntaxError: /Users/pierrepirault/spysmiles/src/shims-vue.d.ts: Unexpected token, expected ";" (2:8)

  1 | // Mocks all files ending in `.vue` showing them as plain Vue instances
> 2 | declare module '*.vue' {
    |         ^
  3 |   import Vue from 'vue'
  4 |   export default Vue
  5 | }
    at Parser._raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:756:17)
    at Parser.raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:750:17)
    at Parser.unexpected (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8930:16)
    at Parser.semicolon (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8912:40)
    at Parser.parseExpressionStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11888:10)
    at Parser.parseStatementContent (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11484:19)
    at Parser.parseStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11930:25)
    at Parser.parseBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11916:10)
Failed to collect coverage from /Users/pierrepirault/spysmiles/src/router/routes.ts
ERROR: /Users/pierrepirault/spysmiles/src/router/routes.ts: Unexpected token (3:12)

  1 | import { RouteConfig } from 'vue-router'
  2 | 
> 3 | const routes: RouteConfig[] = [
    |             ^
  4 |   {
  5 |     path: '/',
  6 |     component: () => import('layouts/MainLayout.vue'),
STACK: SyntaxError: /Users/pierrepirault/spysmiles/src/router/routes.ts: Unexpected token (3:12)

  1 | import { RouteConfig } from 'vue-router'
  2 | 
> 3 | const routes: RouteConfig[] = [
    |             ^
  4 |   {
  5 |     path: '/',
  6 |     component: () => import('layouts/MainLayout.vue'),
    at Parser._raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:756:17)
    at Parser.raise (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:750:17)
    at Parser.unexpected (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:8930:16)
    at Parser.parseVar (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:12018:18)
    at Parser.parseVarStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11823:10)
    at Parser.parseStatementContent (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11415:21)
    at Parser.parseStatement (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11930:25)
    at Parser.parseBlockBody (/Users/pierrepirault/spysmiles/node_modules/@babel/parser/lib/index.js:11916:10)
```

**Platform (please complete the following information):**
OS: MacOS
Node: 12.16.1
NPM: 6.14.7

**Additional context**
This seems to be due to lack of Typescript support somewhere. I can't tell where since the tests run fine. It is only the coverage which fails.

**Comment by IlCallo** [comment]
Hi @papiro can you please check if running `yarn test:unit` provide the same errors?

**Comment by papiro** [comment]
@IlCallo, it does. I noticed that the coverage report is printed to the console and it is only the `*.ts` files which actually use Typescript constructs/keywords which fail to have coverage collected from them.

**Comment by IlCallo** [comment]
Are you using the latest `@quasar/app-extension-testing-unit-jest@beta` package?
TS support for testing harnesses is currently in beta, stable channel doesn't suppot TS codebases

**Comment by papiro** [comment]
getting a 404 on that package

**Comment by IlCallo** [comment]
My fault, it's `@quasar/quasar-app-extension-testing-unit-jest`.

You can try it out via `quasar ext add @quasar/testing-unit-jest@beta`.
Notice you'll need to delete previous Jest-harness related files and folder in order to have them scaffolded anew by the harness installer.

Here's the beta new documentation: https://github.com/quasarframework/quasar-testing/blob/1414bd5f1598795307c469bba76d6588202e22f4/packages/unit-jest/README.md

**Comment by papiro** [comment]
@IlCallo  it worked!

**Comment by hawkeye64** [comment]
@IlCallo @papiro Can this be closed now?
