### ISSUE TITLE
Icongenie throws error with padding > 7, does not pad with padding < 8

### ISSUE THREAD

**Issue by sluedecke** [quasarframework/quasar#7750]
**Describe the bug**
Trying to add a padding to generated icons, but it does nothing

**To Reproduce**
1. Install icongenie globally (`yarn global add @quasar/icongenie`)
2. Generate fresh quasar project (accept all defaults)
3. invoke: `icongenie generate --padding 8,8`

**Expected behavior**
Icons generated with acceptable padding

**LOG**
```
 icongenie generate --padding 8,8

 * ⚠️  No source icon file specified, so using the sample one

 Generating files with the following options:
 ==========================
 Quasar project folder..... /SOMEDIR/tmp/foo/arsta
 Quality level............. 5/12
 Icon source file.......... /SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/samples/icongenie-icon.png
 Icon trimming............. yes
 Icon padding.............. horizontal: 8; vertical: 8
 Background source file.... none
 Assets of................. spa
 Generator filter.......... none
 Svg color................. #1976D2
 Png color................. #fff
 Splashscreen color........ #fff
 Splashscreen icon ratio... 40%
 ==========================

(node:131125) UnhandledPromiseRejectionWarning: Error: Expected positive integer for width but received 0 of type number
    at Object.invalidParameterError (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/node_modules/sharp/lib/is.js:101:10)
    at Sharp.resize (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/node_modules/sharp/lib/resize.js:234:18)
    at getSquareIcon (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/utils/get-square-icon.js:9:7)
    at Object.module.exports [as png] (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/generators/png.js:4:15)
    at /SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/cmd/generate.js:88:31
    at new Promise (<anonymous>)
    at generateFile (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/cmd/generate.js:86:10)
    at /SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/cmd/generate.js:119:34
    at Array.map (<anonymous>)
    at generateFromProfile (/SOMEDIR/.config/yarn/global/node_modules/@quasar/icongenie/lib/cmd/generate.js:119:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:131125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:131125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 * Generated ico:          public/favicon.ico (37.0KB)
 * Generated png:          public/icons/favicon-32x32.png (11.5KB)
 * Generated png:          public/icons/favicon-96x96.png (13.1KB)
 * Generated png:          public/icons/favicon-128x128.png (13.8KB)

```

**Platform (please complete the following information):**
```
$ icongenie 

  Running @quasar/icongenie v2.3.2
```

```
$ quasar info

Operating System - Linux(5.8.7-arch1-1) - linux/x64
NodeJs - 14.9.0

Global packages
  NPM - 5.1.0
  yarn - 1.22.5
  @quasar/cli - 1.1.0
  @quasar/icongenie - 2.3.2
  cordova - You have been opted out of telemetry. To change this, run: cordova telemetry on.
9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.13.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 2.0.9 -- Quasar Framework local CLI
  @quasar/extras - 1.9.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 2.6.12 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.2.0 -- Official router for Vue.js 2
  vuex - 3.5.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.11.6 -- Babel compiler core.
  webpack - 4.44.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.11.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks
  typescript - 3.9.5 -- TypeScript is a language for application scale JavaScript development

Quasar App Extensions
  *None installed*
```

**Comment by rstoenescu** [comment]
There is a required favicon of 16x16px. Applying a padding of at least 8px (2x8=16) would mean you'd be left with only the padding :)

Regardless, padding is now dropped if it exceeds the target's dimensions. And a nice warning about this is shown in the console. Will be available in v2.3.3.
