### ISSUE TITLE
Error: Cannot find module 'quasar-ssr'

### ISSUE THREAD

**Issue by gokaybiz** [quasarframework/quasar#7787]
**Describe the bug**
missing package

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
>quasar mode add ssr
>cd src-ssr
>node index
See error in **Additional context**

**Platform (please complete the following information):**
OS: arch linux
Node: 14.3.0
NPM: 6.14.5

**Additional context**
```
[pjskyr@dev-pjskyr src-ssr]$ node index.js 
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'quasar-ssr'
Require stack:
- /opt/lampp/htdocs/nodejs/quasar/prj/src-ssr/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/opt/lampp/htdocs/nodejs/quasar/prj/src-ssr/index.js:17:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/lampp/htdocs/nodejs/quasar/prj/src-ssr/index.js' ]
}
```

**Comment by pdanpdan** [comment]
Hello. Please read the documentation on how to use quasar. Please use the forum or the discord channel for help requests.
