### ISSUE TITLE
@quasar/app 2.1.1 raised a Error that is Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by baryon** [quasarframework/quasar#7924]
**Describe the bug**
my project build with electron and quasar.

@quasar/app 2.1.0 works.

when upgrade, raised a Error that is Invalid left-hand side in assignment

```
App threw an error during load
SyntaxError: Invalid left-hand side in assignment
    at Object../node_modules/debug/src/node.js (/Users/xxx/.quasar/electron/electron-main.js:4145:1)
    at __webpack_require__ (/Users/xxx/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///./node_modules/debug/src/index.js?:9:19)
    at Object../node_modules/debug/src/index.js (/Users/xxx/.quasar/electron/electron-main.js:4134:1)
    at __webpack_require__ (/Users/xxx/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///./node_modules/electron-localshortcut/index.js?:6:16)
    at Object../node_modules/electron-localshortcut/index.js (/Users/xxx/.quasar/electron/electron-main.js:4263:1)
    at __webpack_require__ (/Users/xxx/.quasar/electron/electron-main.js:21:30)
    at eval (webpack:///./node_modules/electron-debug/index.js?:3:23)
    at Object../node_modules/electron-debug/index.js (/Users/xxx/.quasar/electron/electron-main.js:4180:1)
```

**Platform (please complete the following information):**
OS: Darwin x64 19.6.0
Node: 12.18.3
NPM: 6.14.8
Yarn: 1.22.4
Electron: 10.1.4

**Comment by hawkeye64** [comment]
@baryon You probably also updated your eslint. I doin't have a line 4145 in my `.quasar/electron/electron-main.js`. Can you kindly post your `src-electron/main-process/electron-main.js`.
Closing this for now as I suspect user error, but will reopen if valid once you post the requested data.

**Comment by fprijate** [comment]
The same error is on 
platform: Win64
Node: v14.14
Electron: 10.1.4
@quasar/app": "^2.1.2

But It works with @quasar/app": "^2.1.1
It also works as SPA

**Comment by hawkeye64** [comment]
@fprijate I need to know what part of the code it is complaining about

**Comment by fprijate** [comment]
I just opened a new isue, where everything is explained
