### ISSUE TITLE
QUploader component does not work on capacitor android 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#8648]
have tested with many refresh project same issue both on real device and emulators 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.myapp, PID: 10587
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2099529143, result=0, data=null} to activity {app.myapp/app.myapp.MainActivity}: java.lang.IllegalStateException: showFileChooser result was already called
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: showFileChooser result was already called
        at xs.onReceiveValue(PG:4)
        at com.getcapacitor.BridgeWebChromeClient.lambda$showFilePicker$15(BridgeWebChromeClient.java:434)
        at com.getcapacitor.-$$Lambda$BridgeWebChromeClient$K2q_hX7VVU3kdrpTHIyaUpWfpEc.onActivityResult(Unknown Source:2)
        at com.getcapacitor.BridgeWebChromeClient.lambda$new$1$BridgeWebChromeClient(BridgeWebChromeClient.java:77)
        at com.getcapacitor.-$$Lambda$BridgeWebChromeClient$nK4HrLIPc8JbAwJyF2CGTpDio8A.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:362)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:322)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:634)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:217)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
   
```

**Comment by diadal** [comment]
is there anyway to fix this

**Comment by diadal** [comment]
after debuging  `BridgeWebChromeClient` i find out that using `QUploader` `accept=".jpg, .png, .jpeg"` is the couse of the issue so i change to `accept="image/jpg, image/png, image/jpeg"` `QUploader` work find
