### ISSUE TITLE
Default Jest setup fails to run

### ISSUE THREAD

**Issue by speasley** [quasarframework/quasar#8671]
When running Quasar v2.0.0-beta.10 after adding Jest with `quasar ext add @quasar/testing-unit-jest`, running the default test suite throws an error:

```
yarn run v1.22.10
$ jest --updateSnapshot
 FAIL  test/jest/__tests__/App.spec.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module vue mapped as:
    vue/dist/vue.common.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^vue$/": "vue/dist/vue.common.js"
      },
      "resolver": undefined
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:551:17)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:11)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.393 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

OS: macOS 10.15.7
Node: v12.20.0
Yarn: 1.22.10

**Comment by Smrtnyk** [comment]
Didn't even know quasar beta has testing extension
Are you sure that the extension is compatible with v2 beta?

**Comment by IlCallo** [comment]
As noted by @Smrtnyk, AEs aren't yet Qv2 compatible, the issue is tracked here already: https://github.com/quasarframework/quasar-testing/issues/159
