### ISSUE TITLE
Support JSX/TSX

### ISSUE THREAD

**Issue by panhezeng** [quasarframework/quasar#8690]
quasar create quasar-tsx --branch next

module.exports = {
  presets: [
    '@quasar/babel-preset-app',
  ], 
  plugins: ['@vue/babel-plugin-jsx']
}

https://github.com/vuejs/jsx-next

**Comment by Smrtnyk** [comment]
tsx is not supported in quasar yet unfortunately afaik
I guess there are more prio issues to be done currently
Seems like the components go through something else first before coming to the jsx transpiler and it breaks

Would be nice if this gets supported at some time because it has much cleaner syntax than render functions

**Comment by joaomede** [comment]
@panhezeng Im using TSX in "3.0.0-beta.10" Quasar/App, your babel.config.js is correct, but you need config "babel loader" on "quasar.conf.js";

see my config on "extendWebpack"

```js
      extendWebpack (cfg, { isServer, isClient }) {
        cfg.resolve.alias = {
          ...cfg.resolve.alias,
          vue$: 'vue/dist/vue.esm-bundler.js',
          '@': path.resolve(__dirname, './')
        }
        cfg.resolve.extensions.push('.tsx')
        cfg.module.rules.push({
          test: /\.ts(x?)$/,
          exclude: /(node_modules|quasar)/,
          use: [
            {
              loader: 'babel-loader',
              options: { babelrc: true }
            },
            {
              loader: 'ts-loader',
              options: {
                appendTsSuffixTo: [/\.vue$/],
                transpileOnly: true

              }
            }
          ]
        })
        cfg.module.rules.push({
          test: /\.tsx$/,
          exclude: /(node_modules|quasar)/,
          use: [
            {
              loader: 'babel-loader'
            },
            {
              loader: 'ts-loader',
              options: {
                appendTsSuffixTo: [/\.vue$/],
                transpileOnly: true
              }
            }
          ]
        })
      }
    },

```
in addition to this configuration, you need to define the suppertTS
```js
    supportTS: {
      tsCheckerConfig: {
        eslint: {
          enabled: false,
          files: './src/**/*.vue'
        }
      }
    },
```

**Comment by Smrtnyk** [comment]
@joaomede Is q-dialog working for you in tsx?
For me it is broken and always shown in the component as a visible block element

**Comment by Smrtnyk** [comment]
Actually I get for all quasar components a warning that it cannot resolve when used in tsx file

**Comment by IlCallo** [comment]
@joaomede did you manage to make JSX/TSX work with Quasar?
Do you have some time to contribute with a PR adding it out of the box?

**Comment by joaomede** [comment]
@IlCallo Yes man, I Will Do

**Comment by IlCallo** [comment]
Thanks :)
Reach me out on Discord if you need any assistance

**Comment by joaomede** [comment]
Hello Guys, @IlCallo, @Smrtnyk, @panhezeng.
I published a working example of "Quasar  v2 / Vue 3" with official plugin "https://github.com/vuejs/jsx-next".

https://github.com/joaomede/Quasar-Vue3-TSX
https://codesandbox.io/s/github/joaomede/Quasar-Vue3-TSX

Comments:
* quasar v2 components are not returning JSX/TSX types, to solve this the "any" type needs to be pegged after import, eg:
```tsx
import { defineComponent } from 'vue'
import { QBtn as Btn } from 'quasar'

const Component = defineComponent({
  setup() {
    const QBtn = Btn as any
    return () => <QBtn label={'label here'}>
  }
})
```

**Comment by Smrtnyk** [comment]
you can add this to quasar.conf
```
sourceFiles: {
            rootComponent: "src/App",
        },
```
and rename your `App.vue` to `App.tsx`

**Comment by Smrtnyk** [comment]
I don't have the type issues with quasar components when I use kebab-case naming for them for some reason

**Comment by joaomede** [comment]
@Smrtnyk, updated my example https://codesandbox.io/s/github/joaomede/Quasar-Vue3-TSX, changing the file "app.vue" to "app.tsx", thanks for that.

about this:
> I don't have the type issues with quasar components when I use kebab-case naming for them for some reason

* The configuration expects this type:
![Captura de tela de 2021-08-10 20-00-14](https://user-images.githubusercontent.com/49351989/128945778-3f731e3e-286f-4d5f-bedc-aecfc26b713e.png)
* however, quasar components return this type:
![Captura de tela de 2021-08-10 20-00-20](https://user-images.githubusercontent.com/49351989/128945804-9fd91717-ecef-4ff2-9403-4104233e4b1f.png)

Therefore, the error will always appear; when you use kebeb-case, the configuration assumes that you are using regular html, since in the quasar configuration you defined the components.

**Comment by IlCallo** [comment]
@joaomede how can I return interfaces which are both TSX compatible AND retain existing behaviour (to describe the component public API)?

**Comment by joaomede** [comment]
I understand that the "hDir" function renders correctly but returns the "unexpected" types, I will fork the project to better understand this utility (hDir).

ref: https://github.com/quasarframework/quasar/blob/78df1f4939936fdbf591d90addf950a8f42e665b/ui/src/utils/private/render.js#L43

**Comment by joaomede** [comment]
@IlCallo,
I believe that's the problem here, the project generates types, overlapping the originals,
https://github.com/quasarframework/quasar/blob/918af69abb4e855f0848cd699b0413fed65e51e2/ui/build/build.types.js#L311
I believe this needs to be revised as the original types returned by the components work correctly.

**Comment by joaomede** [comment]
![Captura de tela de 2021-08-12 11-17-26](https://user-images.githubusercontent.com/49351989/129213077-e4719a8d-67d5-4c1e-952f-84b0cad755f0.png)
the exports types is all correct, the problem is on replaced types, in https://github.com/quasarframework/quasar/blob/918af69abb4e855f0848cd699b0413fed65e51e2/ui/build/build.types.js#L311

**Comment by IlCallo** [comment]
Interesting...
Since the naming convention holds with interface and file name, I should be able to just import the type from the file itself for all components, will check what I can do with it

**Comment by joaomede** [comment]
@IlCallo, I generated an type expected by JSX, including the JSDoc comments from the props are working.

```tsx
import { LooseDictionary, QBtn as Button } from 'quasar'
import { defineComponent, DefineComponent, ComponentOptionsMixin, EmitsOptions, AllowedComponentProps, VNodeProps, ComponentCustomProps } from 'vue'

export type PublicProps = VNodeProps & AllowedComponentProps & ComponentCustomProps

type NewType = DefineComponent<{}, () => JSX.Element, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, EmitsOptions, string, PublicProps, Readonly<{} & {}>, {
    /**
     * Size in CSS units, including unit name or standard size name (xs|sm|md|lg|xl)
     */
     size? : string
     /**
      * Define the button HTML DOM type
      */
     type? : 'a' | 'submit' | 'button' | 'reset'
     /**
      * Equivalent to Vue Router <router-link> 'to' property
      */
     to? : string | LooseDictionary
     /**
      * Equivalent to Vue Router <router-link> 'replace' property
      */
     replace? : boolean
     /**
      * Equivalent to Vue Router <router-link> 'append' property
      */
     append? : boolean
     /**
      * The text that will be shown on the button
      */
     label? : string | number
     /**
      * Icon name following Quasar convention; Make sure you have the icon library installed unless you are using 'img:' prefix
      */
     icon? : string
     /**
      * Icon name following Quasar convention; Make sure you have the icon library installed unless you are using 'img:' prefix
      */
     iconRight? : string
     /**
      * Use 'outline' design
      */
     outline? : boolean
     /**
      * Use 'flat' design
      */
     flat? : boolean
     /**
      * Remove shadow
      */
     unelevated? : boolean
     /**
      * Applies a more prominent border-radius for a squared shape button
      */
     rounded? : boolean
     /**
      * Use 'push' design
      */
     push? : boolean
     /**
      * Applies a glossy effect
      */
     glossy? : boolean
     /**
      * Makes button size and shape to fit a Floating Action Button
      */
     fab? : boolean
     /**
      * Makes button size and shape to fit a small Floating Action Button
      */
     fabMini? : boolean
     /**
      * Apply custom padding (vertical [horizontal]); Size in CSS units, including unit name or standard size name (none|xs|sm|md|lg|xl); Also removes the min width and height when set
      */
     padding? : string
     /**
      * Color name for component from the Quasar Color Palette
      */
     color? : string
     /**
      * Overrides text color (if needed); Color name from the Quasar Color Palette
      */
     textColor? : string
     /**
      * Avoid turning label text into caps (which happens by default)
      */
     noCaps? : boolean
     /**
      * Avoid label text wrapping
      */
     noWrap? : boolean
     /**
      * Dense mode; occupies less space
      */
     dense? : boolean
     /**
      * Configure material ripple (disable it by setting it to 'false' or supply a config object)
      */
     ripple? : boolean | LooseDictionary
     /**
      * Tabindex HTML attribute value
      */
     tabindex? : number | string
     /**
      * Label or content alignment
      */
     align? : 'left' | 'right' | 'center' | 'around' | 'between' | 'evenly'
     /**
      * Stack icon and label vertically instead of on same line (like it is by default)
      */
     stack? : boolean
     /**
      * When used on flexbox parent, button will stretch to parent's height
      */
     stretch? : boolean
     /**
      * Put button into loading state (displays a QSpinner -- can be overridden by using a 'loading' slot)
      */
     loading? : boolean
     /**
      * Put component in disabled mode
      */
     disable? : boolean
     /**
      * Makes a circle shaped button
      */
     round? : boolean
     /**
      * Percentage (0.0 < x < 100.0); To be used along 'loading' prop; Display a progress bar on the background
      */
     percentage? : number
     /**
      * Progress bar on the background should have dark color; To be used along with 'percentage' and 'loading' props
      */
     darkPercentage? : boolean
     /**
      * Emulate click on QBtn
      * @param evt JS event object
      */
     click (evt? : LooseDictionary): void
 }>

const QBtn = Button as any as NewType

export default defineComponent({
  setup () {
    return () => (
      <QBtn label={'Working!!!'}></QBtn>
    )
  }
})

```

**Comment by IlCallo** [comment]
What's `Readonly<{} & {}>` for?

**Comment by joaomede** [comment]
I believe they need to receive similar values ​​as props, however, it will serve for "single-file.vue" intellisense, but this needs to be validated better.

**Comment by joaomede** [comment]
original declare from vue https://github.com/vuejs/vue-next/blob/f258f5d2c2774eb2a2c2e4a0ac235b23d0cf9968/packages/runtime-core/src/apiDefineComponent.ts
```ts
export type PublicProps = VNodeProps &
  AllowedComponentProps &
  ComponentCustomProps

export type DefineComponent<
  PropsOrPropOptions = {},
  RawBindings = {},
  D = {},
  C extends ComputedOptions = ComputedOptions,
  M extends MethodOptions = MethodOptions,
  Mixin extends ComponentOptionsMixin = ComponentOptionsMixin,
  Extends extends ComponentOptionsMixin = ComponentOptionsMixin,
  E extends EmitsOptions = Record<string, any>,
  EE extends string = string,
  PP = PublicProps,
  Props = Readonly<ExtractPropTypes<PropsOrPropOptions>> & EmitsToProps<E>,
  Defaults = ExtractDefaultPropTypes<PropsOrPropOptions>
> = ComponentPublicInstanceConstructor<
  CreateComponentPublicInstance<
    Props,
    RawBindings,
    D,
    C,
    M,
    Mixin,
    Extends,
    E,
    PP & Props,
    Defaults,
    true
  > &
    Props
> &
  ComponentOptionsBase<
    Props,
    RawBindings,
    D,
    C,
    M,
    Mixin,
    Extends,
    E,
    EE,
    Defaults
  > &
  PP
```

**Comment by IlCallo** [comment]
Meanwhile, I found a way to infer the `DefineComponent` type from the JS file and generate it as a TS definition, but since we're using render functions seems like there's no way to automatically infer the public API defined via `expose()`.

Also note there's this change pending in dev branch: https://github.com/quasarframework/quasar/commit/918af69abb4e855f0848cd699b0413fed65e51e2

Can you try if patching `ComponentConstructor` helper type in some way can help us get TSX support?
I performed that changeto get full inference into Vue Test Utils, but is still unreleased

To test it, you should clone quasar repo locally, enter `ui` folder, run `yarn install`, then `yarn build` , then `rm -rf node_modules` (this is important) and finally install the local dependency into your project with `yarn add <quasar package folder>/ui`

**Comment by ghost** [comment]
@IlCallo, you branch, https://github.com/quasarframework/quasar/commit/918af69abb4e855f0848cd699b0413fed65e51e2 solved the problem partially, lint stopped complaining, however, the component is only exposing 2 keys, they are; "key" and "ref", the declared props are not found yet.
![Captura de tela de 2021-08-13 11-59-04](https://user-images.githubusercontent.com/64478189/129376853-370409e7-792d-4520-974d-daca90668944.png)

**Comment by IlCallo** [comment]
Yep, that's the same problem I reached right now in today experiments branch [here](https://github.com/IlCallo/quasar/tree/automatically-infer-components-types)

Apparently there's no way to infer stuff exposed via `expose`.
I found a way to extract props from inferred `DefineComponent` interface doing `Parameters<(typeof QAjaxBar)['setup'][0]>` (`QAjaxBar` is the type generated starting from the JS file), so if you only need the props we can expore a bit more on that side.

Consider that we need to fix many problems and add JS annotations to get acceptable inferred types, I only did a small experimento on QAjaxBar today

---

> the declared props are not found yet

That's why I told you to tinker a bit with `ComponentConstructor` helper, maybe you can use existing docs-generated interfaces to add something there, even if I guess you'll then lose distinction between props, methods, etc and break VTU extraction in some way 🤔

**Comment by IlCallo** [comment]
I got in touch with Vue Core team, an advanced guide to Vue interfaces should be in the works, as well as a refactor of TS classes to make them more easy to use by library authors. They'll export a JSX compatible interface for components too, so let's cross fingers 🤞🏻

**Comment by mrBrownys** [comment]
any updates? JSX/TSX works with Vite, but types not provide class and style attributes.

**Comment by IlCallo** [comment]
Seems like Vue team on this regard stopped due to the major docs rewrite they're doing
Pinged them to get some info

Last time I heard them they told me it's possible to use `RenderComponent` interface to declare a JSX-compatible component, but that interface doesn't seem exist anymore

**Comment by darkevilmac** [comment]
I'd definitely be interested in having this supported by default with the CLI, I can get by using the render methods for now but having JSX definitely helps for readability in certain cases.

**Comment by tony-gm** [comment]
> any updates? JSX/TSX works with Vite, but types not provide class and style attributes.

Does this class and style attributes already solved?

**Comment by LiamKarlMitchell** [comment]
Is there a proper fix for this that retains the types?
Trying to use tsx with quasar components, can't define a click handler for QBtn as click event is not a property for some reason.
https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by septatrix** [comment]
Allowing JSX/TSX for newly authored components and slowly transition existing components to use it would be huge and make contributing a lot easier. SFCs would help similarly though the switch from render functions to JSX is a lot simpler and makes it easy to adopt.

There have been several instances where I wanted to contribute (mostly small stuff) but was deterred by the need to manually write render functions.

**Comment by IlCallo** [comment]
We don't plan to convert Quasar components to JSX/TSX or SFC, this issue is about supporting JSX/TSX into userland
We need the flexibility, and thus complexity, of render functions to write components optimized for performance

**Comment by septatrix** [comment]
> We need the flexibility, and thus complexity, of render functions to write components optimized for performance

JSX is basically only syntactic sugar for render functions. While I can understand that certain control is required which SFC may not offer (though several other frameworks get away with it with decent performance), in my experience JSX/TSX has no disadvantage over manual render functions. Instead, it results in higher productivity (in my experience) and makes it easier to contribute as one does not have to learn how render functions work.

**Comment by IlCallo** [comment]
I can understand your point and I can understand if you feel more productive using JSX/TSX, but pretty much the whole Quasar core team and Vue ecosystem don't
It's way more probably for us to convert some components to SFC where possible, which at least would provide some minor performance gains, than to JSX/TSX

**Comment by rajeshtva** [comment]
can anyone point me to right direction on how can i integrate jsx/tsx into **quasar vite cli** generated app? I think [this comment](https://github.com/quasarframework/quasar/issues/8690#issuecomment-896361072) is for webpack-cli generate app. also, i tried to work on the fork of sandbox, it doesn't seem simple to integrate a normal single `.vue` file. plus i want to use ".tsx" syntax in `.vue` files as well.  In the forked sandbox, every component is converted into `.tsx` file.  My point is that if i have to create a single file for writing two-line component. then there is no point of using `.tsx/.jsx`  my main project is a **regular quasar project**. 

This is the sandbox link https://codesandbox.io/s/vue-3-quasar-vite-cli-setup-k5ztxs?file=/src/pages/Index.tsx

**Comment by rajeshtva** [comment]
I also tried to manually integrate `.tsx/.jsx` into my project through `@vue/babel-plugin-jsx` package by adding this into `quasar.config.js > build > vitePlugins` section like 
```
  vitePlugins: [
        [
          '@intlify/vite-plugin-vue-i18n',
          {
            include: path.resolve(__dirname, './src/i18n/**'),
          },
        ],
        ['@vue/babel-plugin-jsx', {}],
        // [require('@vitejs/plugin-vue-jsx').default, {}],
      ],
```

not sure, if it worked. but i do see `eslint` issue in the page where i am using `.jsx/.tsx`. 
![Screenshot from 2023-05-10 15-26-40](https://github.com/quasarframework/quasar/assets/41513422/17e945e9-2e58-4d28-aaf4-abd0d08d6129)

this is the code in the page.
```
<template>
  <q-page class="q-mx-md-md q-mx-xs-sm">
    <div class="container q-mx-auto">
      <HelloWorld />
    </div>
  </q-page>
</template>

<script setup lang="tsx">
const HelloWorld = () => <><div>Hello world.</div></>


</script>

```
**how can i configure `eslint` to recognize `.jsx` syntax.?**

**Comment by IlCallo** [comment]
AFAIK Vite supports JSX/TSX out of the box
If you need to use them into Vue files, you should just need [@vitejs/plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx)

Not sure if ESLint needs particular plugins to be able to parse JSX/TSX

**Comment by DaleMckeown** [comment]
Just wondering if anyone had a solution to the PascalCase types when using JSX/TSX? We've had to change to JSX and our projects are now awash with type errors.

![image](https://github.com/quasarframework/quasar/assets/1249673/9fa08a94-1dd4-4a72-83a8-41863b4ce300)

**Comment by aetherchase** [comment]
worked for me
`vitePlugins: [['@vitejs/plugin-vue-jsx', {}]],
`
in `quasar.config.js > build`

**Comment by DaleMckeown** [comment]
Further issues with JSX/TSX support.

When using certain imports from Quasar, during `quasar build` I get the following error:

```
App •  WAIT  • Compiling of PWA UI with Vite in progress...
[vite:quasar:script] Unknown import from Quasar: QEditorCommand
file: G:/Git/Gateway-Quasar/Gateway-UI/src/App.tsx
G:\Git\Gateway-Quasar\Gateway-UI\node_modules\quasar\dist\transforms\import-transformation.js:6
    throw new Error('Unknown import from Quasar: ' + importName)
          ^
Error: Unknown import from Quasar: QEditorCommand
    at module.exports [as default] (G:\Git\Gateway-Quasar\Gateway-UI\node_modules\quasar\dist\transforms\import-transformation.js:6:11)
    at G:\Git\Gateway-Quasar\Gateway-UI\node_modules\@quasar\vite-plugin\dist\index.cjs:101:87
    at Array.map (<anonymous>)
    at G:\Git\Gateway-Quasar\Gateway-UI\node_modules\@quasar\vite-plugin\dist\index.cjs:85:8
    at String.replace (<anonymous>)
    at mapQuasarImports (G:\Git\Gateway-Quasar\Gateway-UI\node_modules\@quasar\vite-plugin\dist\index.cjs:81:15)
    at Object.transform (G:\Git\Gateway-Quasar\Gateway-UI\node_modules\@quasar\vite-plugin\dist\index.cjs:437:17)
    at G:\Git\Gateway-Quasar\Gateway-UI\node_modules\rollup\dist\shared\rollup.js:22826:37 {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:quasar:script',
  hook: 'transform',
  id: 'G:/Git/Gateway-Quasar/Gateway-UI/src/App.tsx',
  watchFiles: [
```

This happens for a number of interfaces, some I can confirm are:
- QEditorCommand
- QTableProps
- QTableSlots
- QTableColumns

There are likely many, many more.

~~I think this really highlights being able to upgrade to more recent versions of `@vitejs/plugin-vue-jsx`, which is not currently possible as they have peer dependencies on later versions of Vite, which Quasar does not yet support.~~

Scratch this, I've put the workarounds in place to use Vite 4.5.0 and  @vitejs/plugin-vue-jsx 3.0.2 and it errors with the same issue.

It must be something else causing the interfaces to not be exported.

edit: 

This only happens in .tsx files and not in .ts files.

**Comment by DaleMckeown** [comment]
It appears that the issue is with some kind of transformation happening on the interfaces.

The only way I can think or resolving this is to re-export the interfaces/types in ts files to avoid such transformation.

`export type { QTableColumn as QTableColumnProxy } from 'quasar';`

usage in components:

```
import QTableColumnProxy from '/Types/QTableColumnProxy';
```
I've appended the name with `Proxy` for clarity.

**Comment by zhennann** [comment]
Worked for me:

1. install plugin-vue-jsx
``` bash
$ pnpm add -d @vitejs/plugin-vue-jsx
```

2. quasar.config.ts
``` js
vitePlugins: [
  ['@vitejs/plugin-vue-jsx', {}],
]
```

3. tsconfig.json
``` json
"compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "vue",  // important
},
```

**Comment by Tenrys** [comment]
On Nuxt 3, which has support for JSX/TSX out of the box, with those same above configuration settings in tsconfig.json, I still run into issues trying to use Quasar components with JSX.

![image](https://github.com/quasarframework/quasar/assets/3979239/3f92db24-837d-47e7-b34e-e0df7cf693be)
```
Type '{ class: string; key: any; to: any; disable: any; }' is not assignable to type 'IntrinsicAttributes & { to?: any; exact?: boolean | undefined; replace?: boolean | undefined; activeClass?: string | undefined; exactActiveClass?: string | undefined; ... 12 more ...; onClick?: ((evt: Event, go?: ((opts?: { ...; } | undefined) => Promise<...>) | undefined) => void) | undefined; } & QItemProps'.
  Property 'class' does not exist on type 'IntrinsicAttributes & { to?: any; exact?: boolean | undefined; replace?: boolean | undefined; activeClass?: string | undefined; exactActiveClass?: string | undefined; ... 12 more ...; onClick?: ((evt: Event, go?: ((opts?: { ...; } | undefined) => Promise<...>) | undefined) => void) | undefined; } & QItemProps'.
```

This is the solution I have to come up with for now.

![image](https://github.com/quasarframework/quasar/assets/3979239/02ef6ed9-5589-47d7-8f7f-b3e8f86fddb0)

Same goes for the `style` attribute.

**Comment by jarofbilly** [comment]
@Tenrys we had this issue as well. Try adding this to your `env.d.ts`:

`declare global {
    namespace JSX {
        interface IntrinsicAttributes {
            [name: string]: any
        }
    }
}`

Also, register the global Vue JSX namespace. We added this in `quasar.d.ts`:
`/// <reference types="vue/jsx"/>`

This seems to allow any attributes to be added to Quasar components like class, style etc. whilst keeping autocomplete for component props.
![image](https://github.com/quasarframework/quasar/assets/60233676/a0b532c4-9fba-4eb2-bb75-f8aadd46fb66)

**Comment by hariprasadiit** [comment]
I had issue where typescript was complaining about missing `class`, `style` and other `HTMLAttributes`. I just patched the `vue/jsx-runtime/index.d.ts` file using [patch-package](https://www.npmjs.com/package/patch-package)

`IntrinsicAttributes` should also extend `HTMLAttributes` to access all HTML attributes on a JSX element

`vue/jsx-runtime/index.d.ts` file after patching

```ts
/* eslint-disable @typescript-eslint/prefer-ts-expect-error */
import type { HTMLAttributes, NativeElements, ReservedProps, VNode } from '@vue/runtime-dom'

/**
 * JSX namespace for usage with @jsxImportsSource directive
 * when ts compilerOptions.jsx is 'react-jsx' or 'react-jsxdev'
 * https://www.typescriptlang.org/tsconfig#jsxImportSource
 */
export { h as jsx, h as jsxDEV, Fragment } from '@vue/runtime-dom'

export namespace JSX {
  export interface Element extends VNode {}
  export interface ElementClass {
    $props: {}
  }
  export interface ElementAttributesProperty {
    $props: {}
  }
  export interface IntrinsicElements extends NativeElements {
    // allow arbitrary elements
    // @ts-ignore suppress ts:2374 = Duplicate string index signature.
    [name: string]: any
  }
  export interface IntrinsicAttributes extends ReservedProps, HTMLAttributes {} // added HTMLAttributes here which is needed
}

```

**Comment by Yamadetta** [comment]
@hariprasadiit 
This can be done much more easily without patching, by creating a d.ts file with the following content:
```ts
import 'vue/jsx-runtime'
import type { HTMLAttributes } from 'vue'

declare module 'vue/jsx-runtime' {
    namespace JSX {
        interface IntrinsicAttributes extends HTMLAttributes {}
    }
}

```

**Comment by rstoenescu** [comment]
Implemented on `dev`, shipping in **Quasar UI v2.26** and **@quasar/app-vite v3.8**.

Two separate things were missing. Both are in now.

**1. The build side** (932fe47a005200a21588e92f618c5fca7040fdd8): a new opt-in `quasar.config file > build > vueJsx` option.

```js
build: {
  vueJsx: true
}
```

That is all that is needed, with no extra dependency. Vite compiles the JSX/TSX itself; the option points it at Vue's JSX runtime (instead of the React one it assumes by default) and adds the matching `jsx` / `jsxImportSource` to the generated `.quasar/tsconfig.json`. It covers `.jsx` / `.tsx` files and `<script lang="jsx|tsx">` blocks inside `.vue` files, in every mode (SPA, SSR, SSG, PWA, BEX, ...).

Should you want the Vue specific JSX sugar (`v-model`, `v-show`, `v-slots`), set the option to `"preserve"` and add [@vitejs/plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx) to `build.vitePlugins`, which then takes over the transformation.

**2. The type side** (04797c7c23fe8f7477941c43da51ab391de40994): Quasar components rejected `class`, `style`, `key` and `ref` in JSX/TSX. That is the complaint from several comments above, and the reason for the `IntrinsicAttributes` and `vue/jsx-runtime` patches circulating in this thread. `ComponentConstructor` (the type of every exported component) now carries Vue's `PublicProps`, so props, events (`onClick`, `onUpdate:modelValue`, ...) and those universal props all type-check. No `as any` casts, no patched packages, no hand-written interfaces.

Docs: https://v2.quasar.dev/quasar-cli-vite/handling-vite#jsx-tsx (goes live with the release).

To be explicit about the scope, as stated earlier in this thread: this is about writing **your own** components with JSX/TSX. Quasar's own components stay on render functions.

Closing as completed.
