### ISSUE TITLE
Expect Apple M1 support for electron.

### ISSUE THREAD

**Issue by molon** [quasarframework/quasar#9646]
https://github.com/quasarframework/quasar/blob/a59f2a180377c5798cfa9601fcdc029403e21990/app/lib/mode/mode-electron.js#L11

```
>>> quasar mode add electron
App · [sync] Running "yarn add --dev electron@^9.0.0 electron-debug@^3.0.1 electron-devtools-installer@^3.0.0 devtron@^1.4.0"
...
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
```

The new version of electron currently supports the M1 chip, but quasar depend on the old version.

**Comment by rstoenescu** [comment]
Hi,

Quasar v1 does not depend on Electron v9. You can safely upgrade to the newer versions. However, newer Electron versions come with their own breaking changes and you should read their release notes.

On the other hand, Quasar v2 stable release (currently at rc.1 stage) is imminent and /src-electron is spawned following latest and greatest Electron specs out of the box. So, I'd suggest creating a Quasar v2 project if you are just starting out developing your app.

**Comment by molon** [comment]
If I run this command `quasar mode add electron` without success. The folder `src-electron` will not be created. 
So I run this command `yarn upgrade electron@latest` will also make no sense.

**Comment by hawkeye64** [comment]
@molon Like Razvan said. You are using Quasar v1. This means you can't use Electron v9. To use v9, you will need to upgrade to Quasar v2. I am pretty sure this is because of webpack v4 does not support Electron v9, but webpack v5 does, which is now integrated with Quasar v2.

**Comment by rstoenescu** [comment]
Any electron version can be used with Quasar v1.
You pasted:

```
App · [sync] Running "yarn add --dev electron@^9.0.0 electron-debug@^3.0.1 electron-devtools-installer@^3.0.0 devtron@^1.4.0"
...
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
```

Notice Quasar App CLI trying to run the yarn add command. `App · [sync] Running "yarn add --dev electron@^9.0.0 ....`
Then NPM servers replying with `HTTPError: Response code 404 (Not Found)`.

`HTTPError: Response code 404 (Not Found)` --> this is an NPM issue or Electron does not supports your architecture for that version.

**Comment by renzocastillo** [comment]
This is also happening to me when using capacitor

```
yarn install v1.22.21
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @babel/eslint-parser@7.23.10" has unmet peer dependency "@babel/core@^7.11.0".
warning " > eslint-webpack-plugin@2.7.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > workbox-webpack-plugin@6.6.1" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
[5/5] 🔨  Building fresh packages...
[-/4] ⠈ waiting...
[-/4] ⠈ waiting...
[-/4] ⠈ waiting...
error /Users/renzocastillo/Dev/yaku-app/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/renzocastillo/Dev/yaku-app/node_modules/electron
Output:
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/renzocastillo/Dev/yaku-app/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:517:28)
    at module.exports (/Users/renzocastillo/Dev/yaku-app/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/renzocastillo/Dev/yaku-app/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at origin.emit (/Users/renzocastillo/Dev/yaku-app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip',
    href: 'https://github.com/electron/electron/releases/download/v7.3.3/electron-v7.3.3-darwin-arm64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
      statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
      errorCodes: Set(8) {
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      }
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Sun, 03 Mar 2024 03:30:26 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'content-length': '29',
    'x-github-request-id': '3BF3:1BED:31670B7:45CADBF:65E3EED2',
    connection: 'close'
  },
  body: undefined
}
```

Is there any workaround for this?


My package.json is:

```json
{
  "name": "",
  "version": "",
  "description": "",
  "productName": "",
  "author": "",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue ./",
    "icons": "icongenie generate -i AppIcon.png --theme-color 009ffd"
  },
  "dependencies": {
    "@capacitor/core": "^5.5.0",
    "@capacitor/filesystem": "^5.1.4",
    "@capacitor/geolocation": "^5.0.6",
    "@capacitor/share": "^5.0.6",
    "@quasar/extras": "^1.12.2",
    "@vue-leaflet/vue-leaflet": "^0.9.0",
    "axios": "^0.24.0",
    "core-js": "^3.6.5",
    "dotenv": "^16.1.3",
    "firebase": "^9.6.0",
    "js-cookie": "^3.0.1",
    "leaflet": "^1.7.1",
    "quasar": "^2.3.3",
    "vue": "^3.2.45",
    "vue-router": "^4.1.6",
    "vue-tel-input": "^8.1.4"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.16.3",
    "@capacitor/cli": "^5.4.2",
    "@quasar/app-webpack": "^3.12.4",
    "@vue/devtools": "^5.3.4",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-vue": "^7.0.0",
    "eslint-webpack-plugin": "^2.6.0",
    "workbox-webpack-plugin": "^6.4.2"
  },
  "browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ],
  "engines": {
    "node": ">= 12.22.1",
    "npm": ">= 6.13.4",
    "yarn": ">= 1.21.1"
  }
}
```

**Comment by rstoenescu** [comment]
@renzocastillo This is a weird package manager issue, but a second run of the quasar command should work as expected.

**Comment by renzocastillo** [comment]
Thank you! In my case it seemed like `vue-devtools` dev dependency package
was the troublemaker.

More of self problem than a quasar default instalation on m1 issue.
