### ISSUE TITLE
quasar build -m electron  , used builder build,  report an error

### ISSUE THREAD

**Issue by pxr-mm** [quasarframework/quasar#9706]
please help me, thank you very much !!

 "@quasar/app": "^3.0.0-beta.1",
    "electron": "^13.0.1",
    "electron-builder": "^22.4.0",
    "electron-packager": "^14.1.1"
windows

App • Bundling app with electron-builder...
(node:6656) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'build' of undefined
    at D:\projects\admin\CrawlerBot\SpiderBot\node_modules\@quasar\app\lib\electron\index.js:136:21
    at new Promise (<anonymous>)
    at D:\projects\admin\CrawlerBot\SpiderBot\node_modules\@quasar\app\lib\electron\index.js:127:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rstoenescu** [comment]
Can't reproduce. Can you create a reproducing repo pls?

**Comment by hawkeye64** [comment]
Closing for inactivity. Feel free to open again if the issue persists.
