### ISSUE TITLE
source code complie error Merging undefined is not supported

### ISSUE THREAD

**Issue by xwyzsn** [quasarframework/quasar#9776]
**Describe the bug**
Just clone this repo trying to run a dev mode on ui directory. It throws error 
```
TypeError: Merging undefined is not supported
    at mergeWithOptions (H:\desktop\quasar\quasar\ui\node_modules\webpack-merge\dist\index.js:63:19)
    at merge (H:\desktop\quasar\quasar\ui\node_modules\webpack-merge\dist\index.js:52:35)
    at QuasarConfFile.compile (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\lib\quasar-conf-file.js:392:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async goLive (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\bin\quasar-dev:237:3)
```

**Codepen/jsFiddle/Codesandbox (required)**

**To Reproduce**
1. clone this repo
2.  ```cd ui && npm install && npm run dev```

**Expected behavior**
success compile

**Screenshots**
![image](https://user-images.githubusercontent.com/55912637/123119189-e0a36980-d475-11eb-872f-74942390b51a.png)

**Platform (please complete the following information):**
Quasar Version: v2.0.0
@quasar/app Version: v3.0.0

OS:win10
Node: v14.16.0
NPM: 6.14.11

**Additional context**
follow the node waring and try to surround ```await quasarConfFile.compile()  ``` with a catch block and it throw error below
```
 Merging undefined is not supported
    at mergeWithOptions (H:\desktop\quasar\quasar\ui\node_modules\webpack-merge\dist\index.js:63:19)
    at merge (H:\desktop\quasar\quasar\ui\node_modules\webpack-merge\dist\index.js:52:35)
    at QuasarConfFile.compile (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\lib\quasar-conf-file.js:392:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async goLive (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\bin\quasar-dev:238:5)
(node:1288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'store' of undefined
    at regenerateTypesFeatureFlags (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\lib\helpers\types-feature-flags.js:30:20)
    at goLive (H:\desktop\quasar\quasar\ui\node_modules\@quasar\app\bin\quasar-dev:246:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
how can i fixed it ? pls

**Comment by rstoenescu** [comment]
Run "npm run build" inside of "ui" first.
