### ISSUE TITLE
Can't debug a Quasar 2 project

### ISSUE THREAD

**Issue by johnRivs** [quasarframework/quasar#9839]
### Discussed in https://github.com/quasarframework/quasar/discussions/9823

<div type='discussions-op-text'>

<sup>Originally posted by **johnRivs** June 26, 2021</sup>
**Just to clarify, I'm not trying to get help for this particular error. Rather, why the error messages are so unhelpful.**
---

@quasar/app: ^3.0.0
quasar: ^2.0.0

I'm having trouble tracing error messages in the terminal. This doesn't mention a single file I created:
```
[Quasar Dev Webserver] /test -> error during render
TypeError: Cannot read property 'includes' of undefined
    at ssrRender (render-app.js:1186:361)
    at renderComponentSubTree (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:225:13)
    at renderComponentVNode (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:176:16)
    at ssrRenderComponent (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:487:12)
    at ssrRender (render-app.js:1134:81)
    at renderComponentSubTree (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:225:13)
    at renderComponentVNode (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:176:16)
    at renderVNode (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:266:22)
    at renderComponentSubTree (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:231:13)
    at renderComponentVNode (C:\PROJECT\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:176:16)
```

What created hook? This page component in particular (channel.vue) doesn't have any hook. The `55:30` in `chunk-src_pages_channel_vue.js` makes no sense since a) the file doesn't exist and b) channel.vue is actually empty. 
```
[Vue warn]: Unhandled error during execution of created hook
  at <Channel onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
[Quasar Dev Webserver] /test -> error during render
TypeError: Cannot read property 'channel' of undefined
    at Proxy.<anonymous> (chunk-src_pages_channel_vue.js:55:30)
    at Proxy.<anonymous> (C:\PROJECT\node_modules\quasar\dist\quasar.cjs.prod.js:6:461528)
    at callWithErrorHandling (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:36)
    at callWithAsyncErrorHandling (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:165:21)
    at callWithAsyncErrorHandling (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:175:21)
    at callHook (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3182:5)
    at applyOptions (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:3112:9)
    at finishComponentSetup (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7171:9)
    at setupStatefulComponent (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7081:9)
    at setupComponent (C:\PROJECT\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7012:11)
```

When I open the project in the browser, it says
```
Open: chunk-src_pages_channel_vue.js
Unable to locate file source.
```

This happens with other type of errors as well.
</div>

**Comment by hawkeye64** [comment]
@johnRivs I am just taking a guess here, based on the error messages:

```html
<Channel onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
```

To me, this looks like you added a `ref` tag to the `Channel` component, but the reference is missing in your javascript part.
Also, `Channel` should be `channel`, but that's inconsequential.

**Comment by johnRivs** [comment]
> To me, this looks like you added a `ref` tag to the `Channel` component,

Not the case. Also, no `ref` inside it.
![](https://i.imgur.com/VeErVE8.png)

> Also, `Channel` should be `channel`, but that's inconsequential.

I don't understand this. `<Channel onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >` is not something I wrote. It's a page component, I don't use it manually (if that makes sense). It gets instantiated by `<router-view>`.

**Comment by hawkeye64** [comment]
I didn't mean a ref inside the code, but on the Channel tag of wherever is being used. Those being undefined could just be Vue's attempt to add all available states during ssr.

**Comment by johnRivs** [comment]
> I didn't mean a ref inside the code, but on the Channel tag of wherever is being used

Yeah, I meant both on the tag and inside. But in any case, I'm not doing `<channel></channel>` myself. It's a page component being instantiated by Quasar (or rather, vue-router).
![](https://i.imgur.com/w4NsJsI.png)

> could just be Vue's attempt to add all available states during ssr

Don't really understand this. What states? Is that something I control?

Most importantly though, my issue is not this particular error. It's the error messages not helping me trace the error.

**Comment by johnRivs** [comment]
Here's an example with a brand new Quasar 2 project. The store state doesn't have a channel key and I'm trying to figure out how the error message relates to that.

src\pages\Index.vue
```vue
<template>
    <my-component>
        <template #header>
            {{ $store.state.channel }}
        </template>
    </my-component>
</template>
```

src\components\MyComponent.vue
```vue
<template>
    <div>
        <slot name="header"></slot>
    </div>
</template>
```

![](https://i.imgur.com/TubI2Fw.png)

**Comment by yusufkandemir** [comment]
@johnRivs can you please just share a repro with us? That way we can look into this easier, and after we found the problem we might try to think if there is a better way we can handle the errors.

**Comment by rstoenescu** [comment]
Hi,

From what I read the problem here is that the error message is not descriptive enough / doesn't helps debugging.
This error message is reported by Vue and we pass it along. Nothing that we can improve. It's out of our reach.

This problem ("make error message more descriptive/helpful") should be reported to the Vue team.

Feel free to still comment here and we'll try to help you as much as we can, but closing this ticket as it's nothing actionable here from our part.
